### ISSUE TITLE
Missing whitespace green indicator in version 0.4.0

### ISSUE THREAD

**Issue by realpasro09** [Microsoft/vscode-tslint#10]
I was using the version 0.3.0 and everything work good, then today I upgrade to the version 0.4.0 and the whitespace lint errors in green are not showed anymore.
Also unused variables were marked in green before the update

**Comment by egamma** [comment]
The published package is incomplete, will fix asap

**Comment by egamma** [comment]
Republished the package.

**Comment by realpasro09** [comment]
awesome :+1: thank you
