### ISSUE TITLE
Sample gulpfile.js in Market place does not work

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-tslint#100]
There is a sample gulpfile.js in the [Market place](https://marketplace.visualstudio.com/items?itemName=eg2.tslint)

```
'use strict';
const gulp = require('gulp');
const gulp_tslint = require('gulp-tslint');
//...
gulp.task('tslint', () => {
    return gulp.src(['**/*.ts', '!**/*.d.ts', '!node_modules/**'])
      .pipe(gulp_tslint())
      .pipe(gulp_tslint.report());
});
```

I used the above gulpfile to lint and it does not shows any problems in VS Code.

Above gulp task generates a single line output for all errors which does not matches problem matcher pattern. After breaking down the message into multiple lines it worked

Here are the versions of modules I used

```
"gulp": "^3.8.9",
 "gulp-tslint": "^4.3.0",
  "tslint": "^3.3.0",
  "typescript": "^2.0.3",
```

I updated to latest gulp-tslint. This also does not work which is producing line by line errors and also consolidated message

Here is the gulp file I used to breakdown into line by line errors:

```
'use strict';
const gulp = require('gulp');
const gulp_tslint = require('gulp-tslint');

function reportFailures(failures) {
    failures.forEach(failure => {
        const name = failure.name || failure.fileName;
        const position = failure.startPosition;
        const line = position.lineAndCharacter ? position.lineAndCharacter.line : position.line;
        const character = position.lineAndCharacter ? position.lineAndCharacter.character : position.character;

        console.error(`${ name }:${ line + 1}:${ character + 1 }:${ failure.failure }`);
    });
}

//...
gulp.task('tslint', () => {
   return gulp.src(['**/*.ts', '!**/*.d.ts', '!node_modules/**'])
         .pipe(gulp_tslint())
      .pipe(gulp_tslint.report(reportFailures));
});
```

It would be nice if the provided sample works out of the box

**Comment by egamma** [comment]
Cannot repro in the latest, closing.
