### ISSUE TITLE
Custom rules do not produce warnings on text typing

### ISSUE THREAD

**Issue by kkovalevskiy** [Microsoft/vscode-tslint#101]
I've written several my own rules for tslint, but it looks like they are not executed when I'm typing text. I've set both settings : "tslint.rulesDirectory": %RelativePathToMyCompiledRulesFromWorkspaceRoot% in settings.json and also configured "rulesDirectory" in tslint.json file, but it looks like vscode-tslint is ignoring my rules. If I run tslint as a gulp task, all work fine. What should I do to enable warnings on type for my own rules?

Also I'd be great if vscode-tslint will log all linting related output in some "verbose" mode. At the moment all that I see in output is just
`[Info  - 11:41:56 AM] Linter is running.`
and it logs only if smth happened.

**Comment by egamma** [comment]
@kkovalevskiy 
Do you have tslint installed globally or locally? 

We are using custom rules for VS Code itself and there it works, pls see:
https://github.com/Microsoft/vscode/blob/master/.vscode/settings.json#L19
We have installed tslint locally inside the workspace.

**Comment by kkovalevskiy** [comment]
I've found the issue. My rule is based on path to current file (it works only for files in specific folders). when the rule is being executed from vscode-tslint `node.path` has global path, while when I'm executing it from gulp it has relative path.

Looks like I need to fix my rule somehow

**Comment by kkovalevskiy** [comment]
BTW, How can I log some useful info when rule is executing and see it in output window in vs code? Is it possible?

**Comment by egamma** [comment]
>BTW, How can I log some useful info when rule is executing and see it in output window in vs code? Is it possible?

@kkovalevskiy writing to console.log should be forwarded to the output channel, did you try this and it didn't work? If the output doesn't show in the output channel, can you open the dev tools (Help>Toggle Dev Tools) and check the console there.

**Comment by kkovalevskiy** [comment]
Yep, this is the first what I tried, and there is no output neither in output window nor in dev tools.
