### ISSUE TITLE
When tslint is not found, the new status bar item does not show error

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-tslint#102]
While testing https://github.com/Microsoft/vscode/issues/12603

> Without having tslint and typescript installed try to lint a .ts file. Create a tslint.json file using the command palette. Verify that the status bar item shows an error and the output channel shows the reason.

The output channel does show the reason, but the status bar item does not appear at all

![image](https://cloud.githubusercontent.com/assets/16890566/18927287/232835b0-8570-11e6-8b96-7bae8078036f.png)

**Comment by egamma** [comment]
Actually this is the expected behaviour, the status bar item shows up as soon as the tslint server is running, in this case the server does not start.
