### ISSUE TITLE
Output channel does not show error when a workspace is opened with invalid tslint.json

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-tslint#105]
While testing https://github.com/Microsoft/vscode/issues/12603
1. Make a syntax error in tslint.json
2. Reload window, open a ts file and let linting begin
3. Info box pops up saying "vscode-tslint: Cannot read tslint configuration - 'Unexpected string in JSON at position ..'"
4. But output channel says "Linter is running" and nothing else
5. The status bar item does not show any error

**Comment by egamma** [comment]
Cannot reproduce in the latest, pls reopen the issue if you can still reproduce it.
