### ISSUE TITLE
Improved error messages when the server will close

### ISSUE THREAD

**Issue by leewinder** [Microsoft/vscode-tslint#106]
I was getting the following error when trying to use TSLint.

[Info  - 2:45:56 PM] Connection to server got closed. Server will restart.
[Info  - 2:46:00 PM] Connection to server got closed. Server will restart.
[Info  - 2:46:04 PM] Connection to server got closed. Server will restart.
[Info  - 2:46:07 PM] Connection to server got closed. Server will restart.
[Error - 2:46:09 PM] Connection to server got closed. Server will not be restarted.

I was incorrectly setting tslint.nodePath to 'my_node_path/tslint/bin' but it needed to be simply 'my_node_path'.  Luckily just messing around with the settings fixed this.

Would be helpful if better output messages were given to help identify what the problems are.

**Comment by egamma** [comment]
In the latest I'm now getting the error message the tslint cannot be loaded when the nodePath setting points to an incorrect location, closing.
