### ISSUE TITLE
Show source rule of warning/error

### ISSUE THREAD

**Issue by beckend** [Microsoft/vscode-tslint#109]
Show the rule details along with the actual warning/error?

**Comment by egamma** [comment]
The rule id is shown since a while. Do you have more in mind?
![image](https://cloud.githubusercontent.com/assets/172399/20743606/9f018284-b6d7-11e6-8a39-85a53147bb4a.png)

**Comment by egamma** [comment]
@beckend closing for now, pls reopen if your enhancement request isn't covered in the latest.

**Comment by beckend** [comment]
Thanks, I missed this ping.
This was exactly what I was looking for.

**Comment by egamma** [comment]
@beckend happy end then, thanks for your confirmation.
