### ISSUE TITLE
Add option to add tslint:disable-next-line

### ISSUE THREAD

**Issue by CaselIT** [Microsoft/vscode-tslint#110]
Would be nice if tslint showed among the solution options (showed on the light buld) the ability to disable the rule that is causing the error by adding a `// tslint:disable-next-line:rule`.
Alternately the simpler `// tslint:disable-next-line` to disable all rules on that line would be still appreciated.

Thanks

**Comment by egamma** [comment]
@CaselIT I like this feature. 

We will then have to distinguish between quick fixes we want to apply always automatically and ones a user explicitly requests. Otherwise we fix all the warnings by disabling the checking 😄

**Comment by CaselIT** [comment]
I think that it should only appear on the light bulb next to an error, not in the command palette since we are creating an exception for specific and limited part of the code.

**Comment by egamma** [comment]
Added in the latest. Will publish to the market place soon.

![image](https://cloud.githubusercontent.com/assets/172399/20812782/30099f28-b813-11e6-81a6-883677959788.png)

![image](https://cloud.githubusercontent.com/assets/172399/20812797/3ece5a8a-b813-11e6-8fe5-acfe46ae0d05.png)

**Comment by CaselIT** [comment]
Great, thanks!
