### ISSUE TITLE
Possible code duplication in tslintAutoFix.ts

### ISSUE THREAD

**Issue by CaselIT** [Microsoft/vscode-tslint#111]
I was browsing the code and I've found a possible duplicate autofix rule in the file `tslintAutoFix.ts`
The `no-var-keyword` rule is repeated [on line 106](https://github.com/Microsoft/vscode-tslint/blob/master/tslint-server/src/tslintAutoFix.ts#L106) and [on line 127](https://github.com/Microsoft/vscode-tslint/blob/master/tslint-server/src/tslintAutoFix.ts#L127)

Maybe one of the two one could be changed to

``` ts
autoFix = {
    tsLintCode: "no-var-keyword",
    tsLintMessage: "Forbidden 'var' keyword, use 'let' or 'const' instead",
    autoFixMessage: "Replace var by const",
    autoFix: (codeBefore: string): string => {
        let codeAfter = "const"
        return codeAfter
    }
};
```

so that one can choose to replace the `var` with `let` or `const`

**Comment by CaselIT** [comment]
I've checked and at the moment only a fix is possible for any particular error so my proposed solution as is would not work.
I was thinking about adding support for multiple solutions for a problem but I do not know how to best handle the "fix all problem" scenario when more than one solution can be applied. Do you have any suggestion about this @egamma ?

**Comment by egamma** [comment]
We have deprecated the custom VS Code provide auto fixes in favor of the tslint provided one. So this fix is currently no longer available. Now, tslint supports autofixing the recommendation is to contribute an auto fix for this rule in the tslint project, then everybody profits from it.

Closing this issue.
