### ISSUE TITLE
"Could not find the following rules specified in the configuration"

### ISSUE THREAD

**Issue by canda** [Microsoft/vscode-tslint#113]
I'm using some custom rules and they are specified on the tslint.json rulesDirectory attribute

```
  "rulesDirectory": [
    "node_modules/codelyzer",
    "node_modules/tslint-eslint-rules/dist/rules"
  ]
```

When I open the folder that contains the tslint.json file on its root, it works fine
But when I open a higher level folder that contains the folder that contains tslint.json file, it gives me this error on the output.
Perhaps its not resolving right the relative path?

**Comment by egamma** [comment]
@canda 

>But when I open a higher level folder that contains the folder that contains tslint.json file, it gives me this error on the output.

What is the error? Do you still get diagnostics from tslint in this case?

Can you pls try to use the vscode `tslint.rulesDirectory` setting in the .vscode/settings.json folder to resolve the path?

What version of vscode, vscode-tslint, tslint are you using?

Do you get any linting

**Comment by c1rus** [comment]
same problem here, linting is completly broken and the error is:
`vscode-tslint: 'Could not find custom rule directory`

i need to setup relative path to tslint.json, not to opened folder.

**broken:**
solution
&nbsp;&nbsp;&nbsp;project
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node_modules
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tslint.json

**works:**
project
&nbsp;&nbsp;&nbsp;node_modules
&nbsp;&nbsp;&nbsp;tslint.json

vscode: 1.6.1
tslint: 3.15.1
vscode-tslint: 0.5.39

**Comment by canda** [comment]
@egamma 
I don't get any linting at all
Versions
VSCode: 1.6.1
vscode-tslint: 0.5.39
Not sure if it's using the global tslint or the one installed inside my project node_modules folder
global tslint: 3.5.0
local tslint: 3.15.1

This is the error in the console
```
[Info  - 9:56:16 AM] Linter is running.
[Info  - 9:56:16 AM] vscode-tslint: 'Could not find the following rules specified in the configuration:
directive-selector-name
component-selector-name
directive-selector-type
component-selector-type
directive-selector-prefix
component-selector-prefix
use-input-property-decorator
use-output-property-decorator
use-host-property-decorator
no-attribute-parameter-decorator
no-input-rename
no-output-rename
no-forward-ref
use-life-cycle-interface
use-pipe-transform-interface
pipe-naming
component-class-suffix
directive-class-suffix
no-angle-bracket-type-assertion
no-reference
one-variable-per-declaration
use-isnan' while validating: /home/canda/projects/twc_cms/docroot/sites/all/modules/wu/src/components/wu-favorites/wu-favorites.ts stacktrace: Error: Could not find the following rules specified in the configuration:
directive-selector-name
component-selector-name
directive-selector-type
component-selector-type
directive-selector-prefix
component-selector-prefix
use-input-property-decorator
use-output-property-decorator
use-host-property-decorator
no-attribute-parameter-decorator
no-input-rename
no-output-rename
no-forward-ref
use-life-cycle-interface
use-pipe-transform-interface
pipe-naming
component-class-suffix
directive-class-suffix
no-angle-bracket-type-assertion
no-reference
one-variable-per-declaration
use-isnan
```

And if I point rules directory to my custom rules directory, it throws an error telling me that it can't find some tslint default rules

```
[Info  - 10:10:40 AM] vscode-tslint: 'Could not find the following rules specified in the configuration:
no-angle-bracket-type-assertion
no-reference
one-variable-per-declaration'
```

**Comment by egamma** [comment]
Bug cleansing, closing this issue, pls reopen if this still happens with the latest versions.
