### ISSUE TITLE
command 'tslint.fixAllProblems' not found

### ISSUE THREAD

**Issue by sasidhar** [Microsoft/vscode-tslint#114]
<img width="634" alt="fix-all-auto-fixable-problems" src="https://cloud.githubusercontent.com/assets/897339/19546127/7c222ebe-96aa-11e6-94a7-584b2d3fbbf3.png">

<img width="562" alt="fixallproblems-not-found" src="https://cloud.githubusercontent.com/assets/897339/19524147/6142be30-963a-11e6-867e-08176096e4b8.png">

**Comment by yyjazsf** [comment]
command:    Fix all auto-fixable problems

**Comment by egamma** [comment]
fixed in vscode-tslint 0.6.0.
