### ISSUE TITLE
after deleting a file with warnings, the warnings are never cleared

### ISSUE THREAD

**Issue by MastroLindus** [Microsoft/vscode-tslint#118]
-Create a file with some warnings in it
-Delete the file
-The warnings will stay in the console until you restart visual code

**Comment by egamma** [comment]
@MastroLindus I cannot reproduce this with the latest vscode-tslint 0.7.1, see the attached video. 

Please reopen the issue if you can still reproduce and provide more details about your setup.

![delete-file](https://cloud.githubusercontent.com/assets/172399/21053957/eaf48c58-be2b-11e6-8417-3b430b804990.gif)
