### ISSUE TITLE
vscode-tslint: Cannot read tslint configuration - 'linter.findConfiguration is not a function'

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode-tslint#123]
vscode-tslint: 0.5.40
tslint: 4.0

Just create new project and this error shows up.

**Comment by bradenhs** [comment]
Looks like tslint just updated to v4.0.0. Going back to version 3.15.1 fixed it for me.

**Comment by rlasjunies** [comment]
I've the same issue.

Can you, please, try putting:
    `"tslint.configFile": "tslint.json",`

The extension is looking for the tslint config file.

**Comment by CoenraadS** [comment]
@bradenhs how do you download old versions?

**Comment by CoenraadS** [comment]
@bradenhs 

I ran ```npm -g install tslint@3.15.1 typescript```

However I get this message

```[Info  - 3:11:02 pm] Failed to load the TSLint library.
To use TSLint in this workspace please install tslint using 'npm install tslint' or globally using 'npm install -g tslint'.
You need to reopen the workspace after installing tslint.```

Any ideas?

**Comment by egamma** [comment]
pls see also this comment https://github.com/Microsoft/vscode-tslint/issues/124#issuecomment-261755169

**Comment by egamma** [comment]
PR is available https://github.com/Microsoft/vscode-tslint/pull/125, waiting until other tools like gulp, grunt updated to tslint 4.0.

**Comment by YuichiNukiyama** [comment]
[gulp-tslint](https://github.com/panuhorsmalahti/gulp-tslint/commit/38da472fa24267ba7f227c59cf4372b4624d69be) has been updated!

**Comment by Izzmo** [comment]
@egamma beat me to it... but I do have some comments for you on your PR.

**Comment by egamma** [comment]
Published version 0.6.0 that supports both tslint < 4.0 and tslint >= 4.0

**Comment by yahyaKacem** [comment]
Hi, @egamma I'm still having the same problem: `vscode-tslint: Cannot read tslint configuration - 'linter.findConfiguration is not a function'` after updating to vscode-tslint v0.6.0, with tslint v4.0.1,
I reloaded to enable the new version I even restarted the editor but still the same error.

**Comment by Mosho1** [comment]
Still seeing this as well.

**Comment by unional** [comment]
Do you have a lower version of tslint locally?

It seems to be working for me.

**Comment by yahyaKacem** [comment]
@unional actually I didn't have tslint installed globally at all and the local version is v4.0.0 I updated the local to 4.0.1 and installed it globally still the same error, but after uninstalling it globally it start to look like it's working but it seems like the error is just suppressed and it's not working properly, I don't see the green line under a long line anymore, maybe other stuff too, but that's what I see now.

**Comment by egamma** [comment]
When I install tslint 4.0.0 then I can reproduce the 'findConfiguration error. 
When I install tslint 4.0.1 then I cannot reproduce the problem and tslint is working properly.

Looks like a bug in the version check for 4.0.0. I'll look further into it, but for now the fix is to make sure that you have the latest tslint 4.0.1 installed.

**Comment by egamma** [comment]
The version check didn't recognize 4.0.0 correctly. Fixed using e2f69e175c811bbc71f48ca90bb89c4cbb6a7b30 and published 0.6.1.

**Comment by yahyaKacem** [comment]
@egamma sorry, I wasn't clear, for v4.0.1 the error is not thrown but tslint is not working,
I have temporary long line where I disabled tslint for them by adding this comment 
```
/* tslint:disable */
let veryLongVariable: string = 'ver long line here exceed the 100 char length defined in my tslint.json';
/* tslint:enable */
```
but when I remove the first comment like this:
```
let veryLongVariable: string = 'ver long line here exceed the 100 char length defined in my tslint.json';
/* tslint:enable */
```
I don't see the green line under it anymore which was previously shown before the error and its fix.

**Comment by egamma** [comment]
@yahyaKacem this looks like a separate issue than this one. With the latest update I get tslint diagnostics for both tslint 4.0.0 and tslint 4.0.1. See my test case below

`tslint.json`
```json
{
    "rules": {
        "quotemark": [
            true,
            "double"
        ],
        "no-consecutive-blank-lines": true
    },
    "jsRules": {
        "quotemark": [
            true,
            "double"
        ],
        "no-consecutive-blank-lines": true
    }
}
```
![image](https://cloud.githubusercontent.com/assets/172399/20522956/1c7ac53e-b0b3-11e6-9cdf-2eb06b90be11.png)

Do you get tslint diagnostics for this scenario?

**Comment by egamma** [comment]
@yahyaKacem I'm unable to reproduce your problem, pls see the animated gif below

![tslint](https://cloud.githubusercontent.com/assets/172399/20523566/fc3f1768-b0b5-11e6-8558-6168f4addc32.gif)

**Comment by yahyaKacem** [comment]
@egamma thank you for your fast response, and sorry for my delayed one, I opened a new issue for this #131 .
