### ISSUE TITLE
vscode-tslint: Cannot read tslint configuration

### ISSUE THREAD

**Issue by wonbyte** [Microsoft/vscode-tslint#124]
I am getting the following in vscode; 

vscode-tslint: Cannot read tslint configuration - 'linter.findConfiguration is not a function'

running:
vscode: Version 1.7.1 (1.7.1)
macOS Sierra 10.12.1
tslint@4.0.0 
TSLint plugin 0.5.40

**Comment by Izzmo** [comment]
I can reproduce this as well.

**Comment by zachrip** [comment]
+1

**Comment by Izzmo** [comment]
@wonbyte @zachrip you need to go back down to v3.x. The plugins for vscode, gulp, and grunt, have not been updated to work with v4.x yet.

**Comment by YuichiNukiyama** [comment]
Maybe, this [PR](https://github.com/palantir/tslint/pull/1720) is the cause.

**Comment by aleksey-pastuhov** [comment]
+1

**Comment by egamma** [comment]
Closing as a duplicate of #123.

@YuichiNukiyama the analysis is correct the tslint API has changed in tslint 4.0 and the vscode-tslint extension needs to be adapted.

**Comment by egamma** [comment]
@Izzmo I've created a PR https://github.com/Microsoft/vscode-tslint/pull/125
