### ISSUE TITLE
Array<T> to T[] Autofix Wipes out Code

### ISSUE THREAD

**Issue by tomwanzek** [Microsoft/vscode-tslint#129]
I just encountered the following bug:

The tslint extension highlights occurrences of `Array<T>` with the warning that for "simple" types `T[]` should be used. While the highlighted code is correctly identified, based on the rule, applying autofix wipes out the code instead of replacing it. (This applies for individual as well as "all" application of the autofix)

Environment:
* TSLint for VSCode Extension v 0.6.3
* VSCode 1.7.1

Thanks for looking into it. Love the tool 👍

**Comment by michaeljota** [comment]
I think this maybe related to #121 

Related, but I don't see this as duplicated.

**Comment by egamma** [comment]
These fixes are not yet properly supported. I've disabled them in 0.6.5.

Adding support for such fixes is tracked in #135. Closing this issue.
