### ISSUE TITLE
Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/vscode-tslint#13]
Ported from Microsoft/vscode#921.

When I have a project running off of TypeScript 1.6.2, the editor behaves as normal with tslint 0.5.1.  When I upgrade the project to TypeScript 1.7.3, in the editor I constantly am getting `ERROR: Cannot read property 'kind' of undefined`.  Reverting the project back to 1.6.2, doing an `npm install` fixes the issue. Also uninstalling the tslint extension also fixes the issue.

![vcode issue](https://cloud.githubusercontent.com/assets/1282577/11531090/2e0150ae-98f2-11e5-86b2-27ee3f53ddc6.gif)

**Comment by egamma** [comment]
I cannot reproduce this. I'm using typescript 1.7.3 and tslint 3.1.1.
You say that you are using tslint 0.5.1 which appears old. What happens when you update tslint to 3.1.1?

**Comment by egamma** [comment]
You wrote:
> the editor behaves as normal with tslint 0.5.1

I guess you are referring to the version of vscode-tslint and not the tslint version.

Can you share your tslint.json?

**Comment by kitsonk** [comment]
Correct, the extension version available in VSC.

[tslint.json](https://github.com/kitsonk/actions/blob/master/tslint.json):

```json
{
	"rules": {
		"ban": [],
		"class-name": true,
		"comment-format": [ true, "check-space" ],
		"curly": true,
		"eofline": true,
		"forin": false,
		"interface-name": false,
		"jsdoc-format": true,
		"label-position": true,
		"label-undefined": true,
		"max-line-length": false,
		"no-any": false,
		"no-arg": true,
		"no-bitwise": false,
		"no-console": false,
		"no-consecutive-blank-lines": true,
		"no-construct": false,
		"no-constructor-vars": true,
		"no-debugger": true,
		"no-duplicate-key": true,
		"no-duplicate-variable": true,
		"no-empty": false,
		"no-eval": true,
		"no-shadowed-variable": false,
		"no-string-literal": false,
		"no-switch-case-fall-through": false,
		"no-trailing-comma": true,
		"no-trailing-whitespace": true,
		"no-unreachable": true,
		"no-unused-expression": false,
		"no-unused-variable": true,
		"no-use-before-declare": false,
		"no-var-keyword": true,
		"no-var-requires": false,
		"one-line": [ true, "check-open-brace", "check-whitespace" ],
		"quotemark": [ true, "single" ],
		"radix": true,
		"semicolon": true,
		"triple-equals": [ true, "allow-null-check" ],
		"typedef": false,
		"typedef-whitespace": [ true, {
			"index-signature": "nospace",
			"parameter": "nospace",
			"property-declaration": "nospace",
			"variable-declaration": "nospace"
		} ],
		"use-strict": false,
		"variable-name": false,
		"whitespace": [ true, "check-branch", "check-decl", "check-operator", "check-module", "check-separator", "check-type", "check-typecast" ]
	}
}
```

It does appear to be upstream palantir/tslint#832.  It is addressed in 3.1.1, so all that is needed is to update the version dependency.

**Comment by kitsonk** [comment]
Oh, I see... the extension uses the installed version of tslint.  I have upgraded to version 3.1.1 of tslint in my project and re-enabled the extension and all is working perfectly. Thank you.

**Comment by egamma** [comment]
Thank you for your responsiveness. 

I'll update the README and document that tslint version 3.1.1 is required.
