### ISSUE TITLE
 'Cannot read property 'innerText' of undefined' while validating

### ISSUE THREAD

**Issue by michaeljota** [Microsoft/vscode-tslint#130]
I don't know what trigger this error. But keeps showing since the update.

**Comment by jmalonzo** [comment]
I seem to notice this on TS code with an issue with ordered-imports. Fixing the first ordered-import issue seems to fix it for me.

**Comment by egamma** [comment]
@michaeljota it is not clear whether this an issue with tslint or the vscode extension. Therefore:
- do you also get this error when you run tslint from the command line
- where does this error show-up? 
- What is shown when you click the 'tslint' statusbar item in the bottom right?

**Comment by bvanreeven** [comment]
We can reproduce the problem by having `tslint` installed as a dependency, enabling the `"ordered-imports"` rule and then creating the following TypeScript file:

```typescript
import { Formatters, Configuration } from "tslint";
import { Rules, Linter } from "tslint";
```

Running `tslint` on the command-line does not yield the error, but just the normal tslint warnings you would expect.

Clicking the 'TSLint' statusbar item yields only the following output: `[Info  - 11:12:01] Linter is running.`

Attached a screenshot of the stack trace as far as VSCode allows us to read it:
![image](https://cloud.githubusercontent.com/assets/353404/20557912/e8eec182-b16d-11e6-8703-0b3e9851c9c3.png)

**Comment by egamma** [comment]
@bvanreeven thanks this clarifies things. 

The code fails where it processes an autofix that comes from the ordered-imports rule in tslint at this line in vscode-tslint: 
   https://github.com/Microsoft/vscode-tslint/blob/master/tslint-server/src/server.ts#L175

@rlasjunies I suspect we run into this limitation `this algo does not support several fixes provided by tslint engine. Only the first element of the innerReplacements array is used`

**Comment by michaeljota** [comment]
I think the autofix for ordered-imports should be disable. It does not however "fix" the issue, just duplicate the imports in a giving order.

**Comment by egamma** [comment]
@michaeljota we can do this, but it is not clear to me whether this is an issue of the `ordered-imports` rule or whether is an issue with the way vscode-tslint applies the fix.

**Comment by michaeljota** [comment]
With this and #121, maybe is the way TSLint itself applies fixes? If you use TSLint to applied fixes.

**Comment by egamma** [comment]
@rlasjunies according to the release notes there are now  more rules with fixes https://palantir.github.io/tslint/2016/11/17/new-for-4.0.html.  We need to make a test pass to ensure they are supported properly by vscode-tslint. One fallback is that we disable the tslint fixing until we have confidence in the validation support. What do you think?

**Comment by egamma** [comment]
@michaeljota if we let tslint apply the fixes then the entire document contents is replaced. This is bad for VS Code, since this would mean that your markers, e.g., a breakpoint will not be updated. For this reason the edits need to be minimal to preserve the existing markers.

**Comment by michaeljota** [comment]
I see. I just was wondering it, because there are many auto fix functions broken after the update. But, it should be expected in a major release.

**Comment by egamma** [comment]
@michaeljota you are right:

>I think the autofix for ordered-imports should be disable. It does not however "fix" the issue, just duplicate the imports in a giving order.

the fix rule looks incorrect. I've disabled it and will make a new version of vscode-tslint available.

**Comment by rlasjunies** [comment]
Hi @egamma ,

I've analyze the issue. The problem is seems to be here:

> 	//check tsl fix
>	if (!!problem.fix) {
>		fixText = problem.fix.innerReplacements[0].innerText;
>		// fixStart = problem.fix.innerReplacements[0].innerStart;
>		// fixEnd = problem.fix.innerReplacements[0].innerStart + problem.fix.innerReplacements[0].innerLength;
>		fixStart = problem.startPosition;
>		fixEnd = problem.endPosition;
>	}

My understanding is that the fixStart/fixEnd position used in the edits array:
>		edits[computeKey(diagnostic)] = {
>			label: `Fix this "${problem.failure}" tslint warning?`,
>			documentVersion: document.version,
>			ruleId: problem.failure,
>			edit: {
>				range: [fixStart, fixEnd],
>				text: fixText
>			}
>		}; 

does not match with the file content. 

For sure, edit based on the range start/end Position provided by tsl does not work. Can we base the edits on the innerReplacements (innerStart+innerLenght)? 

I would follow your recommandation to deactivate the autoFix until we found the solution. 

Unfortunatelly, I've tried hours without success to debug the server. Does something change? what is your procedure to have server debugging running?

**Comment by egamma** [comment]
@rlasjunies thanks for looking into this

>Unfortunatelly, I've tried hours without success to debug the server. Does something change? what is your procedure to have server debugging running?

I've failed attaching the debugger to the server as well. I'm currently remote from the team and cannot look into the issue together with them.

The way I've debugged is with good all print statements:
```javascript
connection.console.log(util.inspect(object))
```
This output shows up in the eslint output channel.
I'll also look into this again.
