### ISSUE TITLE
Wrong warnings in tslint.json for accepted configuration values

### ISSUE THREAD

**Issue by Martin-Wegner** [Microsoft/vscode-tslint#132]
I'm using VSCode 1.7.2, TSLint plugin 0.6.3 and TSLint 4.0.1.

When I open the tslint.json file in VSCode I get serveral wrong warnings about my configuration values:

`"cyclomatic-complexity": true,` -> `Incorrect type. Expected "array"`

`"no-consecutive-blank-lines": true,` -> `Incorrect type. Expected "array"`

`"object-literal-key-quotes": [true, "consistent-as-needed"],` -> `Value is not an accepted value. Valid values: [true,false,"always","as-needed"]`

`"one-variable-per-declaration": true,` -> `Incorrect type. Expected "array"`

`"only-arrow-functions": true,` -> `Incorrect type. Expected "array"`

`"typedef": [true, "arrow-call-signature"],` -> `Value is not an accepted value. Valid values: [true,false,"call-signature","parameter","arrow-parameter","property-declaration","variable-declaration","member-variable-declaration"]`

**Comment by egamma** [comment]
These warnings come directly from the tslint API, vscode-tslint just shows them to you. Please report the issue against the tslint repository

**Comment by Martin-Wegner** [comment]
https://github.com/SchemaStore/schemastore/issues/245

**Comment by egamma** [comment]
@Martin-Wegner thanks 🌷
