### ISSUE TITLE
Don't lint JS files when tslint version < 4.0

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode-tslint#133]
In the current version of vscode TSLint seems to run alongside ESLint but with less success. Is this normal behavior? TSLint seems to run although it cannot work with the js file open.

[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version 1.7.2
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:06:37.428Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0

[OK]
`
[Info  - 16:30:01] vscode-tslint: 'Invalid source file: <name>.js. Ensure that the files supplied to lint have a .ts or .tsx extension.' while validating: <name>.js stacktrace: Error: Invalid source file: <name>.js. Ensure that the files supplied to lint have a .ts or .tsx extension.
    at Linter.lint (<username>\AppData\Roaming\npm\node_modules\tslint\lib\tslint.js:49:19)
    at doValidate (<username>\.vscode\extensions\eg2.tslint-0.6.3\server\server.js:296:29)
    at validateTextDocument (<username>\.vscode\extensions\eg2.tslint-0.6.3\server\server.js:209:27)
    at Delayer.d.trigger [as task] (<username>\.vscode\extensions\eg2.tslint-0.6.3\server\server.js:362:9)
    at completionPromise.Promise.then (<username>\.vscode\extensions\eg2.tslint-0.6.3\server\delayer.js:19:35)
`

**Comment by egamma** [comment]
@con-ssc Which version of tslint are you using? Support for linting .js files has been added in one of the more recent tslint versions. Can you try with tslint 4.0.1.

@YuichiNukiyama  fyi

**Comment by con-ssc** [comment]
Okay, I just updated to tslint 4.0.1 and it seems to work. I don't know what version I had before the update though.

**Comment by egamma** [comment]
FYI you can define the rules for js linting in  a `jsRules` section. @YuichiNukiyama is this documented anywhere?

**Comment by con-ssc** [comment]
Does that mean I could go and only use TSLint and remove ESLint?

**Comment by egamma** [comment]
I defer to @YuichiNukiyama he contributed the PR to tslint.

**Comment by egamma** [comment]
The support for .js files is actually mentioned in the release notes https://palantir.github.io/tslint/2016/11/17/new-for-4.0.html

**Comment by YuichiNukiyama** [comment]
@con-ssc 
> Okay, I just updated to tslint 4.0.1 and it seems to work.
> I don't know what version I had before the update though.

Support for linting .js files has been added in v4.0.0. 

> Does that mean I could go and only use TSLint and remove ESLint?

Your ideas are half full and half wrong. TSLint support for linting .js files, but TSlint have fewer rules than ESLint. If you have only a few .js flies that are supplementarily used in the TS project (e.g. gulp.js etc), you can remove ESLint. While you have a lot of .js files, TSLint isn't convinient as ESLint, so you better keep using ESLint.

**Comment by con-ssc** [comment]
Would it be possible to prevent vscode-tslint from running on js files if a not appropriate tslint version is available?

**Comment by egamma** [comment]
@con-ssc yes this is a good idea and current code already includes a version check. I've changed the title.
