### ISSUE TITLE
How to easily debug the server side code?

### ISSUE THREAD

**Issue by rlasjunies** [Microsoft/vscode-tslint#134]

**Comment by rlasjunies** [comment]
Hi @egamma,

 The purpose of this issue is to track this activities. I do not like to mix different topic in the same issues. There are too many open issue on going to add complexity.

As you said 1 way is writing below code in the server side, the message will appears in the console of the client (being in dev. mode):

`connection.console.log(util.inspect(object))
`

**Comment by rlasjunies** [comment]
Don't you think the problem of debugging can be linked to the version of `"vscode-languageclient": "^2.5.0"` or `"vscode": "^1.0.0"` compare to the "real" version of the vscode 1.7.x?

**Comment by rlasjunies** [comment]
Clicking on "TSLint" in the bottom toolbar shows also the console from the server.

![image](https://cloud.githubusercontent.com/assets/1439791/20599424/66fbab90-b24e-11e6-85d5-06b8739d0e24.png)

**Comment by egamma** [comment]
@rlasjunies here is away how I could get it to work.
In the client where you define the client options there is a 4th argument that can be set to true and that means 'forceDebug'.

file `vscode-tslint\tslint\extension.ts` line 192 add a 4th boolean argument and set it to true
```typescript
	let client = new LanguageClient('tslint', serverOptions, clientOptions, true);
```

**Comment by rlasjunies** [comment]
@egamma,  thank for the advice but still not work to debug server side in my environment. I've the latest packages vscode-language server: 2.6.2 / client: 2.6.3 in both project.

**Comment by egamma** [comment]
@rlasjunies with the latest I can successfully attach but breakpoints are not hit. I can make a breakpoint hit once the file is opened by the debugger through another means:
- catch All exceptions
- when an exception is thrown open the file server.ts from the call chain
- from then on breakpoints are hit.

One possible work around is to insert JavaScript `debugger;` statements into server.ts.

Suspect an issue with source mapping.

**Comment by egamma** [comment]
This is now tracked in https://github.com/Microsoft/vscode/issues/16143, closing this issue.
