### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by Crevil** [Microsoft/vscode-tslint#139]
Make changes more clear by adding a CHANGELOG.md to the root. This enables the extension explorer to show changes and make the project progress more transparent.

This was enabled in the October VS Code 1.7 release: https://code.visualstudio.com/updates#_changelogs

**Comment by egamma** [comment]
There is already a CHANGELOG.md in the root of the extension, pls see:
https://github.com/Microsoft/vscode-tslint/blob/master/tslint/CHANGELOG.md

What am I missing?

**Comment by Crevil** [comment]
Ah, stupid me. Missed that. NVM.
But it is not updated to latest versions?

**Comment by egamma** [comment]
I do my best :smile:. It looks up to date to me. I do not list individual bug fixes for each update. Do you miss anything in particular?

**Comment by Crevil** [comment]
All right. I expected that, but sure thing, if no bug-fixing is listed, it is up to date. :)

Keep it up and thanks for the extension. 👍
