### ISSUE TITLE
Cannot find module 'tslint/lib/lint'

### ISSUE THREAD

**Issue by Z3roCoder** [Microsoft/vscode-tslint#142]
VSCode version: 1.7.2
VSCode TSLint-Version: 0.6.6

I am getting this error constantly since the recent few updates. TSLint and Typescript is installed in my current workspace, but also globally, as recommended in the Prerequisites. What could be causing this error?

This is a great tool and I would like to keep using it :)

**Comment by egamma** [comment]
Which version of tslint are you using? I suspect you are using TSLint > 4.0.0. There were breaking API changes in this version and not all rule providers have caught up with them yet.

The workaround is to install an older version of tslint, e.g. 3.15.1, see also https://github.com/Microsoft/vscode-tslint/issues/131

**Comment by Z3roCoder** [comment]
Aah, I understand. I shall downgrade for the time beeing then.
Thanks 👍

**Comment by egamma** [comment]
OK - then closing the issue
