### ISSUE TITLE
Auto fix light bulb not appearing for the ' should be " rule.

### ISSUE THREAD

**Issue by DaveEmmerson** [Microsoft/vscode-tslint#144]
This worked until very recently, perhaps until the last update.

The green underline appears still when ' are used instead of ", but the auto fix light bulb no longer appears.

The light bulb appears for other rules, such as the "don't use var" one.

tslint 4.0.1 installed locally
vscode 1.7.2
tslint 0.6.7 installed (reinstalled too)

Replicated on a colleague's machine too.

**Comment by egamma** [comment]
This quick fix was a custom VS Code provided quick fix that got deprecated. Now, that the extension fully supports tslint provided quick fixes we no longer want to maintain such custom quick fixes. 

I should have mentioned this in the release notes. TI'll update the release notes. 

I'll make PR against tslint to provide this quick fix. The tslint API for fixes is straightforward and having the quick fixes in tslint and not vscode is the right thing.

**Comment by DaveEmmerson** [comment]
Spot on, thanks for the quick response.

**Comment by egamma** [comment]
Several users are complaining... So I'll revived the VS Code provided fix for this rule and I'll make a PR against tslint.  (FYI @rlasjunies)

**Comment by egamma** [comment]
fixed by f9bed75ef66bd1ec9aea0ee4c85ed5a10258b010
