### ISSUE TITLE
Quickfix for whitespace rules no longer available

### ISSUE THREAD

**Issue by realityfilter** [Microsoft/vscode-tslint#145]
Maybe this is related to #144. But the quick fix to whitespace related problems is still not available and quite a show stopper. Thanks for the support.

**Comment by egamma** [comment]
@realityfilter yes this is related to #144. I've revived the infrastructure to provide VS Code provide quickfixes and I can add more. For which whitespace related rules are you missing quick fixes?

**Comment by egamma** [comment]
I've revived more rules in 0.7.1.

**Comment by realityfilter** [comment]
Thank you very much for this quick fix.
