### ISSUE TITLE
vscode-tslint: no quick-fix for "ordered-imports" rule

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-tslint#148]
_From @weinand on December 6, 2016 15:47_

While testing #16519:

Enabling "ordered-imports" did result in some warnings in my test project but no quick fix lightbulb was showing up.

Since "ordered-imports" is listed on https://palantir.github.io/tslint/2016/11/17/new-for-4.0.html as having a fixer, it is not clear whether there is a problem with the corresponding quick fix in VS Code.

_Copied from original issue: Microsoft/vscode#16676_

**Comment by egamma** [comment]
@weinand I cannot reproduce this one, please see the attached video

![ordered-import](https://cloud.githubusercontent.com/assets/172399/21030192/8d27356e-bd9d-11e6-9dd0-b0e40a6fc359.gif)

**Comment by janpieterz** [comment]
I actually encountered this too, in two files exactly the same (well, different names but the same wrong order and the same amount of imports from similar locations) it didn't work either. Given that they were exactly alike I didn't figure out what the difference could be.

**Comment by egamma** [comment]
@janpieterz the next this happens can you try to auto fix the ordered-import rule warning from the command line using `tslint --fix`. This will help to narrow down whether the error is on the side of tslint or the side of the vscode-tslint extension.

Also when this happens can you open the tslint output channel and check whether there is an error message. To open the output channel you can click on the `tslint` status bar item, that shows up for `.ts` files.

**Comment by egamma** [comment]
I can reproduce cases when no fixes are available for the ordered-imports rule. 

```ts
import { c, b } from 'c';  // tslint#problem.Fix() returns an empty/zero length replacements array
import { a } from 'b';    // tslint#problem.Fix() returns a replacement array that replaces the entire group and fixes the import on the line above
```

tslint.json
```json
{
	"rules": {
		"ordered-imports": [
			true
		]
	}
}
```

Changed the code to handle the empty array more gracefully and not offer a fix when the replacements array is empty. The result is still slightly confusing to the user. The user has to pick the last light bulb, but this is a tslint behaviour. Interestingly this is not an issue when the fixes are applied from the command line using `--fix`, in this case it doesn't matter which fix is applied.

**Comment by janpieterz** [comment]
Sweet, thank you. I noticed indeed that after turning on the auto-fixing, or running it through a keyboard shortcut, it did fix them without any. Thanks for your follow-through egamma, much appreciated!
