### ISSUE TITLE
Extension should provide options to disable TSLint of JS files

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-tslint#149]
With the latest changes TSLint now automatically activates on JS files. If users want to use ESLint for JS file and TSLint for TS files in the same workspace we should allow users to disabled TSLint on JS files.

**Comment by Ventajou** [comment]
Isn't the option already there?

    "tslint.exclude": ["**/*.js"]

**Comment by egamma** [comment]
@Ventajou using a glob pattern allows to exclude .js files from linting today. However, users where confused/complained that `tslint` shows up in the status bar when they edit a .js file. With an explicit option we can fully disable tslint related UI when editing .js files.
