### ISSUE TITLE
Error shown in wrong file when using rules that lints external html templates

### ISSUE THREAD

**Issue by Ristaaf** [Microsoft/vscode-tslint#153]
I am using codelyzer rules for tslint with a rule that actually lints html files (templates referenced in a ts file). The resulting lint-result could look like this:

$ tslint card.component.ts
card.component.html[6, 269]: You can bind only to public class members.

however in vscode the green squigglies is actually placed in the card.component.ts file since that was the file being linted

I understand that it might be impossible for the vscode-tslint plugin to show the squigglies in another file than the one being linted, but I think it should not show them in the ts file if the result file is another than the one being linted.

**Comment by Ristaaf** [comment]
Steps to reproduce (using angular cli to get a quick angular and codelyzer installation in place):

npm i -g angular-cli
ng new TESTING
cd TESTING
ng generate component test

open TESTING folder in vscode, make sure tslint extension is installed

open the file src/app/app.component.html change the file to:
<app-test [variable]="title"></app-test>

open the file src/app.component.ts
Change line 9 (title='app works!') to
private title = 'app works!';

You will now see squiglies in the import statement in the app.component.ts file even though that error actually belongs to the app.component.html file.

**Comment by egamma** [comment]
@Ristaaf interesting scenario and thanks for the steps to reproduce. 

The extension can create a diagnostic for another file and the `tslint.RuleFailure` provides the source file information. However, one issue is that the HTML file itself is not synched into the linter server process. This means the linter rule will only check the saved file on disk and not the state that is in memory. 

So this can be broken down into:
- [bug] don't show diagnostics for the html file inside the .ts file (this issue)
- [enhancement] support that a linter can lint html files. (this should be a separate new issue.

**Comment by egamma** [comment]
Published in vscode-tslint 0.8.1
