### ISSUE TITLE
Option to report lint issues as errors & not issues

### ISSUE THREAD

**Issue by nevir** [Microsoft/vscode-tslint#155]
The green squigglies are pretty easy to miss - it'd be nice if we had an option to report lint issues as errors so we get red squigglies instead

**Comment by egamma** [comment]
@nevir this makes sense to me. There already is a feature request for this in tslint: palantir/tslint#345 and tslint is the better place for such an option.

**Comment by nevir** [comment]
Hmm, what signal does VS Code use to determine whether to display green
underlines vs red underlines?

**Comment by egamma** [comment]
@nevir VS Code receives the rule-failures from tslint through the tslint API. The tslint provided rule failures have no `severity` attribute and currently vscode-tslint creates tslint diagnostics as vscode warnings.

It would be straightforward to implement a setting to enable the user to configure whether a tslint rule failure should be an error or a warning,  but doing this in vscode-tslint is the wrong location, this should be done in tslint and be part of the rule configuration see also https://github.com/palantir/tslint/pull/1738.

**Comment by nevir** [comment]
Gotcha, thanks!

**Comment by tdsmithATabc** [comment]
I actually came here asking the opposite, so FYI to any future people: TSLint allows you to configure per-rule `severity` as well as global `defaultSeverity`. It defaults to `error` but changing it to `warn` will restore the (green) issue-style highlighting.

**Comment by egamma** [comment]
@tdsmithATabc I think this issue was filed before tslint support to configure rule severities. Since it is now supported by tslint all is good now, correct?

**Comment by tdsmithATabc** [comment]
Yep! I just wanted to document what I learned in case anyone else read this issue. 👍
