### ISSUE TITLE
Exclude option doesn't work

### ISSUE THREAD

**Issue by msudgh** [Microsoft/vscode-tslint#157]
Hello, I'm trying to exclude some TypeScript file from linting but it doesn't work.
See below screenshot:
![image](https://cloud.githubusercontent.com/assets/11756815/21508474/90a3617e-cc96-11e6-8e60-b8023ec53a06.png)

**Comment by egamma** [comment]
@msudgh these errors do not come from `tslint` but from the TypeScript language service (they have the prefix `[ts]`). You will get the same errors when you compile this code using the `tsc` compiler. Therefore the `tslint:disable` has not effect and this is the correct behavior.

You need install the typings for the test modules you are using.
