### ISSUE TITLE
JS Files not linted although jsEnable set to true

### ISSUE THREAD

**Issue by jschlieber** [Microsoft/vscode-tslint#159]
In my mixed project setup with `.ts` as well as `.js` files the latter aren't linted although I've set:
```javascript
{
  ...
  "tslint.jsEnable": true
  ...
}
```
in my workspace `settings.json`.

VS Code: 1.8.1
TSLint: 0.8.1

**Comment by egamma** [comment]
@jschlieber how does you `tlint.json` look. Does it have a section for `jsRules`, see below

```json
{
    "rules": {
    },
    "jsRules": {
        "triple-equals": [
            true,
            "allow-null-check"
        ]
    }
}

**Comment by jschlieber** [comment]
@egamma ahh, no I don't have a section for `jsRules`. In your example it looks like I have to duplicate the rules for `.js` files. That just doesn't feel DRY enough for me ;). Obviously TypeScript specific rules can't be applied to `.js` files, but wouldn't it be nice if rules that can be applied to JavaScript are automatically applied and `jsRules` only provides an option to override?

Anyway, thanks for your help.

**Comment by egamma** [comment]
@jschlieber 

>Obviously TypeScript specific rules can't be applied to .js files, but wouldn't it be nice if rules that can be applied to JavaScript are automatically applied and jsRules only provides an option to override?

This would have to be addressed by tslint itself and I suggest to file this enhancement request against the tslint repository https://palantir.github.io/tslint. 

Closing this issue.
