### ISSUE TITLE
Only watches `tslint.json` even if `tslint.configFile` is set to something different.

### ISSUE THREAD

**Issue by david-driscoll** [Microsoft/vscode-tslint#16]
Was just browsing thing and noticed that, while there is a configuration for `tslint.configFile`, `tslint.json` is the only file that will be watched.

https://github.com/Microsoft/vscode-tslint/blob/master/tslint/extension.ts#L20

**Comment by egamma** [comment]
Problem confirmed. There are two issues:
- can only watch files inside the workspace
- the file configured for watching doesn't honor the `tslint.configFile` setting.
The work around is to run the 'Reload Window' command for now.
I'll document the limitation in the README.
