### ISSUE TITLE
Documentation Enhancement Request: settings.json tslint.configFile

### ISSUE THREAD

**Issue by mudrz** [Microsoft/vscode-tslint#169]
#### Reason: there are no examples and recipes for common configurations

Example - standard TS/MVC project with multiple libraries

> folder structure

```
root
    --.vscode
        --settings.json
    --src
        --...(multiple C# and other libraries)
        --MvcProject
           --node_modules
           --tslint.json
           --package.json
    --test
```

For tslint to work locally instead of requiring a global installation, the following settings are required 

> .vscode/settings.json

```js
{
  "tslint.configFile" : "src/MvcProject/tslint.json",
  // AND nodePath, so that TSLint knows where to pick modules from
  "tslint.nodePath": "src/MvcProject/node_modules"
}
```

> src/MvcProject/package.json

```js
{
   //...
   devDependencies:{
    "tslint": "^4.4.2",
    "typescript": "^2.2.1"
   }
}
```

> src/MvcProject/tslint.json

```js
{
    "extends": [
        "tslint:recommended"
    ],
    "rules": {
    }
}
```

**Comment by mudrz** [comment]
Closing this since it is not an issue, but keeping it for reference to others, if they find it helpful

**Comment by egamma** [comment]
@mudrz thanks for writing this up. 

We could add this document to the vscode-tslint wiki https://github.com/microsoft/vscode-tslint/wiki. You can fork this repo and may be make a PR?

**Comment by mudrz** [comment]
@egamma sure, just added a page to the wiki

**Comment by egamma** [comment]
Great, thanks!
