### ISSUE TITLE
Failed to load TSLINT when tslint and typescript is installed globally 

### ISSUE THREAD

**Issue by CamelKing** [Microsoft/vscode-tslint#172]
I wonder what causes this problem, and I really prefer to have it installed globally rather than on every project.

**Comment by egamma** [comment]
@CamelKing having tslint and typescript installed globally should work. What doesn't work if you mix a global with local install. 

Can you describe your setup?

**Comment by CamelKing** [comment]
My bad, it was a mixed up. I am going all global now. Thanks.
