### ISSUE TITLE
nodePath option not working

### ISSUE THREAD

**Issue by maxdeviant** [Microsoft/vscode-tslint#173]
The `tslint.nodePath` option does not appear to be working.

We have a local package that contains our tslint package and configuration (for sharing across projects). I am trying to get VSCode to use that version of tslint when running the TSLint extension.

I have the following in our workspace settings:

```json
// settings.json
{
  "tslint.nodePath": "./node_modules/@remark/typescript/node_modules"
}
```

VSCode complains that it can't find the TSLint library:

```
[Info  - 10:23:17 AM] Failed to load the TSLint library.
To use TSLint in this workspace please install tslint using 'npm install tslint' or globally using 'npm install -g tslint'.
You need to reopen the workspace after installing tslint.
```

When I turn on the `"tslint.trace.server": "verbose"` option, I see this:

```
[Trace - 10:24:16 AM] Sending request 'initialize - (0)'.
Params: {
    "processId": 11092,
    "rootPath": "c:\\Projects\\CloudTestGrading",
    "capabilities": {},
    "initializationOptions": {
        "nodePath": "./node_modules/@remark/typescript/node_modules"
    },
    "trace": "verbose"
}


[Trace - 10:24:16 AM] NODE_PATH value is: c:\Projects\CloudTestGrading\node_modules\@remark\typescript\node_modules
[Trace - 10:24:17 AM] 'npm config get prefix' value is: C:\Program Files\nodejs
[Trace - 10:24:17 AM] NODE_PATH value is: C:\Program Files\nodejs\node_modules
[Trace - 10:24:18 AM] Received response 'initialize - (0)' in 1766ms. Request failed: Failed to load tslint library. Please install tslint in your workspace
folder using 'npm install tslint' or 'npm install -g tslint' and then press Retry. (99).
Error data: {
    "retry": true
}


[Info  - 10:24:18 AM] Failed to load the TSLint library.
To use TSLint in this workspace please install tslint using 'npm install tslint' or globally using 'npm install -g tslint'.
You need to reopen the workspace after installing tslint.
[Trace - 10:24:18 AM] Sending request 'shutdown - (1)'.
[Trace - 10:24:18 AM] Received response 'shutdown - (1)' in 1ms.
No result returned.


[Trace - 10:24:18 AM] Sending notification 'exit'.
No parameters provided.
```

I believe this might be a bug in [vscode-languageserver-node](https://github.com/Microsoft/vscode-languageserver-node).

##### Environment Info:
**OS:** Windows 7
**Node:** v7.7.1
**VSCode:** v1.10.1
**vscode-tslint:** v0.8.1

**Comment by maxdeviant** [comment]
This has been fixed in `vscode-languageserver-node`, so we will need to update to v3.2.0, once it is released.

**Comment by egamma** [comment]
@maxdeviant thanks for the info.

@dbaeumer can you please ping when you update the vscode-languageserver-node module.

**Comment by egamma** [comment]
Adopted 3.2.0 of the vscode-languageserver-node and published a new version of the extension.

**Comment by maxdeviant** [comment]
@egamma I updated to `vscode-tslint` v0.11.0 but am still seeing the same issue.

I noticed that the version of the `vscode-languageserver-node` that the extension is using is [`^3.0.2-beta.3`](https://github.com/Microsoft/vscode-tslint/blob/master/tslint/package.json#L168).

According to the info in the other issue thread, the fix is in `v3.2.0` of `vscode-languageserver-node`.

**Comment by egamma** [comment]
@maxdeviant just verified the bundle node module is `v3.2.0`.

```
npm ls -depth 0
tslint-server@0.2.0 C:\Users\egamma\Projects\vscode-tslint\tslint-server
+-- @types/minimatch@2.0.29
+-- @types/node@6.0.51
+-- @types/semver@5.3.30
+-- minimatch@3.0.3
+-- semver@5.3.0
+-- tslint@5.0.0
+-- typescript@2.1.4
`-- vscode-languageserver@3.2.0
```

**Comment by maxdeviant** [comment]
@egamma Following up on this:

After taking another look I was able to get it working. The issue was that the `nodePath` I was providing was not a parent of the resolved module path. Switching to a path that was a parent fixed the issue.

**Comment by egamma** [comment]
@maxdeviant thans for letting me know!
