### ISSUE TITLE
Question: Is there a way to report TSLint rules violations as errors?

### ISSUE THREAD

**Issue by tugberkugurlu** [Microsoft/vscode-tslint#175]
I am looking for a switch within this extension to report TSLint rule violations as errors. Is that possible?

**Comment by egamma** [comment]
Duplicate of #155 which has been closed, please see the discussion in this issue.

**Comment by tugberkugurlu** [comment]
@egamma thanks! Seems like this made it into a pre-release version now: https://github.com/palantir/tslint/pull/1738#issuecomment-285698572 Can it work with VS Code extension automatically now when I work with that version of TSLint does it need a further work here to hook that in?

**Comment by egamma** [comment]
@tugberkugurlu thanks for the notification. This requires some small adoption work. I've created #177 for it.
