### ISSUE TITLE
Feature Request: Configuration to use the tslint module installed locally or globally 

### ISSUE THREAD

**Issue by Emeryao** [Microsoft/vscode-tslint#176]
Hi there,
Here is the scenario: I have a `tslint.json` which based on the latest version(v4.5.1) of the `tslint` module, and I've install the latest version of `tslint` globally, but in my working folder, there's a node module depends on an older version of `tslint`, so the tslint extension uses the `tslint` module locally under the `working-folder/node_modules` instead of the globally one, which result in a lot of errors for the extension cause my `tslint.json` config file is base on the latest version of `tslint`.
So, I think there should be a configuration to let the user choose which `tslint` module is preferred(similar to the configuration of `typescript.tsdk` in vs code), and I think the configuration maybe something like `tslint.preferGlobal:true/false`.

Thanks.
Awesome Extension 👍

**Comment by egamma** [comment]
@Emeryao as a work around did you try to use the `tslint.nodePath` setting and have it point to the global or local version?

**Comment by Emeryao** [comment]
Hi @egamma
I tried change the `tslint.nodePath` setting aftering seeing your comment.
I changed the `tslint.nodePath` to `C:\\Users\\Emeryao\\AppData\\Roaming\npm\\node_modules` on my windows10 PC as I want the extension to pick the global module with referring this [example](https://github.com/Microsoft/vscode-tslint/wiki/Common-configuration-examples)
I tried both the user setting and the workspace setting but the `tslint:error` for the TSLint version is still there.
Did I set the `tslint.nodePath` with a correct value?

Sorry for my poor English 😄

**Comment by egamma** [comment]
@Emeryao sorry for the delay. `tslint.nodePath` should point to the folder that contains the `node_modules` so it should be `C:\\Users\\Emeryao\\AppData\\Roaming\npm\\`.

Here is another example, tslint installed into `C:\tmp\node_modules`. Then the `nodePath` setting should be `"tslint.nodePath": "c:\\tmp"`

**Comment by Emeryao** [comment]
Thanks @egamma 👍 
I will have another try

**Comment by Emeryao** [comment]
@egamma 
It's working by setting `tslint.nodePath` to `C:\\Users\\Emeryao\\AppData\\Roaming\\npm\\` 👍 
So, is the example [here](https://github.com/Microsoft/vscode-tslint/wiki/Common-configuration-examples) a correct one?
![image](https://cloud.githubusercontent.com/assets/3591899/25782546/b6bec740-337f-11e7-8f8d-7cd0dd7e8882.png)
