### ISSUE TITLE
The tslint installed by yarn globally does not work.

### ISSUE THREAD

**Issue by lijunle** [Microsoft/vscode-tslint#178]
It is a MUST to install tslint from npm. However, I want to use yarn to install npm packages globally.

**Comment by lijunle** [comment]
Looks like this is a vscode-languageserver-node issue: https://github.com/Microsoft/vscode-languageserver-node/blob/ddf508c65e917066c0d699b2baab11544de4d68a/server/src/files.ts#L257

**Comment by ivankashtanov** [comment]
@lijunle
You can use `tslint.nodePath` in user settings as a workaround, e.g.
```
{
    ...
    "tslint.nodePath": "/home/myuser/.config/yarn/global/node_modules"
}
```

**Comment by egamma** [comment]
The underlying issue is discussed here Microsoft/vscode-eslint#187

**Comment by zheeeng** [comment]
I'm having the same issue, hope a fix-upgrade.

**Comment by egamma** [comment]
This is currently blocked by yarn and the following enhancement request yarnpkg/yarn#2652.

**Comment by egamma** [comment]
This has been unblocked and is now provided by eslint https://github.com/Microsoft/vscode-eslint/commit/d5f53a539c531be45c2b3155907d02440c679fa0.

**Comment by lijunle** [comment]
Hi, @egamma

Is this resolved end-to-end? I still saw this error message with newest VSCode:

```
Failed to load the TSLint library for the document c:\Users\myName\myTypeScriptFile.ts

To use TSLint in this workspace please install tslint using 'npm install tslint' or globally using 'npm install -g tslint'.
TSLint has a peer dependency on `typescript`, make sure that `typescript` is installed as well.
You need to reopen the workspace after installing tslint.
```

**Comment by egamma** [comment]
@lijunle When you want to use yarn you have to set `tslint.packageManager` to `yarn`. The default is npm.

**Comment by lijunle** [comment]
@egamma I see. That is working! Thank you!

**Comment by lijunle** [comment]
It could be better to mention this in README.

**Comment by egamma** [comment]
Just checked, it is actually documented in the README and the Changelog.

**Comment by lijunle** [comment]
Hmm... It is interesting that, there are two README files:

- Under root folder: [/README.md](https://github.com/Microsoft/vscode-tslint/blob/master/README.md)
- Under `tslint` folder: [/tslint/README.md](https://github.com/Microsoft/vscode-tslint/blob/master/tslint/README.md)

I am looking on the root folder one, but the one is `tslint` folder has more information.

**Comment by egamma** [comment]
The one in the root folder describes the development setup, the one in the tslint folder is about the extension that is shipped out of this development setup. The one in the tslint folder is the contents that is shown in the market place https://marketplace.visualstudio.com/items?itemName=eg2.tslint and in the extensions viewlet.

I'll add a link from the root folder to the one in the tslint folder. This should address the potential confusion.

**Comment by lijunle** [comment]
Thank you! That is awesome!
