### ISSUE TITLE
Auto fix on save stops working until reloading VS Code

### ISSUE THREAD

**Issue by woutderooms** [Microsoft/vscode-tslint#183]
Tslint usually does a very nice job at fixing my tslint errors when saving files, but after a while (haven't figured out what triggers it) it stops fixing lint errors when saving.

I then have to proceed to disabled the plugin, reload, enable the plugin, reload, and then it is fixed.

EDIT: It does seem this always happens when there is an unused import in the file which I try to save.

UPDATE: If I don't fix the unused import before disabling and reenabling the plugin, it keeps not working. If I fix the unused import first, and then proceed to disable and enable the plugin, it works again.

platform: Mac OSX Sierra

**Comment by egamma** [comment]
@woutderooms Could it be that you run into the limitation that auto fixing cannot handle overlapping fix ranges as described in issue #164. 

When this happens again could you attach the file that is causing the issue together with your tslint.json file

**Comment by woutderooms** [comment]
I think it is indeed related to overlapping fix ranges.

```
import { b, a } from './myFile.ts';

console.log(b);
```

In combination with tsconfig.json: 

```
...
"no-unused-variable": true,
"ordered-imports": [true, {"import-sources-order": "any", "named-imports-order": "case-insensitive"}]
...
```

The fixing completely stops for all files until I remove `a` from the import and restart vscode.

**Comment by egamma** [comment]
@woutderooms 👍 I can repro now with https://github.com/Microsoft/vscode-tslint/tree/master/tslint-tests

**Comment by egamma** [comment]
Fix will be in the next update.
