### ISSUE TITLE
what to setup if my tslint.config is in subfolder

### ISSUE THREAD

**Issue by evollu** [Microsoft/vscode-tslint#184]
I've search for a while but can't get it work.
My tslint.config lives in /client subfolder in my repo. Is it possible to change `tslint.configFile` to make this plugin to load config from there?

**Comment by egamma** [comment]
By tslint.config you mean the `tslint.json` file? You should be able to use the `tslint.configFile` setting to define that the config is loaded from there. Have you tried this and it didn't work?

**Comment by evollu** [comment]
I tried to set it to `./client/tslint.json` but not working

**Comment by OliPro007** [comment]
AFAIK, you have to put an absolute path for the tslint.configFile setting.

**Comment by evollu** [comment]
I tried `"tslint.configFile": "/Users/LLu/Code/Patient/client/tsconfig.json"` but still no luck.

**Comment by evollu** [comment]
BTW my node_modules folder is in /client folder as well. Does it make sense to introduce a `root` option to set the root folder? @egamma

**Comment by egamma** [comment]
I cannot reproduce this and you do not need an absolute path to the config file. I'm using the workspace settings to define the location of the config file.

Here is my setup. What is the difference to your setup?
![image](https://cloud.githubusercontent.com/assets/172399/24646546/b4493860-191c-11e7-82c1-86a1f1a79501.png)

**Comment by OliPro007** [comment]
@evollu Indeed, if your `node_modules` folder is inside `client/`, you need to set the `tslint.nodePath` to `/whatever/path/client/node_modules`. 

As for the path, @egamma is right, you can simply use `client/tslint.json` and `client/node_modules`. It didn't work when I first made my configs for some reasons.

**Comment by evollu** [comment]
it works. Thanks @OliPro007 @egamma 
now I have another issue, `The 'no-use-before-declare' rule requires type checking`.
how can I pass `--type-check` into the plugin?

**Comment by evollu** [comment]
looks like there is another issue opened for this. closing this.

**Comment by lekhnath** [comment]
I've exact same directory structure as @evollu mentioned and following settings in `.vscode/settings.json` worked for me, thanks to @OliPro007 

```json
{
"tslint.enable": true,
"tslint.configFile": "client/tslint.json",
"tslint.nodePath": "client/node_modules"
}
```
