### ISSUE TITLE
tslint extension and tslint-loader use different root path to resolve rulesDirectory

### ISSUE THREAD

**Issue by oocx** [Microsoft/vscode-tslint#187]
I'm using webpack 2 with tslint-loader and VS Code with tslint extension 0.11.0. I have a tslint.json in config/tslint.json. 

In my VS Code workspace settings, I have this entry:
"tslint.configFile": "./config/tslint.json"    

My tslint.config contains the following rulesDirectory config:
"rulesDirectory": [
    "node_modules/codelyzer"
  ],

tslint-loader resolves the rulesDirectory setting relative to the project root folder. vscode-tslint resolves it relative to the tslint.config file (it tries to read ./config/node_modules/codelyzer).

That means tslint either works in my webpack build, or it works in VS Code. I can't get it to work in both environments.

I already tried to also configure the rulesDirectory in my workspace settings, but that did not fix the problem.

**Comment by egamma** [comment]
@oocx the rules directory resolution is done inside tslint, The extension passes the setting for the rules directory on the command line to tslint. So I suspect you get the same behaviour when you run tslint on the command line. I would have expected that the command line setting for the rules directory wins over the setting defined in the tslint.json. Not clear yet, what the extension can do to help here.

One idea would be to not define the rules directory inside the tslint.json, but to define in the workspace settings for vscode, and in some place in webpack (don't know if this is possible).

**Comment by egamma** [comment]
@oocx ping, could you solve this issue?

**Comment by egamma** [comment]
@oocx closing for now, please reopen if there are additional insight.
