### ISSUE TITLE
vscode-tslint: Unexpected token }

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-tslint#19]
I was editing the tslint.json file and suddenly got the following error:

![image](https://cloud.githubusercontent.com/assets/900690/11783518/0c0d844c-a278-11e5-81b8-9e45abccdc8e.png)

**Comment by bpasero** [comment]
Maybe auto save kicked in with the invalid JSON.

**Comment by egamma** [comment]
Yes, the error message is from ts-lint when the tslint.json JSON is not valid.

**Comment by bpasero** [comment]
Should be easy enough to try to JSON.parse() it before sending it to tslint

**Comment by egamma** [comment]
Now detecting config file errors and only show an info message when the tslint configuration has errors.
