### ISSUE TITLE
I'd like to be able to display tslint errors as warnings

### ISSUE THREAD

**Issue by testerez** [Microsoft/vscode-tslint#199]
Before tslint 5, the tslint issues where displayed as warnings in vscode, which made it easy to distinguish typescript and formatting errors. I'd like to keep it as it was...
I could change my tslint config so all rules are warnings but it's not easy to do when you inherit other configs and anyway I use tslint in my prepush hook so I want it to fail on errors.

What I suggest is a vscode configuration option to set the maximum error level used to notify tslint errors in vscode. Or maybe just a boolean: `tslint.displayErrorsAsWarnings: true`

Does it seem reasonable to you?

**Comment by garysoed** [comment]
seconded

**Comment by egamma** [comment]
The better solution would be when tslint makes it easier to configure that all rule failures are warnings, then it would work across all tools.

Having said this, this is straightforward to do, the hardest part will be to come up with the name of the setting 😃 .

**Comment by garysoed** [comment]
@egamma I don't think that's what we want. In the tslint cli, we want tslint to still consider lint errors as errors, not warnings. But in the IDE, we want the lint errors to show as warning.

I think the confusion here is what "error" means. To tslint, a lint error is an error severe enough to return code !== 0 when linting. To an IDE, an error is more severe; it usually means compilation error. The FR here is to provide a way to decouple tslint's error from IDE's error.

We can get around this using two tslint.jsons - one for the VSCode that treats errors as warnings, and one for the cli that treats errors as errors. (we can probably make this more manageable using the extend feature, but I haven't tried that). But this is painful to maintain, especially when we have custom severity for specific rules.

Hope that makes sense. Thanks for looking into this!

**Comment by egamma** [comment]
@garysoed the separation you describe makes sense.

**Comment by alexjlockwood** [comment]
Great to hear this was fixed.

Out of curiosity, will this be something that will require changing a setting or something like that in a future release? Or will the problem fix itself?

**Comment by egamma** [comment]
@alexjlockwood this is the setting that this now available in 0.14.0
`tslint.alwaysShowRuleFailuresAsWarnings` - always show rule failures as warnings, independent of the severity configuration in the tslint.json configuration.

**Comment by alexjlockwood** [comment]
@egamma great, thanks!

**Comment by wodge73** [comment]
Hi, where do we add the setting 

tslint.alwaysShowRuleFailuresAsWarnings 

please?

**Comment by egamma** [comment]
@wodge73 in the user or workspace settings, pls see https://code.visualstudio.com/docs/getstarted/settings
