### ISSUE TITLE
Option to specify rule configuration?

### ISSUE THREAD

**Issue by kwonoj** [Microsoft/vscode-tslint#2]
Maybe it's already in place and I'm just not aware - it'd be appreciate to let me know in that case.

Is there way to specify configuration file other than `tsling.json` via settings? it's equivalent to `tslint` option `-c`, allows to specify filename for rule configurations.

**Comment by egamma** [comment]
No this isn't supported yet. Currently you can only define the rulesDirectory and formatterDirectory in the settings file.

**Comment by egamma** [comment]
Added a configuration option 'configFile' pls see the README.md
