### ISSUE TITLE
Casing differences in React node modules causing tslint errors even though ignoring node_modules folder

### ISSUE THREAD

**Issue by devuxer** [Microsoft/vscode-tslint#200]
I'm getting a series of warnings for the react node module even though I have the following in my VSCode user settings:

    "tslint.jsEnable": false,
    "tslint.autoFixOnSave": true,
    "tslint.exclude": "**/node_modules/**"

Here is the first:

> WARNING in ./~/React/react.js
> There are multiple modules with names that only differ in casing.
> This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
> Use equal casing. Compare these module identifiers:
> * [path redacted]\node_modules\React\react.js
>     Used by 1 module(s), i. e.
>     [path redacted]\node_modules\awesome-typescript-loader\dist\entry.js![path redacted]\src\components\selected-nation-list\SelectedNationListItem.tsx
> * [path redacted]\node_modules\react\react.js
>     Used by 149 module(s), i. e.
>     [path redacted]\node_modules\awesome-typescript-loader\dist\entry.js![path redacted]\src\index.tsx

There are 24 more like this.

What can I do to suppress these warning?

**Comment by devuxer** [comment]
Problem seems to have been solved by deleting my node_modules folder and doing `npm update`, so I think this issue can be closed.

**Comment by egamma** [comment]
@devuxer thanks for the update, closing.
