### ISSUE TITLE
applyWithFunction is not a function

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode-tslint#205]
with tslint 5.2.0

```sh
[Info  - 6:57:53 PM] vscode-tslint: 'this.applyWithFunction is not a function' while validating: /Users/hwong/github/unional/global-store/src/index.ts stacktrace: TypeError: this.applyWithFunction is not a function
    at Rule.apply (/Users/hwong/github/unional/global-store/node_modules/tslint/lib/rules/noIrregularWhitespaceRule.js:27:21)
    at Linter.applyRule (/Users/hwong/github/unional/global-store/node_modules/tslint/lib/linter.js:143:33)
```

**Comment by egamma** [comment]
@unional this exception occurs inside a tslint rule
```
at Rule.apply (/Users/hwong/github/unional/global-store/node_modules/tslint/lib/rules/noIrregularWhitespaceRule.js:27:21)
```
why do you believe it is a vscode-tslint issue?

**Comment by unional** [comment]
Next exactly sure if it is tslint issue, but I don't see any warning/error when running it on cli.

I'm running `npm run lint` so using the same local version of `tslint`. Also tried `tslint src/**/*.ts` to use the global version (also 5.2.0).

**Comment by unional** [comment]
Repro at `global-store`

**Comment by egamma** [comment]
@unional I've tried to reproduce the exception using tslint 5.2.0 and the local version of typescript, but I did not succeed. Can you always reproduce it?

![image](https://cloud.githubusercontent.com/assets/172399/26076631/aa268514-39b9-11e7-9c26-5f016987ffb8.png)

**Comment by unional** [comment]
I can't repro it now either. Closing.
