### ISSUE TITLE
Add option to only lint on save

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-tslint#21]
Seeing the warnings while I'm still typing can be annoying.

**Comment by glen-84** [comment]
The `save` event has been implemented according to [this](https://github.com/Microsoft/vscode-languageserver-node/issues/19#issuecomment-212791014) comment.

**Comment by egamma** [comment]
@glen-84 correct and we will look into this. We want to have a consistent approach for this across all the linters and we will look best how to achieve this e.g., adding support in the vscode-language library.
