### ISSUE TITLE
Git operation fails on Windows when TSLint is enabled

### ISSUE THREAD

**Issue by vilic** [Microsoft/vscode-tslint#213]
Possibly related configurations:

```json
{
    "files.autoSave": "onFocusChange",
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,
    "tslint.autoFixOnSave": true
}
```

**Comment by wiegraff13** [comment]
I am seeing file lock issues with a different configuration. I am using:
``` json
{
    "tslint.enable": true,
    "tslint.configFile": ".vscode/tslint.json",
    "tslint.rulesDirectory": "node_modules/tslint-microsoft-contrib",
    "typescript.check.workspaceVersion": false
}
```
Using 0.15.0 of the plugin and seeing the issue occur in both VS Code 1.12.2 using TS Lint 2.3.2 and 1.13.0-insider using TS Lint 2.3.3.

Hope this helps.

**Comment by egamma** [comment]
@vilic can you please add some steps for how to reproduce the issue. What files are locked? What is your tslint.json.

**Comment by egamma** [comment]
@wiegraff13 When do you observer the file lock issue? What files are affected? Your issue could be different than the one from @vilic since you do not have `tslint.autoFixOnSave` enabled.

**Comment by vilic** [comment]
@egamma Seems that it's related to my rules configuration:

1. Create following files under dir `test`.

**test.ts**

```ts
let foo = 'bar';
foo;
```

**tslint.json**

```json
{
  "extends": [
    "vts"
  ]
}
```

2. Install `typescript`, `tslint` and `vts` globally (locally should work as well).

3. `git init && git add . && git commit -m "test"`.

4. Make some changes to `test.ts`.

5. Try `git reset --hard`.

```
error: unable to create file test.ts: Permission denied
fatal: Could not reset index file to revision 'HEAD'.
```

**Comment by vilic** [comment]
@egamma @wiegraff13 And autofix is not required to reproduce this error.

**Comment by wiegraff13** [comment]
@egamma 
Mine looks similar to @vilic reproduction steps above, though I am not using `vts`. Though, the suggestion that it is a rule config thing did get me to look through my rules to see if it down to any particular one, and I found that the problem only occurs when I have:

```
"rules": {
  "encoding": true
}
```

From my existing project:
1. Have the `encoding` rule on.
2. Make and edit to any `.ts` file.
3. From the SCM `Discard Changes` on the changed file.
4. I get an error message: `Git unable to create file test.ts: Permission denied`.
5. If I then restart VS Code or disable the plugin and reload, `git` has the change as deleting the file. I can safely discard the change though having reloaded.

**Comment by vilic** [comment]
@egamma It seems that this issue can also be reproduced with `tslint-language-service` plugin only without tslint extension. And the Git reset operation can also be replaced with simple `rm` and `touch` (`touch` would result in permission denied).

The problem seems to be that, the process keeps the file handle even after the file gets deleted.

![image](https://user-images.githubusercontent.com/970430/26960146-84425204-4d07-11e7-96fa-8dd32cbc7d5d.png)

![image](https://user-images.githubusercontent.com/970430/26960153-9658ee62-4d07-11e7-8287-4b543ffd36be.png)

**Comment by John-Diego** [comment]
I am having the same issue, when i modify an .ts file and run a git checkout with vscode open

**Comment by vilic** [comment]
Close as it seems to be fixed by https://github.com/palantir/tslint/pull/2958

**Comment by egamma** [comment]
@vilic thanks for connecting the dots.
