### ISSUE TITLE
Cannot install tslint

### ISSUE THREAD

**Issue by fangpenlin** [Microsoft/vscode-tslint#214]
Tried to install tslint vscode extension, but after tapping `Install` button, it immediately changes from `Installing` back to `Install`, as following screencast shown

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/201615/26702293/41b6d31c-46d9-11e7-864f-e005e5acdace.gif)

Version of VSCode: 1.12.2 (1.12.2)
OS: macOS 10.12.5 (16F73)

Please let me know where I can find a log file or what, so that I can provide you guys

**Comment by egamma** [comment]
@fangpenlin 
Do you see an exception in the Development Tools console (Help>Toggle Developer Tools)?

Do you have auto update of extensions enabled?

Does it help when you delete the extension manually from disk?
The extension is located in the ~/.vscode-insiders/extensions/eg2.tslint-0.15.0
