### ISSUE TITLE
I can't make tslint do anything.

### ISSUE THREAD

**Issue by rhedin** [Microsoft/vscode-tslint#218]
I've uninstalled it, reloaded the page, stopped and started VS Code. 

I'm using spaces inside braces as a test case.  import {Router}  vs  import { Router } . 

Whether I have tslint currently installed or not, I get no warnings when I remove the spaces.  Or when I save the file.  If I explicitly request a file reformat, the spaces are inserted. 

I suspect something else is doing that, not the tslint extension.

**Comment by rhedin** [comment]
Initially, I didn't change any settings, and this is our tslint.json file.  It is at the top level in our project.

{
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "rules": {
    "callable-types": true,
    "class-name": true,
    "comment-format": [
      true,
      "check-space"
    ],
    "curly": true,
    "eofline": true,
    "forin": true,
    "import-blacklist": [
      true,
      "rxjs"
    ],
    "import-spacing": true,
    "indent": [
      true,
      "spaces"
    ],
    "interface-over-type-literal": true,
    "label-position": true,
    "max-line-length": [
      true,
      140
    ],
    "member-access": false,
    "member-ordering": [
      true,
      "static-before-instance",
      "variables-before-functions"
    ],
    "no-arg": true,
    "no-bitwise": true,
    "no-console": [
      true,
      "debug",
      "info",
      "time",
      "timeEnd",
      "trace"
    ],
    "no-construct": true,
    "no-debugger": true,
    "no-empty": false,
    "no-empty-interface": true,
    "no-eval": true,
    "no-inferrable-types": [
      true,
      "ignore-params"
    ],
    "no-shadowed-variable": true,
    "no-string-literal": false,
    "no-string-throw": true,
    "no-switch-case-fall-through": true,
    "no-trailing-whitespace": true,
    "no-unused-expression": true,
    "no-use-before-declare": true,
    "no-var-keyword": true,
    "object-literal-sort-keys": false,
    "one-line": [
      true,
      "check-open-brace",
      "check-catch",
      "check-else",
      "check-whitespace"
    ],
    "prefer-const": true,
    "quotemark": [
      true,
      "single"
    ],
    "radix": true,
    "semicolon": [
      "always"
    ],
    "triple-equals": [
      true,
      "allow-null-check"
    ],
    "typedef-whitespace": [
      true,
      {
        "call-signature": "nospace",
        "index-signature": "nospace",
        "parameter": "nospace",
        "property-declaration": "nospace",
        "variable-declaration": "nospace"
      }
    ],
    "typeof-compare": true,
    "unified-signatures": true,
    "variable-name": false,
    "whitespace": [
      true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-separator",
      "check-type"
    ],
    "component-selector": [
      true,
      "element",
      "bmw",
      "BMW",
      "kebab-case"
    ],
    "use-input-property-decorator": true,
    "use-output-property-decorator": true,
    "use-host-property-decorator": true,
    "no-input-rename": true,
    "no-output-rename": true,
    "use-life-cycle-interface": true,
    "use-pipe-transform-interface": true,
    "component-class-suffix": true,
    "directive-class-suffix": true,
    "no-access-missing-member": true,
    "templates-use-public": true,
    "invoke-injectable": true
  }
}

**Comment by egamma** [comment]
@rhedin I cannot reproduce this.

Please make sure that you have:
- vscode-tslint installed
- tslint installed
- running tslint from the command line works.

If you have vscode-tslint installed then you will see tslint in the bottom right corner when a typescript file is open in the editor. Clicking it will show you the output from tslint which includes error messages.

**Comment by alextreppass** [comment]
I had this locally, had to disable (not uninstall) TSLint + reload, and then re-enable + reload, to get it working.

VS Code Version 1.15.1 (1.15.1)
TSLint for VS Code 0.17.0
TSLint 5.7.0 (installed globally)
TS 2.5.2

**Comment by rhedin** [comment]
Thanks, Alex.
