### ISSUE TITLE
Doesn't work with newest insider build?

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode-tslint#224]
It looks like this doesn't work in the newest insiders builds?

- Works: 1.13.1
- Doesn't work: 1.14.0-insider

In both cases the TSLint extension 0.15.0 is used in the same project.

My simple test:

```js
// with triple-equals rule
1 == 1;
```

**Comment by egamma** [comment]
I cannot reproduce this on the latest insiders using the latest version of tslint (see the screenshot below).

![image](https://user-images.githubusercontent.com/172399/27633406-55d860be-5bff-11e7-8d80-05f304502434.png)

![image](https://user-images.githubusercontent.com/172399/27633458-975cfe3c-5bff-11e7-8935-f5d7eb0e1068.png)

The test case can be found here:  https://github.com/Microsoft/vscode-tslint/tree/master/tslint-tests

**Comment by donaldpipowitch** [comment]
Strange. Thank you for the reply. I'll try re-installing the extension.

**Comment by donaldpipowitch** [comment]
Thank you for the help. It looks like re-installing the extension solved it for me. I'll think of that as an option for the next time.

**Comment by egamma** [comment]
@donaldpipowitch

Still strange, did you have to manually clean/remove the files from the extension as in https://github.com/Microsoft/vscode/issues/26615 (I was hoping we have fixed this issue)?

**Comment by donaldpipowitch** [comment]
No, I haven't cleaned up something manually. Just re-installing the extension. I had this issue for at least a week (maybe longer) and restarted VS Code Insiders multiple times (with updates).
