### ISSUE TITLE
Add exlude dir option

### ISSUE THREAD

**Issue by andrew-w-ross** [Microsoft/vscode-tslint#23]
Is it possible to add an exclude directory option? My d.ts files are essentially making my lint warnings meaningless.

**Comment by egamma** [comment]
Can you please elaborate more on the issue you have with the .d.ts files, what is an example when the lint warnings become meaningless.

**Comment by andrew-w-ross** [comment]
For example I am using the [highcharts.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/highcharts/highcharts.d.ts) definition and it doesn't abide by my rule set. I'll get 99+ warnings that won't go away unless I reload, hence they become meaningless. 

Overall I want to be able to ignore linting external type definition files, generally that would be the `typings` folder.

**Comment by egamma** [comment]
> I'll get 99+ warnings that won't go away unless I reload, hence they become meaningless.

To make the warnings go away you can close the corresponding .d.ts files from the list of working files in the explorer. 

However, I understand that you would prefer to net get these warnings when opening the .d.ts file.

**Comment by andrew-w-ross** [comment]
>To make the warnings go away you can close the corresponding .d.ts files from the list of working files in the explorer.

Thanks that's a workaround for now. If you were going to implement this would you look at the `tsconfig.json` exclude field?

**Comment by egamma** [comment]
> would you look at the  tsconfig.json  exclude field?
Haven't yet deeply thought about it, but would that really help, since the .d.ts files are typically not excluded but part of the scope of a TypeScript project?

I would prefer a solution in `tslint`, then it applies to all the tools that integrate with it. There is an open feature request for this palantir/tslint#73 which just got some recent activity.

**Comment by andrew-w-ross** [comment]
That would be the best solution but that ticket has been open for 2 years.

**Comment by egamma** [comment]
Yes it is open since 2 years, but discussion has started again https://github.com/palantir/tslint/issues/73#issuecomment-158705432

**Comment by zanettin** [comment]
+ 1 :(

**Comment by egamma** [comment]
Covered by PR #40. Closing.
