### ISSUE TITLE
Failed to load tslint library error on every folder that does not have a tslint.json

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-tslint#236]
1. Have a tslint extension installed
2. Open a folder without a tslint.json file
3. Notice an error in the developer console

This way tslint spams the developer console for most of my test workspaces. Could tslint fail a bit more gracefully in this case? I understand this is better than showing it to the user via message service but maybe use the tslint output channel (which you already have) for messages like this.

![screen shot 2017-07-27 at 15 27 19](https://user-images.githubusercontent.com/1926584/28672582-6536d7a0-72e0-11e7-8408-4f31430e4b15.png)

**Comment by egamma** [comment]
The loading failure is now reported in the status bar item and no longer in the dev console. Also the status bar item is only shown when tslint.enable is set to true.
