### ISSUE TITLE
member-ordering - Incorrect type. Expected "object"

### ISSUE THREAD

**Issue by comerc** [Microsoft/vscode-tslint#241]
VSCODE 1.15.1
EG2.TSLINT 0.17.0

![2017-08-19 11 48 18](https://user-images.githubusercontent.com/1025241/29485089-9255558a-84d4-11e7-8209-8109454912e9.png)

**Comment by CliveTeow** [comment]
I am also facing the same issue.

**Comment by cchene** [comment]
Problem is probably in the tslint.json, not in vscode-tslint: https://palantir.github.io/tslint/rules/member-ordering/

**Comment by egamma** [comment]
Closing as a duplicate of #192
