### ISSUE TITLE
TSLint output window panel every time js file is opened

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-tslint#242]
_From @smlombardi on August 23, 2017 15:53_

- VSCode Version: Code - Insiders 1.16.0-insider (1c6f2f9a8012565adcc50616c3aa90cb444e8797, 2017-08-23T05:10:58.701Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
code-settings-sync|Sha|2.8.3
sort-lines|Tyr|1.3.0
html-snippets|abu|0.1.0
Bookmarks|ale|0.15.2
project-manager|ale|0.19.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.4.2
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.1.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
stylelint|shi|0.28.0
ayu|tea|0.5.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. open a js file.  for example, an AngularJS route file.
2. the "output" panel pops open (empty) for no apparent reason.

_Copied from original issue: Microsoft/vscode#33036_

**Comment by egamma** [comment]
_From @Tyriar on August 23, 2017 18:6_

@dbaeumer might know more, please forward to the right person if not 😄

**Comment by egamma** [comment]
@smlombardi  I cannot reproduce this behaviour, when I open a .js with vscode-tslint installed. I'm using this setup https://github.com/Microsoft/vscode-tslint/tree/master/tslint-tests. 

- what is shown in the tslint output window?
- is anything shown in the developer console Help>Toggle Developer tools?
- what version of tslint are you using?

**Comment by smlombardi** [comment]
@egamma 

> what is shown in the tslint output window?
It's empty

> is anything shown in the developer console Help>Toggle Developer tools?
<img width="1056" alt="screen shot 2017-08-24 at 9 41 09 am" src="https://user-images.githubusercontent.com/835148/29669147-842bec82-88b0-11e7-91f0-9a72c7bac090.png">

> what version of tslint are you using?
tslint@5.6.0 

Looking at the error, I suppose tslint was not installed globally on this Mac — it's a new machine I got and I assumed everything was configured same as my old one, but I guess I forgot a couple of global npm installs.

**Comment by egamma** [comment]
This should not longer happen in vscode-tslint 1.0.1, please reopen if you can still reproduce this behaviour.
