### ISSUE TITLE
No default rules in newly created tslint.json file

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-tslint#246]
Testing https://github.com/Microsoft/vscode/issues/33287

- Run the command `TSlint: Create a 'tslint.json' file`
- Open the newly created tslint.json file

Previously, the newly created tslint.json file would have the below default rules
```
{
		"no-unused-expression": true,
		"no-duplicate-variable": true,
		"no-unused-variable": true,
		"curly": true,
		"class-name": true,
		"semicolon": ["always"],
		"triple-equals": true
}
```
Now there are no default rules.

Having the default rules would help new users in exploring options and understanding tslint

**Comment by egamma** [comment]
The current default rules were all hard coded and it was impossible to pick a set of sensible default rules. For this reason the implementation has changed to use the defaults that tslint also suggests when running `tslint --init`  and the implementation is now just calling `tslint --init`.
