### ISSUE TITLE
Multi-root: tslint.enable is not honored when Workspace settings exist

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-tslint#247]
Testing https://github.com/Microsoft/vscode/issues/33287

In a multi root set up 
- Set `tslint.enable` to `true` in one of the folder settings
- Set `tslint.enable` to `false` in Workspace settings

tslint is now disabled in all folders instead of being enabled in the folder where the setting was enabled

**Comment by egamma** [comment]
Can reproduce for tslint.enable, but the other settings are properly honored in the multi root setup.
