### ISSUE TITLE
Enable to setup quotemark as single in vscode

### ISSUE THREAD

**Issue by jimiatworking** [Microsoft/vscode-tslint#249]
Hi I love this extension, but I couldn't find that I could config in Settings to config quotemark to single. Does there any way I don't need to add file as tsling.json and just config in vscode-settings?

**Comment by egamma** [comment]
@jimiatworking you do not do this in the tslint,json. When you configure this in the settings then you will get different results when you run tslint from the command line and the goal is to get same results on the command line and in vscode.
