### ISSUE TITLE
Tslint config file parsing does not support comments

### ISSUE THREAD

**Issue by cicciodm** [Microsoft/vscode-tslint#25]
We currently have one single-line comment in out `tslint.json` config file.

After installing the plugin on VSC, I got the following error: 
`vscode-tslint: Cannot read tslint configuration - 'Unexpected token /'`

Removing the comment works as a temporary solution, but support for comments would be greatly appreciated.

**Comment by egamma** [comment]
@cicciodm this error message comes from tslint and I tought tslint expects a plain JSON file, without comments. In your set-up do you have a pre-processing step that removes the comments or do you know a way to tell tslint to tolerate comments?

**Comment by egamma** [comment]
I've checked the tslint source code and they just support plain JSON. I suggest to make a pull request against tslint to support comments by stripping out the comments before the parse the JSON. 

Closing this issue, since no work on this is planned on the side of vscode-tslint.
