### ISSUE TITLE
error during build: no exported member 'ProposedProtocol'

### ISSUE THREAD

**Issue by mike-kaufman** [Microsoft/vscode-tslint#256]
I'm sync'd up to master, and I see the following error during build of `tslint` extension:

```
extension.ts(7,2): error TS2305: 
Module '"/Users/mikekaufman/github/microsoft/vscode-tslint/tslint/node_modules/vscode-
languageclient/lib/main"' 
has no exported member 'ProposedProtocol'
```

I'm guessing you've got a dep on some language client changes that haven't been released yet?  Is there a changelist I can sync to that can get stuff working?

I'm trying to see if your vscode debug config works for this extension.  I'm trying to get the debug config for [vscode-htmlhint](https://github.com/Microsoft/vscode-htmlhint) to work, but I can't seem to attach to the server.

**Comment by egamma** [comment]
Make sure that you do an npm install to get the latest dependencies. The extension is using "vscode-languageclient": "^3.4.0" and this version is published in the market place, so it should also work for you.

**Comment by mike-kaufman** [comment]
re-installed node modules, same error.  I have 3.4.2 of vscode-languageclient installed:

```
$ pwd
/Users/mikekaufman/github/microsoft/vscode-tslint/tslint
$ npm ls vscode-languageclient
tslint@1.0.4 /Users/mikekaufman/github/microsoft/vscode-tslint/tslint
└── vscode-languageclient@3.4.2 
```

**Comment by egamma** [comment]
I see there was a breaking change between 3.4.1 and 3.4.2 with regard to using Proposed protocol. I've updated the code to 3.4.2 please check it out again.
