### ISSUE TITLE
tslint.configFile relative to workspace

### ISSUE THREAD

**Issue by StevenLiekens** [Microsoft/vscode-tslint#259]
I cannot get the extension to find my config file.

Error:
> vscode-tslint: Cannot read tslint configuration - 'Could not find config file at: `C:\Program Files\Microsoft VS Code\node_modules\@internal\linting\tslint.json`'

My workspace settings:

```json
{
    "tslint.configFile": "node_modules/@internal/linting/tslint.json"
}
```

Why on earth is it looking inside the VS Code directory instead of my workspace?

I have these NPM modules:

Global
1. tslint@5.7.0
2. typescript@2.5.2

Local
1. tslint@5.7.0
2. typescript@2.5.2

VSCode version 1.16.0
vscode-tslint version 1.0.5

**Comment by egamma** [comment]
Problems confirmed, the work around is to use an absolute path name when referring to the configFile. I'll look into a fix as soon as possible.

**Comment by StevenLiekens** [comment]
Thanks. It's good to know I'm not crazy.

**Comment by egamma** [comment]
@StevenLiekens just to give you the background. Since VS Code will support workspaces with multiple root folders, this extension also needs to support this. In the past the server process that does the linting and resolves the path to the configFile was launched in the folder of the single rooted workspace. Since we now support multiple root folders this no longer works, otherwise relative paths will only work for the first folder in a workspace.

**Comment by StevenLiekens** [comment]
Can the extension detect the workspace root of the current file? Can the path to the config file be resolved by combining the current root and a relative path?

**Comment by egamma** [comment]
@StevenLiekens yep this is is what I'll  implement.

**Comment by StevenLiekens** [comment]
Great! 😄

**Comment by egamma** [comment]
Fix published (version 1.0.7) to the market place.

**Comment by mttcr** [comment]
Don't we have the same problem with `tslint.rulesDirectory` ?
I have TSLint 1.0.7, and in the tslint console:
`[Info  - 10:57:17] vscode-tslint: 'Could not find custom rule directory: xxx' while validating: `

**Comment by egamma** [comment]
@mttcr good catch can you please file a separate issue on this.
Did you check whether this is also an issue when you define the rulesDirectory inside the `tslint.json`? The tslint doc states:

> rulesDirectory?: string | string[]: A path or array of paths to a directories of custom rules. This will always be treated as a relative or absolute path.

But it doesn't specify relative to what folder.
