### ISSUE TITLE
Disable tslint for .js

### ISSUE THREAD

**Issue by rshmiraf** [Microsoft/vscode-tslint#261]
Hi,
After new update i've got new warning. I don't use tslint in this project and I also don't have tsilint config there.

With this two line nothing happened:
```
"tslint.jsEnable": false,
"tslint.exclude": ["**/*.js"]
```

Error looks like this:
<img width="1267" alt="screen shot 2017-09-15 at 12 59 43" src="https://user-images.githubusercontent.com/14861637/30479512-ed831f9a-9a15-11e7-8af4-cb092340622a.png">

Is this my mistake somewhere? I know there is possibility to turn off tslint for workspace but this solution is dumb :P

**Comment by egamma** [comment]
A regression, fixed in 1.0.7, thanks for catching.

BTW, setting `"tslint.jsEnable": false` is sufficient to disable linting for .js files.
