### ISSUE TITLE
No-Typescript project report lint...

### ISSUE THREAD

**Issue by yoyo837** [Microsoft/vscode-tslint#262]
No-Typescript project, tslint report lint information from Other extensions directory.
![e3e8ba82-0ba9-4358-8a37-1e95711ce341](https://user-images.githubusercontent.com/6134547/30508946-0774da22-9ad6-11e7-819b-1c326385e36c.png)

My tslint version: 1.0.7
VSCode version: 1.16.1 
OS: Win 10 latest 64bit
The extension is [vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur)

**Comment by egamma** [comment]
@yoyo837 I cannot reproduce this given the above steps. TypeScript definition files are by default ignored. Did you change the setting `tslint.ignoreDefinitionFiles`.

Can you reproduce the problem and provide steps?

**Comment by yoyo837** [comment]
@egamma 
I have not change the setting `tslint.ignoreDefinitionFiles`. It’s the default. I can reproduce this problem, but not every time, but I'm sure I've met more than once. Give me some time, I'll find out some more information.

**Comment by egamma** [comment]
@yoyo837 when it happens that you see errors on another file:
- is it always with a TypeScript definition file .d.ts?
- how did you open the file that doesn't belong to your project?

**Comment by yoyo837** [comment]
Step:
In VSCode I use [vetur ](https://marketplace.visualstudio.com/items?itemName=octref.vetur)to support my vue syntax highlighting and so on
For example, I have two files here: 
`test.js`
```javascript
console.log(document)
console.log(window)
```
`test.vue`
```vue
<template>

</template>

<script>
export default {
  mounted() {
    console.log(document)
    console.log(window)
  }
}
</script>

<style>

</style>

```
1.In `test.js` hold down `Ctrl `and mouse hover over `document` or `window`, Intellisense work fine. Click it.
2.In `test.vue` hold down `Ctrl `and mouse hover over `document` or `window`.

Use the VPN to add screenshots later.

**Comment by yoyo837** [comment]
My God, I'm sorry that my VPN subscription has expired and cannot have renewed through in-app purchase because it has been removed by the app store. In my network environment, no use of VPN cannot upload screenshots.

Please forgive me for my complaints.

**Comment by egamma** [comment]
OK, but since you can reproduce it, can you please enable the setting "tslint.trace.server" and set it to "verbose" and reproduce the problem and attach the trace that is produced in the 'tslint' output channel (click on tslint in the status bar).

One more question do you ever see the file that has the errors open in an editor?

**Comment by yoyo837** [comment]
>One more question do you ever see the file that has the errors open in an editor?
If you just hold down the CTRL key and the mouse is over it, the file will not open, but the error has been reported at this point. If you hold down the CTRL key and click on the file will be opened, will report an error.

Tracking information big, more than 25k lines, how can i provide you more appropriate.

**Comment by yoyo837** [comment]
> is it always with a TypeScript definition file .d.ts?

Yes, and has always been the same file.
>how did you open the file that doesn't belong to your project?

Hold down the CTRL key and click js built-in object like `window`, if click it...

Tracking information I will send you by mail.

**Comment by egamma** [comment]
Great we are getting closer.

>Tracking information I will send you by mail.

You can also save the file and attach it to this issue by dragging the file into the comment box.

**Comment by yoyo837** [comment]
I'm sorry, Amazon AWS is very difficult to access in my network environment, screenshot pictures, files, etc. uploads always fail.
It has been sent to your mailbox in GitHub personal information.

**Comment by egamma** [comment]
Got the mail, thank you!

**Comment by egamma** [comment]
Interesting bug I have to tell the pattern matcher to not ignore hidden files... your path includes '.vscode'.
Thanks for helping me to track this down!
