### ISSUE TITLE
Autofix for import ignores "quotemark" rule

### ISSUE THREAD

**Issue by Leopotam** [Microsoft/vscode-tslint#265]
tslint.json:
```
"quotemark": [
            true,
            "single"
        ],
```
## Expected  behavior
```
import { IMessage } from './messages';
```
## Actual behavior
```
import { IMessage } from "./messages";
```
[Example video](https://youtu.be/QX3E4R3pqHM)

**Comment by egamma** [comment]
Same reason as in https://github.com/Microsoft/vscode-tslint/issues/266#issuecomment-330768310.

The good news is that in the latest version of TypeScript the auto fix honors the quotes of the existing imports.
