### ISSUE TITLE
Provide option to hide status bar item

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-tslint#268]
Currently, whenever a TS file is open, there's a TSLint status bar item down visible. It would be great if there's a setting to control it, since it seems to serve no purpose when things are working.

![image](https://user-images.githubusercontent.com/22350/30641719-6a6afdb6-9e08-11e7-85fd-c83cb475c235.png)

**Comment by egamma** [comment]
The status bar item opens the tslint output channel. This is something that you rarely do when things are working.
