### ISSUE TITLE
Ability to exclude *.d.ts files

### ISSUE THREAD

**Issue by use-strict** [Microsoft/vscode-tslint#27]
As an enhancement, it would be nice to be able to ignore *.d.ts files. I don't think tslint is supposed to work with them. For instance, it complains about internal modules, but that is exactly the point of the declaration file.

**Comment by egamma** [comment]
I prefer this over #23. It is not uncommon to open a d.ts file in VS Code to read an API and this can result in many errors from tslint. 

I suggest to add a setting ignoreDefinitionFiles that defaults to `true`.

**Comment by egamma** [comment]
Covered by PR #40, closing.
