### ISSUE TITLE
Different underline color for TypeScript errors in Linux system.

### ISSUE THREAD

**Issue by ArturGoldyn** [Microsoft/vscode-tslint#270]
On Windows system everything is fine, tslint underlines lint errors in green, and TypeScript compiler errors are red.
However, in Linux both category of errors shows the same red color. Can anything be done about that?
vscode version is 1.16.1

**Comment by egamma** [comment]
@ArturGoldyn  Here is how the colors/severities are handled:
- diagnostics from TypeScript (prefix [ts]) are always colored as an error
- diagnostics from tslint prefixed with [tslint] are configured as defined in tslint.json (by default rule failures are shown as errors).

vscode-tslint supports that you can overrule the tslint.json definition using the `tslint.alwaysShowRuleFailuresAsWarnings` setting.
