### ISSUE TITLE
JSON validation error reported against a markdown file

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-tslint#271]
I have no reproducable case yet, but I have seen this multiple time last week.

The symptoms are:
- there is an error in problems view related to JSON validation 
- the problem refers to a package.json file
- but the contents is from the CHANGELOG.md file.

![image](https://user-images.githubusercontent.com/172399/30822296-886c2df2-a228-11e7-98c0-ca30da4afee1.png)

**Comment by joaomoreno** [comment]
These are `git:` resources.

**Comment by egamma** [comment]
@joaomoreno sorry wanted to file against the vscode repo (I only have the phone wirh me, cannot move the issue easily).

>why is package.json having markdown inits contents

actually this is the contents of the changelog.md file in this repo. i've only seen it in this repo.

**Comment by egamma** [comment]
adding @aeschli could it be that the JSON validation doesn't handle git resources properly?

**Comment by egamma** [comment]
ran git fsck on the repo and I got several errors and a corrupt repository might have caused this.
