### ISSUE TITLE
tslint is ignoring my project's type definition files

### ISSUE THREAD

**Issue by mmmeff** [Microsoft/vscode-tslint#272]
The root of my project has a "types" directory that is being considered in my builds - without them, the project would not compile. However, vs code + tslint is still showing errors across my project as if the definitions were never loaded.

How can I ensure that my type definitions are included in my projects tslint configuration?

**Comment by egamma** [comment]
@mmmeff can you show an example of an error message you are seeing?

**Comment by egamma** [comment]
@mmmeff  This looks like a duplicate of #273. Please reopen if this is another issue.
