### ISSUE TITLE
insiders - tslint cannot find local modules

### ISSUE THREAD

**Issue by vrachels** [Microsoft/vscode-tslint#273]
occurs on 1.17.0-insider ; does not occur on 1.16.1
TSLint plugin 1.0.9
![err1](https://user-images.githubusercontent.com/22227063/30993755-452eacec-a465-11e7-9af3-52887407570d.jpg)

`[ts] cannot find module  '@soulborn/logger'`

Works correctly in vs code non-insiders.
Tried using sqs/TSLint (TEMP multiroot-compat), but gets the same issue.

`@soulborn/logger` is a locally developed package also in the workspace, using lerna for package linking management

**Comment by egamma** [comment]
@vrachels  please see below, the message is prefixed with `[ts]` and it therefore comes from the Typescript language service and not tslint. 

> [ts] cannot find module '@soulborn/logger'

Suggest to file the issue against the Typescript repository with a reproduceable setup.

**Comment by egamma** [comment]
@vrachels I can reproduce this in the insiders build with the insiders version of TS. This problem does not occur with TS version 2.4.3 or 2.5.3 so it has been fixed. The easiest fix is to use the TS version switcher in the status bar (bottom right) and to switch to the workspace version.
