### ISSUE TITLE
Failed to load tslint library

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-tslint#28]
_From @Olgagr on February 12, 2016 19:11_

When I open a project and then open any TypeScript file I see this alert at the top of editor:

"Failed to load tslint library. Please install tslint in your workspace folder using 'npm install tslint' or 'npm install -g tslint' and then press Retry."

I have tslint installed as npm package in my project, as well as global npm package. However, for some reason, editor can't find it.

My editor version is 0.10.8 and I'm on Mac.

_Copied from original issue: Microsoft/vscode#2979_

**Comment by egamma** [comment]
@dbaeumer I think you had a similar issue with es-lint, what was the root cause for this issue? I wonder whether it applies here as well.

**Comment by dbaeumer** [comment]
@egamma  The root case in eslint was a set NODE_PATH env variable. I fixed it in the language server code. If you take latest and republish the extension then you should be fine.

**Comment by nukuuk** [comment]
Was there a solution for this?  I just installed VS code on a new laptop, after installing this extension i get the error "Failed to load tslint library. Please install tslint in your workspace".  worked perfect on my old laptop

**Comment by Brieg** [comment]
+1

**Comment by andrew-w-ross** [comment]
+1 I'm also getting this error.
I'm on a mac and have it installed locally and globally.

**Comment by egamma** [comment]
@andrew-w-ross and @Brieg what version of vscode-tslint are you using?

**Comment by andrew-w-ross** [comment]
@egamma 
vscode 0.10.11
npm 3.8.2
node 5.10.1

**Comment by egamma** [comment]
@andrew-w-ross thanks what version of vscode-tslint. To see the version#:
- execute the 'Show Installed Extensions Command'
- the version can be found in the top right corner
![image](https://cloud.githubusercontent.com/assets/172399/14490116/24de334c-0171-11e6-8751-16bd29edd35c.png)

If you are not on the latest 0.5.22 can you upgrade and try again please

**Comment by andrew-w-ross** [comment]
@egamma Looks like I'm on the latest version

**Comment by egamma** [comment]
Thanks, then to have exactly the same setup when I repro, what version of tslint do have installed?

**Comment by andrew-w-ross** [comment]
3.7.4 but I also tried tslint@next as well.
And if it helps I'm using typescript 1.8.9.

**Comment by Brieg** [comment]
@egamma 

![tslintversion](https://cloud.githubusercontent.com/assets/7222268/14491734/f3504856-017a-11e6-9dc6-7b4bcb9eda5e.png)

![vscodeversion](https://cloud.githubusercontent.com/assets/7222268/14491770/1d4f6eb6-017b-11e6-952b-3670bd36b78b.png)

**Comment by egamma** [comment]
I cannot reproduce it:
- vscode-tslint - 0.5.22
- tslint - 3.7
- vscode - 1.0.0

It works both when I install tslint locally into the workspace and when I install tslint globally.

@Brieg @andrew-w-ross are you using nvm? Pls see this discussion https://github.com/Microsoft/vscode-eslint/issues/28#issuecomment-183013604

**Comment by andrew-w-ross** [comment]
@egamma Yes I am, looks like installing eslint globally stopped the error message but it's also no longer lints.

**Comment by willin** [comment]
+1

vscode 1.1 && 1.0

**Comment by egamma** [comment]
I've published 0.5.23. This version uses the latest vscode-language libs and some fixes went into them. @andrew-w-ross, @willin, @Brieg can you please try whether this situation improves things.

**Comment by willin** [comment]
Failed to load tslint library. Please install tslint in your workspace
![qq20160424-0 2x](https://cloud.githubusercontent.com/assets/1890238/14766512/d9ff20f2-0a3f-11e6-978d-de3c76a019f1.png)

**Comment by egamma** [comment]
@willin thanks for trying. Are you using nvm on OS X?

**Comment by willin** [comment]
@egamma yes

**Comment by bharathitman** [comment]
This error was resolved after I ran npm install -g tslint, instead of ext install tslint from vscode

**Comment by Meligy** [comment]
For me too the error was solved with `npm install -g tslint`.

I think the Atom equivalent has a setting to use bundled eslint or something like that. Not sure exactly.

A quick workaround (fix?) might be to mention the issue and solution in README.

Thanks a lot for the package :)

**Comment by andrew-w-ross** [comment]
@egamma Just updated to the new vs code and it's working again.

**Comment by reactivize** [comment]
What fixed it for me was adding tslint's dependency...

npm install -g tslint typescript

**Comment by egamma** [comment]
>A quick workaround (fix?) might be to mention the issue and solution in README.

@Meligy thanks, I've added the work around to the `README.md`,

**Comment by jgillich** [comment]
Had the same issue with a custom `NPM_CONFIG_PREFIX` & `PATH` set to my home directory in my `.zshrc`, turns out I had to also set it in `~/.profile` (since that one also applies to GUI apps started via GNOME).

**Comment by egamma** [comment]
Can you please try again in the latest version 0.5.39, the tslint module resolution has been improved in this version.

**Comment by MrKou47** [comment]
today i have the same question,
because i had install tslint but did't install typescript ..
when i install typescript it work great
