### ISSUE TITLE
Getting error while writing many to many relation in my entity model

### ISSUE THREAD

**Issue by vipswelt** [Microsoft/vscode-tslint#289]
I am creating an entity as below

    import { Entity, Column, PrimaryGeneratedColumn, ManyToMany } from 'typeorm';
    
    import { UserRoleEntity } from './user-roles.entity';
    
    @Entity('Users')
    export class UserEntity {
    
        @PrimaryGeneratedColumn()
        UserId: number;
    
        @Column()
        FirstName: string;
    
        @Column()
        LastName: string;
    
        @Column()
        MobileNo: string;
    
        @ManyToMany(userRole => UserRoleEntity, userRole =>userRole.userRoles)
        userRoles: UserRoleEntity[];
    }

when i am running my application getting an error as below

> [0]
[1] [0] ERROR in server/models/entities/user.entity.ts(44,17): error TS6133: 'type' is declared but its value is never read.
[1] [0]
> 
> ERROR in Error: TypeError: Cannot read property 'kind' of undefined
> [1] [0]     at nodeCanBeDecorated
> (D:\Projects\MEAN\finception\node_modules\typescript\lib\typescript.js:8344:36)
> [1] [0]     at nodeIsDecorated
> (D:\Projects\MEAN\finception\node_modules\typescript\lib\typescript.js:8364:16)
> [1] [0]     at Object.nodeOrChildIsDecorated
> (D:\Projects\MEAN\finception\node_modules\typescript\lib\typescript.js:8368:16)

how can i ignore this behavior?

**Comment by egamma** [comment]
@vipswelt these messages are from typescript and not from tslint, I'll therefore have to close this issue.

>[1] [0] ERROR in server/models/entities/user.entity.ts(44,17): error TS6133: 'type' is declared but its value is never read.

In your tsconfig.json you have enabled the noUnusedLocals compiler option.
