### ISSUE TITLE
C++ runtime library error

### ISSUE THREAD

**Issue by yoyo837** [Microsoft/vscode-tslint#290]
First of all, I'm sorry, I do not know who is the problem, tslint, vscode or typescript? The following error occurs when I save the ts file or when I execute tslint.

**Comment by yoyo837** [comment]
![33a3761e-0684-47b0-807c-a9878d6f9cad](https://user-images.githubusercontent.com/6134547/32607661-aa0c3e40-c594-11e7-9207-21a128b460b7.jpeg)
![ca05257b-55cb-4fcf-90da-85ec42685a6e](https://user-images.githubusercontent.com/6134547/32607662-aa9e041a-c594-11e7-852b-4705b21224a6.jpeg)
![Uploading 7253A38C-3988-42D6-A0C4-E27CF8473BB0.jpeg…]()
![Uploading 91AB3F59-9ADA-4F0C-962B-81B4ABECFCE9.jpeg…]()

**Comment by yoyo837** [comment]
![56f46b19-326e-413e-8256-f24e930e2a3a](https://user-images.githubusercontent.com/6134547/32607775-f9e966fe-c594-11e7-8a36-d6a1e2cd99f1.jpeg)
![ce4dfb85-5e8c-4758-839f-48af53027e61](https://user-images.githubusercontent.com/6134547/32607780-fe45aa0a-c594-11e7-9d5c-d54354b188e6.jpeg)

**Comment by egamma** [comment]
This looks like an exception from the VS Code terminal, please file the issue against VS Code, but pls add steps for how you can reproduce the error, e.g.,
- what did you do before the error showed up
- can you always reproduce it
- ...
