### ISSUE TITLE
autoFixOnSave does not work with other auto formatters

### ISSUE THREAD

**Issue by robyoder** [Microsoft/vscode-tslint#294]
@egamma [commented here](https://github.com/Microsoft/vscode-tslint/issues/136#issuecomment-263000398)

> There is another restriction in that the code will not do an autofix if a document has been modified during the 'onWillSave' event. This can happen when you have a formatter extension that also formats your document on Save.

I use an extension that implements [`import-sort`](https://github.com/renke/import-sort) with a custom sort style and it sorts on save. A couple of months ago it was actually working fine with `vscode-tslint`. Both were autofixing on save. But now tslint won't autofix on save anymore unless I disable the sort on save for the other extension.

It's weird that it was working fine a couple of months ago because the comment I mentioned at the top was from a year ago.

**Comment by robyoder** [comment]
Hmm, it looks like it may depend on the order in which the extensions are loaded. I played around with enabling and disabling extensions and there was one time where both extensions were enabled and both were autofixing on save. But every other time only the import sorter works.

It sounds like an issue where if the import sorter runs first, the tslint autofixer won't run, but if tslint runs first the import sorter will still run. How would I figure out which of these two formatters is running first?

**Comment by egamma** [comment]
The above restriction has not changed

>There is another restriction in that the code will not do an autofix if a document has been modified during the 'onWillSave' event. This can happen when you have a formatter extension that also formats your document on Save.

Can you provide steps so that I can reproduce the behavior you are seeing?

**Comment by robyoder** [comment]
@egamma the purpose of this issue was to change that restriction. Are you saying you won't change it or you don't want to reopen this issue until I provide steps to reproduce?

I thought you already understood the restriction and simply hadn't fixed it yet.

I don't know if I can provide steps to reproduce because the behavior hasn't been consistent. I've installed this extension as well as [`sort-imports`](https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports) and set both to fix/sort on save:

```
"sort-imports.on-save": true,
"tslint.autoFixOnSave": true,
```

That's all. One session it worked, then I disabled and reenabled the extension and it started failing again.

**Comment by egamma** [comment]
@robyoder the restriction is well understood but it is critical to keep it, otherwise fixes get applied that are not in sync with the document state that was used to compute them. 

The VS Code implementation supports multiple onWillSave participants and it calls them in sequence one participant after the other. So it should be possible to have multiple participants. I suspect an issue in the onWillSave in vscode-tslint and for this reason I'd like to have a reproducible case. I will try with the steps you mention.
