### ISSUE TITLE
Improve wording of the 'disable rule' quick fix

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode-tslint#298]
- tslint Version: 5.8.0
- typescript Version: 2.6.1

We can manually type `// tslint:disable-next-line` or other comments to disable tslint.

However, as we use TypeScript, tslint, istanbu, eslint, etc together all the time, it is hard to remember the convention used by each system.

Add a snippet or command for these would be of great help. 🌷

**Comment by egamma** [comment]
@unional there are already is a quick fixes for disabling the rule for a warning:

![image](https://user-images.githubusercontent.com/172399/33240967-9d18eb60-d2bf-11e7-9a66-0aecbf3b1bfe.png)

I'll look into the different options CompletionProvider and Snippet.

**Comment by unional** [comment]
I see. I have not used the `Disable rule ...` before. I thought it will disable that rule for the whole project (i.e. changing the `tslint.json`).

Maybe `Disable rule "..." once` or `Disable rule "..." for this line"?

**Comment by egamma** [comment]
I came to the same conclusion, the quick fix is better since it will disable a specific rule.

I went with this wording:
![image](https://user-images.githubusercontent.com/172399/33257439-77a93d52-d356-11e7-9d45-8bafb4b849c3.png)
