### ISSUE TITLE
Option to specify external tslint installation

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode-tslint#3]
If you have 5 projects, it's pointless installing tslint 5 times.

Simple implementation would be a single global setting, but a per-project setting may also be useful.

Thanks for the extension. =)

**Comment by egamma** [comment]
You can install tslint globally (`npm install -g tslint`) and it should be picked up by the extension. Did you try this and it didn't work?

**Comment by glen-84** [comment]
Hi Erich,

I hadn't tried that, because the error message makes no mention of it:

> Failed to load tslint library. Please install tslint in your workspace folder using 'npm install tslint' and then press Retry.

I just tried it now and it works.

Thank you. =)

**Comment by irq** [comment]
Related issue:
I am using gulp-tslint, I think it would be great if the extension would pick it up from there (tslint being a dependency of gulp-tslint).

For now I will also just install it globally.

**Comment by egamma** [comment]
I'll update the error message, thanks

**Comment by egamma** [comment]
In 0.5.39 provides a setting 'tslint.nodePath' that can be used to configure an additional node_modules folder that should be consulted when looking for the tslint module.
