### ISSUE TITLE
Hard to understand, how to configure this to work with jsx?

### ISSUE THREAD

**Issue by IljaDaderko** [Microsoft/vscode-tslint#302]
- tslint Version: 1.0.24
- typescript Version: 2.6.2

Steps to Reproduce:

1. Create .tsx and .ts files
2. .ts files are linted correctly, but .tsx seem to be ignored

I'm almost sure I am telling tsconfig.json to use jsx, here is my full file
```
{
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "lib": ["es7"],
    "allowJs": true,
    "checkJs": true,
    "jsx": "react-native",
    "removeComments": true,
    "outDir": "./dist",
    "typeRoots": ["node_modules/@types", "./typings"],
    "experimentalDecorators": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "allowSyntheticDefaultImports": true,
    "strict": true
  },
  "exclude": ["./node_modules", "./android", "./ios", "./assets", "./__tests__", "./dist"],
  "include": ["./src"]
}
```

here is my tslint.json
```
{
  "extends": ["tslint-config-airbnb", "tslint-config-prettier"],
  "rules": {
    "import-name": false,
    "variable-name": [true, "check-format", "allow-pascal-case"]
  }
}
```

it works correctly, airbnb and prettier rules are applied in .ts files and editor gives correct feedback, but not in .tsx files

**Comment by egamma** [comment]
Tslint supports .tsx files out of the box and I've added a test case for a tsx file and it works for me https://github.com/Microsoft/vscode-tslint/blob/master/tslint-tests/tests/testcomponent.tsx. Please see the screenshot below.

![image](https://user-images.githubusercontent.com/172399/33516717-b3f4b370-d777-11e7-911b-7937742625f8.png)

**Comment by IljaDaderko** [comment]
@egamma I'm away from my pc, but will try the `jsx: preserve` option in my config latter, could this be a possible cause? i.e. I am using `react-native`, alternatively I am targeting es6 instead of es5, might be second reason.

**Comment by egamma** [comment]
@IljaDaderko the target es5 or es6 has no impact and both work for me.

Also if you have issues in this area then I suggest to continue the discussion in the tslint repository since the extension cannot do anything about it.
