### ISSUE TITLE
first learn tslint

### ISSUE THREAD

**Issue by InkoiWong** [Microsoft/vscode-tslint#305]
- tslint Version: 1.0.24
- typescript Version: 2.6.2

Steps to Reproduce:

1.
从TSLint官网文档直接复制代码学习时
function greeter(person: string) {
  return "Hello, " + person;
}
let user = "Jane User";
document.body.innerHTML = greeter(user);
2.
报错
[ts] 函数实现重复 (1, 10)
[ts] 无法重新声明块范围变量"user" (5, 5)

**Comment by InkoiWong** [comment]
I just read https://www.tslang.cn/docs/handbook/typescript-in-5-minutes.html
and follow the step from the introduction
then I got the error msg like above i wrote
could you give me a help
i am learning tsc

**Comment by egamma** [comment]
hi, both issues are related to typescript and have nothing todo with vscode-tslint.

i suggest that you ask your question on StackOverflow.
