### ISSUE TITLE
Support autoFixOnSave as a resource setting

### ISSUE THREAD

**Issue by lukeautry** [Microsoft/vscode-tslint#309]
- tslint Version: 5.7.0
- typescript Version: 2.6.2

Info tooltip in settings.json: `This setting cannot be applied now. It will be applied when you open this folder directly.`

Any plans for supporting this setting in workspace?

**Comment by egamma** [comment]
@lukeautry this setting is currently a `windows ` level setting. The goal is to make as many settings as possible to be a `resource ` level setting, so this is a fair feature request.

Having said this you can enable autoFixOnSave in your user settings and then it will apply to the entire workspace.
