### ISSUE TITLE
Make color and shape of error markers configurable

### ISSUE THREAD

**Issue by Franziskus1988** [Microsoft/vscode-tslint#31]
Sometimes it's difficult to find/see the green marked linting errors. Especially when a file contains a lot of comments (normally green).

Would it be possible to make the color and maybe the line thickness configurable?

**Comment by egamma** [comment]
Rendering diagnostics is a general vscode feature.

Moving to vscode

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode#4388
