### ISSUE TITLE
Failed to load the TSLint library for the document 

### ISSUE THREAD

**Issue by AskYous** [Microsoft/vscode-tslint#314]
- tslint Version: 5.9.1 (ran `tslint -v`)
- typescript Version: 2.6.2 (ran `tsc -v`)

When I open any file, I get an error right away in the tslint output saying:

> Failed to load the TSLint library for the document /Users/<hidden>/assets/js/app.ts

> To use TSLint in this workspace please install tslint using 'npm install tslint' or globally using 'npm install -g tslint'.
TSLint has a peer dependency on `typescript`, make sure that `typescript` is installed as well.
You need to reopen the workspace after installing tslint.

I don't have tslint or typescript installed in my project, but I do have them installed globally. I have some screenshots: https://imgur.com/a/woR0x that perhaps they'll help.

**Comment by egamma** [comment]
I haven´t seen this issue in a long while. 

Just for testing does your setup work when you install typescript and tslint locally into your project?

Do the globally installed typescript and tslint modules have compatible versions?

What are the versions of the globally installed tslint and typescript modules?

**Comment by AskYous** [comment]
Hey @egamma, I don't know why but it's working now. I still have them installed globally. I think all I did was restart my computer. Do you still want me to run the tests?

**Comment by egamma** [comment]
@AskYous then let´s close the issue for now, please reopen if you run into this problem again.
