### ISSUE TITLE
max-line-length rule does not support latest schema

### ISSUE THREAD

**Issue by stefanotto** [Microsoft/vscode-tslint#315]
- tslint Version: 5.9.0
- typescript Version: 2.3.4 

Steps to Reproduce:

1. Set `"max-line-length": [true ,80]` in `tslint.json` and lint a file containing lines longer than 80 chars
2. Change rule to `"max-line-length": [true, {"limit": 80, "ignore-pattern": "^import |^export {(.*?)}"}]` as per https://palantir.github.io/tslint/rules/max-line-length/ and see affected lines don't show up as problems, whereas calling `ng lint` (Angular project) does.

**Comment by egamma** [comment]
The vscode-tslint extension is using the schemas provided by [schemastore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/tslint.json) for validating tsconfig.json. This is an upstream issue and PRs to schema are always welcome.
