### ISSUE TITLE
How set config？

### ISSUE THREAD

**Issue by tomoat** [Microsoft/vscode-tslint#318]
- tslint Version:5.91
- typescript Version: 2.6.2

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/7428698/35664685-06855e62-075e-11e8-99e4-6ba9bb8cdd2c.png)

**Comment by egamma** [comment]
@tomoat what is the problem?  Can you please include the error message?

**Comment by egamma** [comment]
Closing, please reopen when you can provide additional information.

**Comment by tomoat** [comment]
![image](https://user-images.githubusercontent.com/7428698/35837850-5f3cc1a8-0b23-11e8-962f-9f70e4ff0c29.png)
![image](https://user-images.githubusercontent.com/7428698/35837901-9c208140-0b23-11e8-9685-468229b46212.png)
![image](https://user-images.githubusercontent.com/7428698/35837912-a5115978-0b23-11e8-87f7-ffc17d84e65f.png)

The code in the third chapter should be correct, but the warning is given.

**Comment by egamma** [comment]
@tomoat please show me the error message. To do so place the cursor over the red line and press the F8 key. This will show the error message.
