### ISSUE TITLE
[Request] An option to only ignore _some_ definition files

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/vscode-tslint#319]
- tslint Version: 5.9.1
- typescript Version: 2.7.0

Currently, it is possible to lint `.d.ts` files with the `"tslint.ignoreDefinitionFiles": false` option; but this also causes tslint to attempt to lint typescript lib files (`dom.lib.d.ts`, or other definitions that come from `node_modules`. The alternative is to disable it, but that stops vscode from helping lint my own local `.d.ts` files.

The request is to have a way to only enable linting of definition files if they are not descendants of a `node_modules` directory.

Example from a project at work (cropped to omit directory names):
<img width="118" alt="image" src="https://user-images.githubusercontent.com/73085/35892783-57728108-0bee-11e8-8d4a-9c97dcf69dbc.png">

The first `index.d.ts` is from `workspace_root/node_modules/@types/jquery`; the rest is from `workspace_root/node_modules/typescript/lib`. They all have `251` errors because tslint bailed due to having over 250 errors, and can get linted even without opening the file directly; when cmd+hovering a definition that comes from those files, for example.

**Comment by egamma** [comment]
vscode version 1.0.28 supports the  `linterOptions.exclude` (https://palantir.github.io/tslint/usage/configuration/) attribute in tslint.json, with this attribute you can exclude any number of files and it should support what you are trying to do.
