### ISSUE TITLE
jsdoc-format schema issue

### ISSUE THREAD

**Issue by michael-letcher** [Microsoft/vscode-tslint#320]
### Bug Report

- __TSLint version__: 5.7.0
- __TypeScript version__: 2.6.2
- __Running TSLint via__: VSCode

#### TypeScript code being linted

Snippet from docs
https://palantir.github.io/tslint/rules/jsdoc-format/

```json
"jsdoc-format": [true, "check-multiline-start"]
```

with `tslint.json` configuration:

```json
"jsdoc-format": [
  true,
  "check-multiline-start"
]
```

#### Actual behavior

`Array has too many items according to schema. Expected 1 or fewer.`

#### Expected behavior

No error

**Comment by egamma** [comment]
Sorry about this but the vscode-tslint extension is using the schemas provided by [schemastore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/tslint.json) for validating tsconfig.json. This is therefore an upstream issue and PRs to schema are always welcome.

**Comment by michael-letcher** [comment]
https://github.com/SchemaStore/schemastore/issues/358
