### ISSUE TITLE
AutoFix on save doesn't work with Vim emulation save

### ISSUE THREAD

**Issue by karptonite** [Microsoft/vscode-tslint#321]
- tslint Version: 5.9.1
- typescript Version: 2.6.2

Steps to Reproduce:

1. Install Vim plugin
2. save a file with `:w`

Not sure if this is a Vim plugin bug or a vscode-tslint bug, but for whatever reason, if I save a file with `:w` in vim mode, the tslint autofixOnSave is not triggered. For what it is worth, I also use prettier-vscode, and and does autoformat on save with `:w`.

**Comment by jrobeson** [comment]
I wonder if this and https://github.com/Microsoft/vscode-tslint/issues/340 are related.

**Comment by egamma** [comment]
@jrobeson it is related same as for #340 the onWillSaveTextDocument isn´t fired.
Not clear whether this is an issue with the VIM extension or VS Code. Linked to the same VS Code issue for now.

**Comment by egamma** [comment]
I can no longer reproduce this in the latest insider.
