### ISSUE TITLE
[Angular Specific] Uneccessary component selector error

### ISSUE THREAD

**Issue by digitalclover** [Microsoft/vscode-tslint#322]
- tslint Version: 1.0.27
- typescript Version: 2.4.2
- Angular Version: 5.2.1

Steps to Reproduce:

1. Create an Angular Component
2. Use a custom prefix for that components selector

The following error is shown:
`The selector of component [name] should have prefix "app"` 
The error is accompanied by a reference URL to the Angular Style Guide [https://angular.io/guide/styleguide#style-02-07](https://angular.io/guide/styleguide#style-02-07)

However, the referenced URL states that custom prefixes are valid to use.

> Do use a custom prefix for a component selector. 

> Do use a prefix that identifies the feature area or the app itself.

By this logic, the error is unnecessary.

**Comment by brgrz** [comment]
Exactly. I have errors in all components and everything's red because of this.

**Comment by egamma** [comment]
These errors must come from some angular specific rules (e.g. codelyzer?), these rules are not contributed by vscode-tslint and the error should be reported against the rule provider.

**Comment by brgrz** [comment]
Thanks. For anyone else running into this, you should add your prefixes to the tslint.json file within your project (the "directive-selector" and "component-selector" sections).

**Comment by digitalclover** [comment]
Yeah, I ended up just disabling that those two rules for my project.
