### ISSUE TITLE
Ignored files intermittently show up in problems window

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-tslint#325]
- tslint Version: 5.9.1
- typescript Version: 2.7.1

Apologies for the woolly report, I'll add more info/screenshots next time it happens. This has been common over the last few weeks...

I have some files that are ignored because the violate a bunch of lints (they're code-gen'd and I haven't fixed them yet):

https://github.com/Dart-Code/Dart-Code/blob/65a2b89e8dce364bfe352914ad001d4fe478084f/tslint.json#L6-L9

Now and then, they will randomly show up in the problems view (with hundreds of errors). If I click on one to open the file, and then close it again, the problems all vanish.

I haven't noticed a pattern to what causes them to appear (but I'm definitely not opening the file).

**Comment by egamma** [comment]
I see that you are using the `linterOptions` setting that was added in tslint 5.8. This setting is only honored when running tslint from the command line, but not when using the tslint API (https://github.com/palantir/tslint/issues/3577#issuecomment-351728015). This means tslint-integrations have re-implement the same behaviour that the CLI does https://github.com/AtomLinter/linter-tslint/issues/211. 

As a work around you can also exclude files by using the vscode-tslint setting `tslint.exclude` in your `settings.json`.

**Comment by DanTup** [comment]
Aha, I'll give it a go - thanks!

**Comment by egamma** [comment]
support for linterOptions.exclude has been published in version 1.0.28.
