### ISSUE TITLE
Only some of tslint warning appear in vscode Problems tab

### ISSUE THREAD

**Issue by semiadam** [Microsoft/vscode-tslint#329]
- tslint Version:
- typescript Version:
2.7.2

I'm not sure if this is a bug or mis-config, but I couldn't fix it yet. In my environment, some tslint warning/erros appear in vscode "Problems" tab, which will take me to the exact line of issue when I click them, and as soon as I save the file they disappear. There are however some of the warnings/errors that only appear at full compile time, and clicking on them only opens the file without taking me to the exact line. It also requires a fresh compile to get rid of these. Is there a way to get all warnings in problems tab?

**Comment by egamma** [comment]
@semiadam 

>There are however some of the warnings/errors that only appear at full compile time, and clicking on them only opens the file without taking me to the exact line.

What does this exactly  mean? Are you running tslint from a task with a problem matcher? Please share a screenshot and your tasks.json.

**Comment by semiadam** [comment]
Yes, I use Create React App which internally uses Webpack. Here's a screenshot:

![image](https://user-images.githubusercontent.com/5418638/37080816-4555a69e-219c-11e8-9e62-1d33bc8339f5.png)

in this case both TERMINAL and PROBLEMS tabs reported the issue. But earlier today I had a lot of issues that was only in TERMINAL tab (which are fixed now). Is PROBLEMS tab supposed to show issues from the entire project, even if the files are not opened in the editor? Or does it only work with the opened files? Also, is there any way to point the issues in terminal tab to the exact line number in editor when clicked?

**Comment by egamma** [comment]
In you setup errors shown in the open files show up in the problems. Errors from a tool shown in the terminal do not show up in the Problems View unless you are using tasks and Problem Matchers, which I don´t think you do. Therefore what you see is the expected behaviour.

BTW, the error message is from eslint and not tslint 😄
