### ISSUE TITLE
Rule flags working?

### ISSUE THREAD

**Issue by vagyriag** [Microsoft/vscode-tslint#33]
Hi,

I'm trying to use the rules flags `/* tslint:disable */ /* tslint:enable */`
but they don't seem to be working

**Comment by egamma** [comment]
Cannot reproduce, see below

![image](https://cloud.githubusercontent.com/assets/172399/13861828/c10d06fe-ec8f-11e5-9e71-d04d38e019f8.png)

Does it work when you invoke tslint from the command line? If it doesn't neither, then please file an issue against tslint.
