### ISSUE TITLE
extension makes problems reported via the problem-matcher disappear when a file is opened

### ISSUE THREAD

**Issue by marcelh-gh** [microsoft/vscode-tslint#337]
- tslint Version: 5.9.1
- typescript Version: 2.8.1

I want to detect some issues which require type information. Therefore I have configured a task to run tslint and then report via the problem-matcher (v5).

Here is the issue: when I click on one of the reported issues (based on type info), the file opens and immediately this issue and all other type info based ones disappear.

It seems to me, the extension (being in charge for the currently opened file) just overwrites the problems and since the extension can't handle type info yet, the issues disappear.

I have tried to configure the problem-matcher for "allDocuments" but that didn't help.

**Comment by egamma** [comment]
This is a challenging setup, you have 2 different sources (vscode-tslint and task that runs tslint) for the problems and the sources produce overlapping problems (the task generates a super set of the problems of vscode-tslint). 

The only solution I see is that in your task.json you overwrite the owner of the problem to be ´tslint-task´ then you have separate diagnostics. 

```
"problemMatcher": {
    "base": "$tslint5",
    "owner": "tslint-task"
}

**Comment by marcelh-gh** [comment]
(1) thanks a lot for the super quick response! :-)
(2) true, it is a challenging setup - it wouldn't be though, if vscode-lint could support type info based rules - any info on that?
(3) great idea with the owner setting - I was not aware that I could change that to arbitrary values :-)

**Comment by egamma** [comment]
>(2) true, it is a challenging setup - it wouldn't be though, if vscode-lint could support type info based rules - any info on that?

pls see https://github.com/Microsoft/vscode-tslint/issues/70#issuecomment-298177554. 

Did the work around work?

**Comment by marcelh-gh** [comment]
@egamma 
Sure, it did. Obviously when you fix an error reported by the task, it does not disappear from the list right away like the ones reported by the extension, but that is tolerable for the time being.

Thanks for the link...I'll look into that...

Cheers,
Marcel

**Comment by marcelh-gh** [comment]
@egamma 
Ok, I have installed and configured tslint & tslint-language-service locally and it works like a charm.
Since you are contributing to both the extension and the language-service, are there any plans to combine efforts on the two projects? 
Do you have a list of features that only the extension has? 
I just quickly checked and even auto-fixing works fine without the extension.
Thanks a lot!

**Comment by egamma** [comment]
@marcelh-gh yes the plan is to have an extension that is based on the tslint-language-service. There is a prototype of [such an extension](https://marketplace.visualstudio.com/items?itemName=eg2.ts-tslint) that is now outdated. It explains the current differences between the language service plugin and the current extension in the extension description.

**Comment by marcelh-gh** [comment]
the suggested solution with tslint & tslint-language-service installed locally worked well as I posted on 12 Apr. However recently it somehow stopped working.
I only get tslint based error messages for **open** files and if I run tsc manually, **none** of the tslint based errors get reported.

tslint version: 5.9.1
typescript version: 2.8.**_3_**
tslint-language-service version: 0.9.9

```
        "plugins": [
            {
                "name": "tslint-language-service",
                "alwaysShowRuleFailuresAsWarnings": false,
                "ignoreDefinitionFiles": true,
                "disableNoUnusedVariableRule": true,
                "supressWhileTypeErrorsPresent": false,
                "mockTypeScriptVersion": true
            }
        ]
```

Any ideas what might be the problem? Thanks a lot!

**Comment by marcelh-gh** [comment]
when I switch the Typescript version inside VS Code to the local one, I get this error message:
```
Error: the description can't be converted into a problem matcher:
{
    "base": "$tslint5",
    "fileLocation": "relative",
    "owner": "tslint",
    "applyTo": "closedDocuments"
}
```

This might be hinting at the problem. I am just not sure what I could change. I would understand this, if I was using a custom task to configure a problem-matcher, but I am not doing that.

**Comment by egamma** [comment]
Regarding https://github.com/Microsoft/vscode-tslint/issues/337#issuecomment-392706495.

>when I switch the Typescript version inside VS Code to the local one, I get this error message

Not clear what your setup is, since the tslint-language-service only works with the locally installed TS version it does not work otherwise.


Do you still have a tasks.json file in your project? When you do not have the vscode-tslint extension installed, then there is indeed no problem matcher contributed for $tslint5.

**Comment by marcelh-gh** [comment]
@egamma thanks for the quick reply. Actually it's my bad. When I originally created this issue, I had two problems: 1) project level analysis and 2) using tslint-rules that need type info. The solution with the tslint-language-service solved 2) but not 1). 

However, the task to run tslint at project level does not provide data to the problem-matcher anymore. I am pretty sure, that was working before. 
Regarding the TSLint ext for VS Code: I did not uninstall, just deactivate it.

```
  "scripts": {
    "lint": "tslint --project tsconfig.json -t verbose"
  },
```

```
    "tasks": [
        {
            "type": "npm",
            "label": "tslint-workspace",
            "script": "lint",
            "problemMatcher": {
                "base": "$tslint5",
                "owner": "tslint-workspace",
                "fileLocation": "relative",
                "applyTo": "closedDocuments"
            }
        },
```

**Comment by marcelh-gh** [comment]
ok. it seems, deactivating the TSLint extension is the main problem since that's where the $tslint5 problem-matcher comes from. 
Maybe there is a way to supply that even when the extension is deactivated?

**Comment by marcelh-gh** [comment]
ok. I did that and it works. :-)
Initially I did configure the problem-matcher and the pattern both in place with the task using them. That works.
If I try to take them out and name them (like in the package.json of TSLint ext) it does not work. See below. Unfortunately the docs for VS Code don't talk about how to name your own patterns & matchers and then reference them.

in package.json
```
 "problemPatterns": [
    {
      "name": "tslint5",
      "regexp": "^(WARNING|ERROR):(\\s+\\(\\S*\\))?\\s+(\\S.*)\\[(\\d+), (\\d+)\\]:\\s+(.*)$",
      "severity": 1,
      "file": 3,
      "line": 4,
      "column": 5,
      "message": 6
    }
  ],
  "problemMatchers": [
    {
      "name": "tslint5",
      "owner": "tslint-workspace",
      "source": "tslint",
      "label": "tslint (version 5) warnings",
      "applyTo": "closedDocuments",
      "fileLocation": "absolute",
      "severity": "warning",
      "pattern": "$tslint5"
    }
  ],
```

in tasks.json:

```
  {
            "type": "npm",
            "label": "tslint-workspace",
            "script": "lint",
            "problemMatcher": "$tslint5"
}
```

**Comment by jasonswearingen** [comment]
fyi the ```"owner": "tslint-task"``` fix worked for me on VSCode July 2018  using TS3.0.1

**For those who "just want the solution"**,  Here is my tasks.json

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "tslint",
			"type": "shell",
			"command": "tslint --project tsconfig.json --config tslint.json --format verbose ./dev/**/*.ts",
			"problemMatcher": {
				"base": "$tslint5",
				"fileLocation": "absolute",
				"owner": "tslint-task"
			},
			"group": {
				"kind": "test",
				"isDefault": true
			}
		},
	]
}
```
using the above task lets you apply a keyboard shortcut to run it (as your "test" task)

also i have  **typescript 3.0.1** and **tslint** installed locally using **npm --save-dev**

**Comment by marcelh-gh** [comment]
since tslint is being deprecated and with the latest vscode update (1.42.0) there is now a quite viable option using eslint with the respective typescript plugin, I am closing this.
