### ISSUE TITLE
autoFixOnSave does not appear to work with VS Code's Save All command.

### ISSUE THREAD

**Issue by Seefer1** [Microsoft/vscode-tslint#340]
- tslint Version: 1.028
- typescript Version: 2.8.1

with **tslint.autoFixOnSave** enabled it does not appear to work when you run VS Code's Save All command.  Saving an individual file with CTRL+S seems to work fine. Is this expected behaviour?

**Comment by egamma** [comment]
Issue confirmed, filed https://github.com/Microsoft/vscode/issues/50549 against vscode.

**Comment by egamma** [comment]
I can no longer reproduce this in the latest VS Code insider build.
