### ISSUE TITLE
"Create a 'tslint.json' file" doesn´t work with local tslint install

### ISSUE THREAD

**Issue by OiYouYeahYou** [Microsoft/vscode-tslint#343]
- tslint: 5.9.1
- typescript: 2.8.3
- VSCode: 1.22.2 
- OS: mocOS 10.13.3

Steps to Reproduce:

1. Open command pallete
2. Select "Create a 'tslint.json' file"

There doesn't seem to be any error output unfortunatley, nor does it create a config file

**Comment by egamma** [comment]
I assume that you have tslint not installed, now showing an error when spawning the tslint process fails.

**Comment by OiYouYeahYou** [comment]
To add tslint outputs the error message that requests tslint is installed locally or globally to use in the workspace. Which gives an expectation that local dependencies should work with the `create` function

```
To use TSLint in this workspace please install tslint using 'npm install tslint' or globally using 'npm install -g tslint'.
TSLint has a peer dependency on `typescript`, make sure that `typescript` is installed as well.
You need to reopen the workspace after installing tslint.
```

**Comment by egamma** [comment]
Reopening, the code doesn´t handle the case of a locally installed tslint, but this should be supported.
I´ve changed the title accordingly.
