### ISSUE TITLE
executing custom rules in real time

### ISSUE THREAD

**Issue by MoistJohn** [Microsoft/vscode-tslint#344]
I wrote a custom rule to uphold part of our coding standards, and when I run the linter, it works and catches the problem.

How do I make it so that my rule will run while I work and mark my code with a squigly underline? It already does it for the predefined rules.
(See attached image)

Thanks,
John
![untitled](https://user-images.githubusercontent.com/11527783/39867435-9152b2f0-545d-11e8-8be1-1e8e70d3cc4c.png)

**Comment by MoistJohn** [comment]
@infogulch The rule is written in TypeScript, but it's compiled into JS.

**Comment by infogulch** [comment]
I mean, are you compiling it yourself `tsc myRule.ts` or are you registering typescript with node to run directly?

**Comment by MoistJohn** [comment]
tsc myRule.ts
