### ISSUE TITLE
no-unused-variables doesn't work

### ISSUE THREAD

**Issue by RyanMitchellWilson** [Microsoft/vscode-tslint#346]
I'm trying to have vscode tell me when I have unused variables, but I do not want to use the configOption `noUnusedParameters` or `noUnusedLocals` in my tsconfig file due to the fact that it causes my compile to fail. I would like to know about these kinds of errors but I don't want them to stop me from developing.

- tslint Version: 1.0.29
- typescript Version: 2.8.3

Steps to Reproduce:

1. Add `no-unused-variables: true` to your tslint.json.
2. Notice that it doesn't do anything in any of your files.

**Comment by egamma** [comment]
@RyanMitchellWilson pls see https://github.com/Microsoft/vscode-tslint/blob/master/tslint/README.md#the-tslint-no-unused-variable-rule-doesnt-report-warnings-any-more

**Comment by RyanMitchellWilson** [comment]
@egamma As I stated in my initial message I cannot use those configOptions due to the fact that they cause my compile to fail for something that should just cause a warning. Therefore I need to use the linter option. I see that you have documented that tslint doesn't support this right now, but that was 2 years ago. Is this ever going to be prioritized and added?

**Comment by egamma** [comment]
@RyanMitchellWilson pls see https://github.com/Microsoft/vscode-tslint/issues/70#issuecomment-298177554
