### ISSUE TITLE
TSLint doesn't work on second project without any errors

### ISSUE THREAD

**Issue by Kenya-West** [Microsoft/vscode-tslint#348]
- tslint Version: 5.10.0
- typescript Version: 2.7.2
- node Version: 10.2.0
- npm Vesion: 6.1.0
- using VS Code latest stable

Steps to Reproduce:

1. Setup two similar projects with exact same TSLint configuration
2. Get your mind blown

I have two projects (backend and frontend) with TSLint locally installed in `devDependencies`, it is also globally installed via npm with same version. But TSLint doesn't work on **backend** project, leaving this message in "Output" window:

`
[Info  - 11:57:07] Linter is running.
[Info  - 11:57:14] TSLint library loaded from: e:\Dev\nefu-rooms-constructor-backend\node_modules\tslint\lib\index.js
` - and nothing happens, it doesn't highlight anything.

TSLint on **frontend** project works perfectly. This is what it writes in "Output":

```
[Info  - 12:14:29] Linter is running.
[Info  - 12:14:31] TSLint library loaded from: e:\Dev\Git\nefu-rooms-constructor\node_modules\tslint\lib\index.js
typeof-compare is deprecated. Starting from TypeScript 2.2 the compiler includes this check which makes this rule redundant.

Could not find implementations for the following rules specified in the configuration:
    no-access-missing-member
    templates-use-public
    invoke-injectable
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
        
Warning: The 'no-use-before-declare' rule requires type information.
[Info  - 12:15:56] vscode-tslint: Status is OK
```

On other machine, TSLint works correctly on both projects. So, this is what entire situation looks like:

| Device  | Backend | Frontend |
| ------------- | ------------- | ------------- |
| Laptop  | TSLint doesn't work  | TSLint works  |
| PC  | TSLint works  | TSLint works  |

Of course, it is something with local project, but what exactly? I tried everything I guess: reinstalled entire repo, `Remove-Item ./node_modules/ -R -F ; npm cache verify; npm i`, wiped and reinstalled all global packages.

**Comment by egamma** [comment]
Can you please also try the trouble shooting steps https://github.com/Microsoft/vscode-tslint/blob/master/tslint/README.md#trouble-shooting
