### ISSUE TITLE
Unused variable in default exports

### ISSUE THREAD

**Issue by remojansen** [Microsoft/vscode-tslint#35]
I'm working on a library and my its point looks as follows:

![untitled](https://cloud.githubusercontent.com/assets/10656223/13807906/860353e0-eb5b-11e5-9916-7dc243fbbd7d.png)

As you can see it says that some variables are not used. This is happening only for modules with `default` export. When I run `gulp-tslint@4.3.1` this errors are not there.

**Comment by egamma** [comment]
This looks like a false positive reported by tslint, pls report the issue against the tslint repository
https://github.com/palantir/tslint/issues
