### ISSUE TITLE
max-line-length rule does not support latest schema

### ISSUE THREAD

**Issue by ryanbowden** [Microsoft/vscode-tslint#351]
I saw issue #315 
so created a pull request on schema - https://github.com/SchemaStore/schemastore/pull/470
I just can't work out how to get it to work in this plugin now otherwise would have done a pull request.

**Comment by egamma** [comment]
@ryanbowden thanks for the PR against the schema store. The extension fetches the schema from the schemastore. Therefore no changes are needed to the extension. I see the PR has been merged into the schema store, so things should work now.

**Comment by ryanbowden** [comment]
TYhey are not working I Have the following:

`"max-line-length": [
            true,
            {
                "limit": 140,
                "ignore-pattern": "^import {(.*?)}"
            }
        ],`

But all lines that are over 140 characters are not getting the warning they are too long. if I have this:
`"max-line-length": [
            true, 140
        ],`

the old way it works correctly. Is there something I need to do to refresh the schema it has or does the plugin need an update to support this new schema?

**Comment by egamma** [comment]
The schema is only used to validate the tslint.json, it has no impact on the application of the tslint rules.

To narrow down whether this is an issue with a tslint rule of the extension can you reproduce the behaviour when you run tslint from the commandline.

**Comment by ryanbowden** [comment]
Ah turns out had an older version of TSLint and just needed to update the version. Thank you.
