### ISSUE TITLE
[tslint] ' should be " (quotemark)

### ISSUE THREAD

**Issue by peterremote1980** [Microsoft/vscode-tslint#354]
these will not stop "[tslint] ' should be " (quotemark)"

			"quotemark": [
				true,
				"single"
			]

Why?

**Comment by egamma** [comment]
@peterremote1980 what is the problem and how can I reproduce the problem?

**Comment by egamma** [comment]
@peterremote1980 cannot reproduce, pls see the screenshot below.  Please reopen the issue when you can provide more detailed steps to reproduce the problem.

![image](https://user-images.githubusercontent.com/172399/41664161-5a71170a-74a5-11e8-81cd-bf96e0597a2f.png)
