### ISSUE TITLE
autoFixOnSave mangling code

### ISSUE THREAD

**Issue by kbirger** [Microsoft/vscode-tslint#356]
- tslint Version: 5.10.0
- typescript Version: 2.6.2
-  extension Version: 1.0.30
- VS Code version: 1.24.0 Windows 10 x64
Steps to Reproduce:

1. enable semicolon, import sorting, and whitespace in tslint
2. enable editor.autoSave
3. write code, hit ctrl+s

Sporadically, this will mangle my code. Sometimes it adds several semicolons where they are not necessary. Sometimes it will add combinations of whitespace and semicolons. Sometimes this happens in the middle of a word. 

Attached my tslint file. This was processed by ng lint --fix. I've encountered this in other projects too however, where the tslint was autogenerated from defaults.
[tslint.json.txt](https://github.com/Microsoft/vscode-tslint/files/2098806/tslint.json.txt)

**Comment by egamma** [comment]
@kbirger this has to do with overlapping fixes which are no fixed in multiple passes. when this happens next time can you please share the code that got mangled? Also when this happens can you execute undo multiple times and observe what happens. I´m interested in how many edits were involved.

**Comment by egamma** [comment]
@kbirger I´ve added additional protection against concurrent edits and published a new version 1.31. Please reopen the issue when you still see the mangling.

**Comment by kbirger** [comment]
I'll try to provide a specific example. For now, I can say that I have seen things such as ";;;;;;;;;;;;;;;;" generated, and I can actually see each individual semicolon get placed one at a time, and undoing removes them one-at-a-time as well.

**Comment by egamma** [comment]
> I can actually see each individual semicolon get placed one at a time, and undoing removes them one-at-a-time as well.

This is good info. This means that the fixes are detected as overlapping edits and they are applied in multiple passes. However, it looks like the same fix is applied multiple times, which would mean that the version of the document that tslint operates on is not up to date.

**Comment by egamma** [comment]
Published 1.32 which also protects against the case that the server´s version of the document and the editor´s version are out of sync.

**Comment by egamma** [comment]
@kbirger just checking, with the latest fixes can you confirm that the mangling issue is gone?

**Comment by kbirger** [comment]
I saw the issue maybe one more time since your 1.3.2 fix, but I wasn't able to catch what caused it. I would consider it closed. Thanks very much for fixing it so quickly. 

If I come across this again, I'll get a specific repro and post it.

**Comment by egamma** [comment]
@kbirger thanks!
