### ISSUE TITLE
editor.autoIndent setting is being ignored

### ISSUE THREAD

**Issue by baguasquirrel** [Microsoft/vscode-tslint#361]
- tslint Version: 1.0.33
- typescript Version: 2.4.2

Steps to Reproduce:

1. Write some code that would be auto-indented, e.g.
```
export type Action = UIActions |
    {
        type: 'RequestSession';
    } | {
        type: 'RequestSignout';
    };
```

2. Save the file.

**Comment by egamma** [comment]
@baguasquirrel why do you think this issue is related to vscode-tslint?
