### ISSUE TITLE
[Question] Identifier 'id' is never reassigned; use 'const' instead of 'let'. (prefer-const)

### ISSUE THREAD

**Issue by muyu66** [Microsoft/vscode-tslint#367]
- tslint Version: 1.0.33
- Npm tslint Version: 5.3.2
- typescript Version: 2.9.2

Example code:

```
function User(){
	return { id: 1, name: 'Tom' };
}
let { id, name } = User();
name = 'Jook';
console.log(id, name);
```

Then, tslint warn me, "Identifier 'id' is never reassigned; use 'const' instead of 'let'. (prefer-const)".

I am confused. I can't change ''let' to ''const' because i want to reassign ''name'. Repeatedly reading User() with two lines of code, I think it is not advisable, if even User() is Promise Function.

How to write pretty code?

**Comment by egamma** [comment]
@muyu66 this looks like a question for tslint and not the extension that integrates tslint into VS Code.
