### ISSUE TITLE
Show error in editor gutter instead of only in Problems window?

### ISSUE THREAD

**Issue by simkessy** [Microsoft/vscode-tslint#371]
I don't always have my problems window, if there's a lint error, can the line be highlighted somehow? Either the line of red circle beside the line number? I think that's more useful.

**Comment by egamma** [comment]
Errors and warnings are currently shown by:
- a decoration in the explorer
- a squiggle below the line with the warning
- a marker in the overview ruler on the right

Given these indications you do not need to have the problems view open.

![image](https://user-images.githubusercontent.com/172399/44085985-6fd2b0d6-9fbb-11e8-9838-83e670607a68.png)

**Comment by egamma** [comment]
This would have to be addressed in VS Code. The feature request exists. Closing as an upstream feature request.
