### ISSUE TITLE
TSLint Error on JS file with tslint.jsEnable set to false,

### ISSUE THREAD

**Issue by pp611** [Microsoft/vscode-tslint#372]
- VSCode Version: 1.25.1
- tslint Version: 5.11
- TSLint for Visual Studio Code: 1.0.34
- typescript Version: no `.ts` file, only `.js` files

Steps to Reproduce:
1. Clone https://github.com/marktext/marktext
2. open `src/main/menus/index.js` file

There are three `[ts]` lint errors. 

The default workspace setteings have
```
"tslint.jsEnable": false,
```

Custom workspace settings have:
```
{
    "tslint.alwaysShowStatus": true,
    "eslint.alwaysShowStatus": true
}
```

The status bar only shows ESLint s running.

<img width="796" alt="screen shot 2018-07-24 at 22 56 10" src="https://user-images.githubusercontent.com/12554834/43182951-3f3b9330-8f98-11e8-86f3-820f885a7281.png">

There is no content under `OUTPUT` tab.

I saw a close issue of disabling TSLint for JS file, but this one seems different. Is this normal? How to disable the TSLint and get rid of the error messages?

**Comment by egamma** [comment]
Diagnostices with the prefix `[ts]` come from TypeScript and not tslint. Diagnostics from tslint are prefixed with `[tslint]`.

You can disable JavaScript validation using the the setting `javascript.validate.enable`.

**Comment by pp611** [comment]
Thanks much for the quick reply. That does it.
