### ISSUE TITLE
vscode-tslint lints vscode temporary files in problems view

### ISSUE THREAD

**Issue by jhaenchen** [Microsoft/vscode-tslint#375]
- tslint Version: 1.0.34
- typescript Version: 3.0.1

Steps to Reproduce:
I seriously have no idea how this is happening, the files are waaaaay outside the project root.
![image](https://user-images.githubusercontent.com/7771519/43866818-bfdd9fd4-9b2c-11e8-93cf-eca547509ceb.png)

1.?????
2.?????
3.Profit

**Comment by egamma** [comment]
@jhaenchen from the screenshot it is not clear if these diagnostics are from tslint. 
Can please add a screenshot where you expand the nodes so that the full diagnostics becomes visible.
