### ISSUE TITLE
invalid semicolon setting

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-tslint#38]
https://github.com/Microsoft/vscode-tslint/blob/master/tslint.json#L52

semicolon should be always or never according to https://github.com/palantir/tslint

**Comment by timbru31** [comment]
Seems to be fixed by 3b38cfb67633e40f35296bdbcf426d4cdafb1516

**Comment by egamma** [comment]
Thanks @timbru31, forgot to close the issue.
