### ISSUE TITLE
Fix all auto-fixable problems not fixing all problems (must be applied multiple times)

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode-tslint#382]
- tslint Version: 1.0.36
- typescript Version: 2.9.2

Steps to Reproduce:

1. see video
http://streaka.testing.videos.s3.amazonaws.com/screencast_2018-08-24_16-41-59.mp4

Sometimes, it fixes one issue. Sometimes like 10. But it doesn't fix them all.

**Comment by egamma** [comment]
@jpike88 the current implementation of 'fix all auto fixable problems' has the limitation that in one pass only non-overlapping fixes are applied. Can you confirm that when you apply fix all multiple times that eventually all the fixes are applied?

**Comment by jpike88** [comment]
Correct eventually it gets them all done

**Comment by egamma** [comment]
Fix is in 1.0.37.
