### ISSUE TITLE
How disable type checking warnings?

### ISSUE THREAD

**Issue by jeudesprits** [Microsoft/vscode-tslint#385]
- tslint Version:  5.11.0 
- tslint extension Version: 1.0.38
- typescript Version: 3.0.3

Good day! I use _tslint-microsoft-contrib_ and _tslint-config-prettier_  rules. I also know that part of the _tslint-microsoft-contrib_ rules need type checking. The question is how to disable warnings in the output console in _vscode_, if these rules only work when manually starting tslint.

**Comment by egamma** [comment]
You cannot disable the warnings, but the good news is that we are working on an implementation of vscode-tslint that uses TypeScript Server plugins and this implementation will support type checking.

I´m closing this issue, since there are no plans to support this with the current implementation.
