### ISSUE TITLE
Feature Request: Integrate circular dependency checker into vscode-tslint 

### ISSUE THREAD

**Issue by AsiFefer** [Microsoft/vscode-tslint#389]
- tslint Version: latest
- typescript Version: 3.0.3

Hello,

Typescript linter should have circular dependency check task. In case linter found any circular dependency, between 2 modules, then it should display a warning about it, In VS code Terminal window.

For example, let's assume that module A uses Module B which in turn uses Module A again. In that case the following warning should be displayed:

Warning: Circular dependency found: A -> B -> A.

circular dependency check is easy to implement:
Linter reads the content of the files in the project. It reads the Import section of each module. It then follows the imports to the next file. It does so, until he reaches a module that has no imports. In case it starts from some module, and on the way it gets back to that module again, then this is a circular dependency between 2 modules.

Thanks,
Asi.

**Comment by egamma** [comment]
@AsiFefer this would have to be implemented by a tslint rule and not by the vscode-tslint extension. Therefore, this feature request should be filed against the tslint repository.

**Comment by AsiFefer** [comment]
I will make a request against tslint repository. Thanks.
