### ISSUE TITLE
Support multiple tslint.json?

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode-tslint#39]
```sh
+ root
  + spec
    + a.spec.ts
    + tslint.json
  + src
    + a.ts
  + tslint.json
```
Does it support this config so that `a.spec.ts` applies different rules than `a.ts`?

**Comment by unional** [comment]
I think it does:
https://github.com/Microsoft/vscode-tslint/blob/master/tslint-server/src/server.ts#L66
:+1: :smile:

**Comment by egamma** [comment]
@unional thanks for verifying. 

The tslint extension is using the tslint API to find the configuration, so I would have been surprised if this would not have been supported.

**Comment by unional** [comment]
yeah. Some other libraries, such as `gulp-tslint` and `grunt-tslint` does not use the `findConfiguraiton` or `loadConfigurationFromPath` call from `tslint`. So....

Also, since you are using tslint API, you are save in the future (soon) when `extends` and `exclude` lands. :smile: 

:beers:

**Comment by Glavin001** [comment]
I am having trouble getting VSCode's TSLint to work as described above.

TSLint extension version: 0.17.0
TSLint: local, per sub-directory

Structure:

```
+ root/
   + tslint.json
   + sub1/
      + tslint.json
      + src/
   + sub2/
      + tslint.json
      + src/
```

`root/tslint.json`:

```json
{
    "extends": [
        "./coding-standard/tslint-defaults.json"
    ],
    "rules": {}
}
```

`root/sub1/tslint.json`:

```json
{
  "rulesDirectory": [
    "./node_modules/tslint-microsoft-contrib",
    "./node_modules/tslint-clean-code/dist/src"
  ],
  "extends": [
    "./node_modules/coding-standard/tslint-defaults.json"
  ],
  "rules": {
     // redacted
  }
}
```

I do see `TSLint` in the status bar at the bottom.

When I go to "tslint" in "OUTPUT" I see:

```
[Info  - 1:02:56 PM] Linter is running.
```

And nothing else.

When I open the sub-directories in VSCode as the root, it works!

```
code ./sub1
# Now the expected TSLint errors show up within the new editor where workspace = sub1!
```

When I run `tslint` manually (from package.json of sub1, sub2, etc) it works!

```
tslint --config tslint.json "{src,test}/**/*.{ts,tsx}"
# Tons of errors I see.
```

When I run a global `tslint` in Terminal when current working directory is `root/`:

```
❯ tslint --config tslint.json "sub1/{src,test}/**/*.{ts,tsx}"
# No linting errors!

❯ tslint --config cacheback/tslint.json "cacheback/{src,test}/**/*.{ts,tsx}"
# All of my expected linting errors!
```

Is there any more information I could provide? I am uncertain how to debug this issue. We have a lot of sub-directories which are actually Git submodules (sub-projects) and I am not able to expect my team to open each sub-directory in a new VSCode window. Any help would be greatly appreciated!

**Comment by volodymyrrudyi** [comment]
Hi, everyone. Thanks a lot for such a great plugin. Monorepo structure with separate tslint configs for each package really lacks this feature.

**Comment by volodymyrrudyi** [comment]
Possible workaround: add a tslint.config to the root directory

**Comment by volodymyrrudyi** [comment]
Not sure what changed, but after adding a top-level tslint.json configs in subdirectories also were loaded.

**Comment by egamma** [comment]
@Glavin001 can you pls try whether the issue you describe still exists in the latest 1.0.6, the implementation has changed. If the issue still exist please open a new and separate issue.

**Comment by egamma** [comment]
@volodymyrrudyi if you think there is an issue please file a separate issue with steps to reproduce the problem.
