### ISSUE TITLE
linterOptions.exclude not working

### ISSUE THREAD

**Issue by jwhitmarsh** [Microsoft/vscode-tslint#393]
- tslint 5.11.0:
- typescript 3.0.3:

Steps to Reproduce:

tslint config: 
```
  "linterOptions": {
    "exclude": [
      "node_modules/**",
      "./src/data/**"
    ]
  },
```

Warnings shown for files in the excluded directory:
![screen shot 2018-09-26 at 10 48 44](https://user-images.githubusercontent.com/8026009/46072268-d4313b80-c179-11e8-820b-41848fd22e88.png)

Have I configured this incorrectly? Running the tslint cli does not return the unwanted warnings, so I don't think it's a configuration problem.

**Comment by egamma** [comment]
linterOptions.exclude is supported. Your snippet looks OK to me, but it lacks the full tslint.json context. 

Here is an example where it seems to work https://github.com/Dart-Code/Dart-Code/blob/65a2b89e8dce364bfe352914ad001d4fe478084f/tslint.json#L6-L9

**Comment by jwhitmarsh** [comment]
Apologies - I realised i'm running vscode-tslint _and_ vscode-tslint-vue which is the extention causing the problem. Thanks for your quick response and sorry for wasting your time :(
