### ISSUE TITLE
use fixer, but silence error squiggles

### ISSUE THREAD

**Issue by aleclarson** [Microsoft/vscode-tslint#395]
Is there a way to enable a fixable rule, but disable the UI squiggles?

**Comment by egamma** [comment]
VS Code does not support diagnostics without squiggles. Why do you want to disable the squiggles? Have you tried to validate on save only and not as you type?

**Comment by aleclarson** [comment]
> Have you tried to validate on save only and not as you type?

Sorry, I should have RTFM. `"tslint.run": "onSave"` fixes my issue. Thanks!
