### ISSUE TITLE
Class name must be in pascal case (class-name) doesn't have auto-fix

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode-tslint#396]
- tslint Version:5.11.0
- typescript Version:3.1.1

Steps to Reproduce:

1. Trigger the above warning
2. No auto fix rule is suggested

**Comment by egamma** [comment]
The pascal case rule has no fixer, pls see https://palantir.github.io/tslint/rules/. Please file a feature request or even better provide a PR with a fixer to tslint.
