### ISSUE TITLE
Support vue single file components

### ISSUE THREAD

**Issue by axin** [Microsoft/vscode-tslint#397]
Please consider adding support for vue single file components (https://vuejs.org/v2/guide/single-file-components.html). It is done in this extenstion: https://github.com/prograhammer/vscode-tslint-vue, but it is not updated for a long time.

**Comment by egamma** [comment]
@axin I agree that lint support would be great, but this should really come from a tslint extension and not be done at the level of vscode-tslint, otherwise the vue-linting will only be available in VS Code. Therefore please file the issue against tslint, when it doesn´t exist already.
