### ISSUE TITLE
Avoid that the rule name is shown twice in the error message

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-tslint#398]
From https://github.com/Microsoft/vscode/issues/49215#issuecomment-425391996

 > I see diagnostic code is being repeated in message part for TS Lint diagnostics. Is it possible to remove them from the message?

**Comment by oNexiaoyao** [comment]
the rule name is not shown in the error message now when I write code in VSCode

**Comment by egamma** [comment]
It is also not shown in the hover. Considering to change the fix so that vscode-tslint does not set the diagnostic.code  and includes the rule name in the message.

@sandy081 what do you think? Do you plan to show the code in the inline error message and the hover? The tslint rule-names are not strictly an error code, but I liked the aligned rendering in the Problems view.

**Comment by oNexiaoyao** [comment]
Thanks, I find the tslint rule-names shown in the Problems view. however, It may be not suitable for me to get the tips in the Problems view. Show it in the hover can be better

**Comment by sandy081** [comment]
I would expect the code to be displayed also in inline error message and hover. It was discussed already but forgot to track it in an issue - https://github.com/Microsoft/vscode/issues/60749

**Comment by egamma** [comment]
@fzaninotto you do not see the rule name in the problems view anymore? I assume then you are not using the latest version of VS Code, that is, 1.28.2?

A simple fix is to only enable this version of the extension when VS Code is at version level 1.28.

**Comment by fzaninotto** [comment]
I'm on 1.28.1, and VSCode doesn't propose any upgrade.

**Comment by egamma** [comment]
The change to show the diagnostic code is in 1.28. 
Can you confirm that the rule name doesn´t appear in the problems view? Can you please add a screenshot of the problems view with tslint diagnostic.

**Comment by fzaninotto** [comment]
VSCode has now upgraded to 1.28.2. I see the name in the problems window:

![image](https://user-images.githubusercontent.com/99944/47155564-529a7c80-d2e5-11e8-8e5a-a65b8b8931a9.png)

But I'd never think about clicking the icon if you hadn't told me. I'd prefer the rule name to appear in the alert.

![image](https://user-images.githubusercontent.com/99944/47155661-7eb5fd80-d2e5-11e8-8f5c-350401c5acc0.png)

**Comment by egamma** [comment]
This is what I meant by the Problems view. Also the insider build includes the rule name in the hover and the error message in the editor.

![image](https://user-images.githubusercontent.com/172399/47162389-23d7d280-d2f4-11e8-895f-59e461918864.png)
