### ISSUE TITLE
[tslint] ' should be " (quotemark)  <--- this happen in some vscode

### ISSUE THREAD

**Issue by peterremote1980** [Microsoft/vscode-tslint#403]
[tslint] ' should be " (quotemark)  <--- this happen in some vscode, but not all. In my mac which is ok.

- tslint Version: 1.28.2
- typescript Version: how can i know?

Steps to Reproduce:

just open my project

![untitled](https://user-images.githubusercontent.com/36571333/47255294-570b9480-d4a1-11e8-82c6-2ba374ec1d01.png)

**Comment by egamma** [comment]
>just open my project

@peterremote1980 how can I open your project so that I can reproduce this?

**Comment by peterremote1980** [comment]
Attachment is the error screen and the error project. Actually i just used latest yo@microsoft/sharepoint to create a empty SPO webpart project. Thanks for helping.
![1](https://user-images.githubusercontent.com/36571333/47441464-c73c5200-d7e2-11e8-85d6-51190daeaaad.png)
[Test.zip](https://github.com/Microsoft/vscode-tslint/files/2511112/Test.zip)


my vscode settings.json:
`
{
    "workbench.iconTheme": "material-icon-theme",
    "explorer.confirmDelete": false,
    "git.autofetch": true,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "git.confirmSync": false,
    "editor.renderIndentGuides": false,
    "html.format.wrapLineLength": 0,
    "git.enableSmartCommit": true,

    "material-icon-theme.showWelcomeMessage": false,
    "workbench.startupEditor": "newUntitledFile",
    "editor.tabSize": 4,
    "editor.insertSpaces": false,
    "editor.detectIndentation": false,
    "workbench.editor.enablePreview": false,
    "workbench.list.openMode": "doubleClick",
	"explorer.autoReveal": false,
	"tslint.autoFixOnSave": true
}
`

**Comment by egamma** [comment]
I can reproduce the error shown on the screen but this is not a tslint error, it from TypeScript

![image](https://user-images.githubusercontent.com/172399/47484255-90465a80-d83b-11e8-9934-c695eb351b43.png)

Also in your tslint.json I don´t see that you enable the rule for quotes.

When this problem happens the next time can you check whether you get the same error when you trun tslint from the command line.

**Comment by peterremote1980** [comment]
sorry i messed you up by capturing wrong image. This problem really exist. I fixed it by copy the tslint.json to the root folder. My project is old, at the time i create it, the tslint.json was in config folder. I believe microsoft has changed tslint.json to root folder, thanks

**Comment by egamma** [comment]
Can you reproduce it when you run tslint from the command line?
