### ISSUE TITLE
The 'no-boolean-literal-compare' rule requires type information

### ISSUE THREAD

**Issue by miltonbecker** [Microsoft/vscode-tslint#404]
- tslint Version: 5.11
- typescript Version: 1.28.2

Steps to Reproduce:

1. Install the mentioned tslint version and also tslint-config-airbnb (latest version, as of now it is 5.7.0)
2. On tslint.json, add `"extends": ["tslint-config-airbnb"]`
3. Open a .ts or .tsx file on vscode
4. Check the output for tslint, it will say "Warning: The 'no-boolean-literal-compare' rule requires type information."
5. Real time linting doesn't work because of it

I've found on https://github.com/palantir/tslint/issues/3864 that a possible workaround for it is to pass "--project tsconfig.json" to tslint.

Could you add an option to pass this parameter within the vscode-tslint extension?

Thank you

**Comment by egamma** [comment]
Timely request ;-)

We are working on a new implementation of the extension that supports rules that require type information (this is more involved then adding an option to pass the parameter).

We have just published a first this extension, please give it a try https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin

**Comment by miltonbecker** [comment]
Oh, nice to hear it! :)

But, I've tried it and couldn't get it to work.
I did a `yarn add -D typescript-tslint-plugin` and added it to the plugins section in tsconfig.json.

Am I missing something?

**Comment by egamma** [comment]
You just need to install the extension it will come with the typescript-tslint-plugin.
You need to have tslint and typescript installed as before.

Anyways, if it doesn´t work then continue the discussion in the other repository.
