### ISSUE TITLE
Support config using tslint.js 

### ISSUE THREAD

**Issue by Hanruis** [microsoft/vscode-tslint#409]
In some cases, old project have a eslint configuration. we want to transform some eslint rules to tslint.
And there is a library do so  https://github.com/teppeis/tslint-import-eslint-config

but vscode-tslint seems not support confg by tslint.js file

**Comment by egamma** [comment]
@Hanruis do you have a pointer to the documentation that tslint supports configuration through tslint.js? I could not find it described in this doc https://palantir.github.io/tslint/usage/configuration/

**Comment by egamma** [comment]
@mjbvz something to consider for the tslint-plugin.

**Comment by mjbvz** [comment]
This issue is tracking support on the plugin side: https://github.com/Microsoft/typescript-tslint-plugin/issues/34

**Comment by mjbvz** [comment]
Closing this as upstream. You should be able to set a config file explicitly using the plugin's `tslint.configFile` setting. I just tried this for a basic `tsconfig.js` and it works
