### ISSUE TITLE
Autofix option is not available and/or not doing anything

### ISSUE THREAD

**Issue by aleksey-sh** [Microsoft/vscode-tslint#410]
Hi! I am not exactly sure whether this is a problem or not or whether I maybe be just missing something. So any help or tips will be appreciated.

Problem is that I do not seem to have auto fix option available when I click the light bulb over the error line and choosing option to "TSLint: Fix all auto-fixable options" from Ctrl+Shift+P does not do anything. I do get "Disable rule" option however. (see screenshot below)

![image](https://user-images.githubusercontent.com/26824059/48962395-6e7ce800-ef4d-11e8-9ff1-8461ffe5a8bb.png)

I tried uninstanning/installing plugin, restarted VS Code several times. Not sure what else I may be missing.

package.json
- tslint Version: 5.11.0
- typescript Version: 3.1.1

vscode 
- Installed TSLint plug-in: 1.0.40

Anyone got any thoughts?

**Comment by egamma** [comment]
It looks like the indent rule is failing. Indent should have a fixer, therefore I would have expected that there is a fix.

Please provide a minimal test case (tslint.json, sample.ts file) that allows to reproduce the issue.

**Comment by ly-cultureiq** [comment]
just noting that https://palantir.github.io/tslint/rules/indent/ mentions that the indent size parameter needs to be specified for auto fixing to work

**Comment by aleksey-sh** [comment]
@ly-cultureiq Bingo! That was it!
