### ISSUE TITLE
Unexpected 'Class name must be in pascal case'

### ISSUE THREAD

**Issue by EnKrypt** [Microsoft/vscode-tslint#412]
- tslint Version: 5.11.0
- typescript Version: 3.1.1

![](https://i.imgur.com/gii1u6a.png)

I'm getting this error strangely on identifiers that are not class names.

This is happening randomly across my Angular 7 project for no apparent reason. Affects any kind of const defined variable, even if they are typed.

**Comment by egamma** [comment]
This looks like an issue with this particular rule, please file the issue against the tslint repository.

**Comment by OleksyKor** [comment]
I had the same issue. Solved by `rm -rf node_modules` and reinstall everything with npm instead of yarn
