### ISSUE TITLE
Fix all auto-fixable problems not working

### ISSUE THREAD

**Issue by muyu66** [Microsoft/vscode-tslint#414]
- tslint Version: 5.11.0
- typescript Version: 2.9.2, 3.2.2
- vscode Version:  1.30.0

Steps to Reproduce:

1. input command "Fix all auto-fixable problems", nothing happened.
2. Tslint show Output, no exceptions are displayed

Tip:
VSCode is 1.29.2, tslint is normal.

**Comment by joscarras** [comment]
Same here.

I realize it stopped working last night. 


TSLint Version: 1.0.41

VSCode:
Version: 1.30.0
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:21:33.585Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.9.0-8-amd64

**Comment by Rumpel78** [comment]
No auto fixing with TSLint Version 1.0.41
Works with TSLint Version 1.0.40

**Comment by NicholaAlkhouri** [comment]
Same for me, the command itself is not working,
however if you click on the bulb next to the error, in the problems tab, then choose "Fix all: trailing whitespace" for example it works

**Comment by VictorQueiroz** [comment]
Same here, I can also reproduce what @NicholaAlkhouri mentioned. TSLint extension version is 1.0.41.

**Comment by egamma** [comment]
@Rumpel78 I cannot reproduce this, auto fix on save works for be in both 1.0.40 and 1.0.41.

My test-case:
- git clone vscode-tslint
- open the folder https://github.com/Microsoft/vscode-tslint/tree/master/tslint-tests
- open .vscode/.settings.json and enable the setting tslint.autoFixOnSave, save the file
- open the file `tests/overlapping-fixes.ts`
- add a white space to the file
- save the file
-> the tslint warning are auto fixed

Can someone provide a reproduceable case in a repo that would help with reproducing the issue.

**Comment by evgsil** [comment]
Have the same situation: command "TSLint: Fix all auto-fixable problems" doesn't work, unless  "tslint.autoFixOnSave" is true

**Comment by jedster1111** [comment]
I think it's to do with this commit: 5c65808 where the default value for the setting `tslint.autoFixOnSave` was changed.

If I add `"tslint.autoFixOnSave": false` to my user settings, fix all auto-fixable problems works again for me.

I don't fully know what the changes in 5c65808 do though.

**Comment by VictorQueiroz** [comment]
> I think it's to do with this commit: [5c65808](https://github.com/Microsoft/vscode-tslint/commit/5c658087476195c8bbbd50cd649a79f3662b5923) where the default value for the setting `tslint.autoFixOnSave` was changed.
> 
> If I add `"tslint.autoFixOnSave": false` to my user settings, fix all auto-fixable problems works again for me.
> 
> I don't fully know what the changes in [5c65808](https://github.com/Microsoft/vscode-tslint/commit/5c658087476195c8bbbd50cd649a79f3662b5923) do though. Also I'm not using autosave or format on save.

Confirmed, it works after adding `"tslint.autoFixOnSave": false` to user settings. Thank you!

**Comment by egamma** [comment]
This is fixed in 1.0.42.

**Comment by muyu66** [comment]
already fixed, it's good
