### ISSUE TITLE
New default for autoFixOnSave broke "Fix-all auto fixable problems"

### ISSUE THREAD

**Issue by AGrzes** [Microsoft/vscode-tslint#416]
I noticed that "Fix-all auto fixable problems" stopped working for me today. 
After some investigation I found that:
* `tslintServer.ts` uses `autoFixOnSave` setting to filter fixes
* The default for `autoFixOnSave` was changed from `false` to `['RuleName']` 5c658087476195c8bbbd50cd649a79f3662b5923
* I assume that the new default was released with latest `1.41` version
* While previously default was not to fix anything on save and fix everything that is possible on "Fix-all auto fixable problems" action now effectively it means that problem will be fixed on both cases.

I would suggest to at least document the effect of the change as I spent few hours tracing the source of changed behavior.

**Comment by egamma** [comment]
@AGrzes thanks for tracking this down. I've seen several complaints on this https://github.com/Microsoft/vscode-tslint/issues/414. I'll role back the change and make a new version available.

**Comment by egamma** [comment]
Published new version 1.0.42
