### ISSUE TITLE
is it support with git diff lines or only works on the changed lines 

### ISSUE THREAD

**Issue by hello-chenchen** [microsoft/vscode-tslint#422]
Hi, for our team, there are many tslint errors highlight on a typescript file.
but these errors highlight was written by other team. we don't want to change other team's source code.
So, i want to know is it support with git diff lines or the changed lines?
If, not support, can you log a new feature for this requirement.
Thanks~

**Comment by egamma** [comment]
pls see https://github.com/microsoft/vscode-tslint/blob/main/tslint/README.md#vscode-tslint-deprecated
