### ISSUE TITLE
Suggestion: "Fix all auto-fixable problems" analogue that uses type information

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode-tslint#425]
- tslint Version: 5.12.1
- typescript Version: 3.3.2

Steps to Reproduce:

1. Have an unused import and "no-unused" tslint rule enabled
2. Trigger "Fix all auto-fixable problems"
3. Due to the type information limitation, the unused will not be deleted.

I currently get around this by adding the following task:
```
{
  "label": "lint",
  "type": "shell",
  "command": "tslint -p ${workspaceRoot}/tsconfig.json -c ${workspaceRoot}/tslint.json --fix"
}
```

But as I don't know of a way to define global tasks (is there one?), I need to replicate this in all projects. It would be nice if there were something built in to tslint that did the same.

**Comment by JacksonKearl** [comment]
I understand that you don't want the live tslint instance to use type info as that would duplicate a bunch of tsc's background work, but I think having a one-off command for it would be helpful.

**Comment by egamma** [comment]
@JacksonKearl good news for you, this has been addressed in the new tslint extension please switch to https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin. We will deprecate this extension soon.
