### ISSUE TITLE
Exports added after references added, don't always get picked up

### ISSUE THREAD

**Issue by RavenHursT** [Microsoft/vscode-tslint#426]
- tslint Version: 5.12.1
- typescript Version: 3.2.4

Steps to Reproduce:

1. Open a `.ts` file that has destructured imports from a `.js` file.
2. Add a new symbol to the import that's not yet exported in the js file
3. Notice the new symbol is correctly underlined as _not_ exported
4. Go add an export that matches that symbol
5. Go back to the ts file.

Notice, the tslint error is not resolved, even though the symbol _is indeed_ now exported from the referenced module:

![image](https://user-images.githubusercontent.com/496983/52506835-7267f000-2bb5-11e9-92c6-a062182b4f27.png)

Screencap: https://i.ibb.co/Gpmtdsq/vscode-bug.gif

**Comment by egamma** [comment]
@RavenHursT errors prefixed with `[ts]` are from the TypeScript and not tslint, pls report the issue in the TypeScript repository.
