### ISSUE TITLE
Clarify deprecation status of egamma.tslint

### ISSUE THREAD

**Issue by MLefebvreICO** [Microsoft/vscode-tslint#429]
Hi there,

Wondering since `egamma.tslint` is considered `deprecated`, what does this means for us developpers using versions of TypeScript lower then 3.2 ?

Will the extension still be available for some time or will it be burried to the ground at some point ?

We cannot upgrade yet as our codebase is huge and has dependencies on external libraries that would need to be upgraded too.

So, do we need to plan to upgrade all that soon or are we still okay for now ?

**Comment by egamma** [comment]
>what does this means for us developpers using versions of TypeScript lower then 3.2 ?

We will keep the extension around for a while, but we will not add new features, this includes supporting a newer release of tslint e.g. 6.0.
