### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vladsanchez** [microsoft/vscode-tslint#433]
- Issue Type: `Performance`
- Extension Name: `tslint`
- Extension Version: `1.0.43`
- OS Version: `Darwin x64 16.7.0`
- VSCode version: `1.32.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/vladimirsanchez/eg2.tslint-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by egamma** [comment]
pls see https://github.com/microsoft/vscode-tslint/blob/main/tslint/README.md#vscode-tslint-deprecated
