### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by siddhantsoni** [microsoft/vscode-tslint#435]
- Issue Type: `Performance`
- Extension Name: `tslint`
- Extension Version: `1.0.43`
- OS Version: `Darwin x64 17.4.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/soni.siddhant/eg2.tslint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by siddhantsoni** [comment]
[eg2.tslint-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-tslint/files/3151920/eg2.tslint-unresponsive.cpuprofile.txt)
PFA the log file requested.

**Comment by egamma** [comment]
pls see https://github.com/microsoft/vscode-tslint/blob/main/tslint/README.md#vscode-tslint-deprecated
