### ISSUE TITLE
1.2.0 - Cannot read tslint configuration - 'linterConfiguration.rules.delete is not a function'

### ISSUE THREAD

**Issue by FatalMerlin** [microsoft/vscode-tslint#437]
- tslint Version: 5.17.0
- typescript Version: 3.5.1

Steps to Reproduce:

1. Create new Microsoft SPFx 2016 onPrem solution (`yo @microsoft/sharepoint`)
2. Remove invalid extends configuration from `tslint.json` (Line 2)
3. Open `.ts`-file
4. Check VSCode Problems Output:

![image](https://user-images.githubusercontent.com/14237330/59756832-c8971f00-928a-11e9-9e03-5c49f9b23176.png)

**Comment by FatalMerlin** [comment]
Nvm, I just realized that Google mislead me to the deprecated repo, sorry

**Comment by beporter** [comment]
But...where's the issue in the new repo? What's the fix? 😭

**Comment by IGx89** [comment]
Running into this error myself as well...

**Comment by IGx89** [comment]
Fix for me was clicking the typescript version box on the bottom right of the toolbar and changing it from "Use VS Code's Version (3.5.2)" to "Use Workspace Version (2.9.2)"

**Comment by beporter** [comment]
> Fix for me was clicking the typescript version box on the bottom right of the toolbar and changing it from "Use VS Code's Version (3.5.2)" to "Use Workspace Version (2.9.2)"

In my case I actually tried that already. And tried completely restarting VSCode itself-- no change from either.
