### ISSUE TITLE
Cannot read tslint configuration

### ISSUE THREAD

**Issue by moostad** [Microsoft/vscode-tslint#44]
Getting following  ```info``` after update to new version  (0.5.21) on mac
```vscode-tslint: Cannot read tslint configuration - 'linter.findConfigurationPath is not a function'```

osx 10.11.3
vscode insider 0.10.15

**Comment by egamma** [comment]
Oops, `findConfigurationPath` is only available in more recent tslint versions. Upgrading to to tslint 3.7 avoid this, but the vscode-tslint needs to support older versions as well.

**Comment by egamma** [comment]
Republished a new version

**Comment by bcherny** [comment]
Seeing this same error on startup with the most recent tslint:

<img width="1033" alt="screen shot 2016-11-20 at 2 03 33 pm" src="https://cloud.githubusercontent.com/assets/1761758/20466550/597864e4-af2a-11e6-9b4c-0d7b54a2efe9.png">

- tslint: 4.0.1
- vscode-tslint: 0.5.40
- vscode: 1.6.1

**Comment by egamma** [comment]
@bcherny pls see #123. Work around is to downgrade tslint to 3.5.12.

**Comment by bcherny** [comment]
Ha, just commented with the same workaround. What's the dependency on Gulp/Grunt?

**Comment by egamma** [comment]
No strong dependency, but I assume that many users use the tslint plugins/extensions for gulp and grunt as well. It simplifies things when there is a peer dependency to the same tslint version.

**Comment by bcherny** [comment]
Makes sense. Thanks for the great plugin @egamma!

**Comment by DrMabuse23** [comment]
Sorry thats really the solution use an old version ?

**Comment by egamma** [comment]
@DrMabuse23 this is the solution until the PR https://github.com/Microsoft/vscode-tslint/pull/125 with the update to the changed tslint API is published. I expect to do this today.

**Comment by DrMabuse23** [comment]
👍 @egamma thx for info

**Comment by egamma** [comment]
@DrMabuse23 updated extension with support for tslint 4.0 has  been published.

**Comment by DrMabuse23** [comment]
@egamma Wow fast Support thx
