### ISSUE TITLE
Typescript and Javascript Language Features extension

### ISSUE THREAD

**Issue by pwaweru** [microsoft/vscode-tslint#443]
Issue Type: <b>Bug</b>

Seeing a spinner with 'Initializing JS/TS language features'. Spinner is not resoving and the following error appears:

`The TypeScript language service died 5 times right after it got started. The service will not be restarted.`

Extension version: 1.0.44
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

**Comment by egamma** [comment]
This message is triggered by the TypeScript extension. Please report the issue with as much context as possible for how to reproduce against this extension.
