### ISSUE TITLE
tslint 3.7 config file changes are not applied

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-tslint#45]
Since tslint 3.7 a change to the tslint config file is not applied automatically anymore, you have to reload the window.

**Comment by egamma** [comment]
Fixed by 898d23c68a328ff7289d8cd7f95abb2f0da41da7.

@unional this is caused by the fact that tslint now is loading the config file using `require` and as a consequence it is only loaded once and then fetched from the cache. I think this was done for the new extends feature. However, I wonder why the config file has to be loaded using require. If it is done to get the node module lookup, then you could also use the `locate` function and then load and parse the JSON file. Parsing the JSON file by tslint also as the benefit that tslint could provide support for comments inside the config file as it is done by `eslint`. The way I've tried to fix this for now is to remove the config file from the node module cache (see the commit). This is a work around and it would be better when tslint does not `require` the tslint.json. What do you think?

**Comment by unional** [comment]
> then you could also use the locate function and then load and parse the JSON file. Parsing the JSON file by tslint also as the benefit that tslint could provide support for comments inside the config file as it is done by eslint.

That would be great. Let me talk to the guys in `tslint` and probably open a PR on this.
Thanks for the tip!

**Comment by egamma** [comment]
Actually we have the code snippet to remove comments from a JSON file that I'd be happy to dig out.

**Comment by unional** [comment]
That would be even better. :+1:

**Comment by unional** [comment]
When you mention the `locate` function, which `locate` function are you refer to?

**Comment by egamma** [comment]
Sorry, it is `require.resolve`

>Use the internal require() machinery to look up the location of a module, but rather than loading the module, just return the resolved filename.

**Comment by unional** [comment]
So seems like this is the line that cause the problem:
https://github.com/palantir/tslint/blob/master/src/configuration.ts#L139
Since
https://github.com/palantir/tslint/blob/master/src/configuration.ts#L138
Already use `require.resolve` to resolve the file path, it can read the file directly.

**Comment by egamma** [comment]
Yes exactly.

**Comment by unional** [comment]
Ok. Late here, will do it tomorrow. :+1:

**Comment by egamma** [comment]
Sounds good, I'll dig out the comment stripping code. Have a good rest :zzz:

**Comment by egamma** [comment]
Here is the code poiner to strip comments from JSON as it is done by vscode-jshint
https://github.com/Microsoft/vscode-jshint/blob/master/jshint-server/src/server.ts#L138

**Comment by JKillian** [comment]
Thanks for discussing this @egamma and @unional. One minor downside to loading/parsing files ourselves as opposed to using `require` directly is that regular `.js` modules can't be loaded as a configuration.

I'm wondering if it would be best in TSLint to just delete cache references as https://github.com/Microsoft/vscode-tslint/commit/898d23c68a328ff7289d8cd7f95abb2f0da41da7 does? Or TSLint could manually load JSON files as https://github.com/palantir/tslint/pull/1129 does, but this won't work correctly for non-JSON files.

**Comment by egamma** [comment]
>One minor downside to loading/parsing files ourselves as opposed to using require directly is that regular .js modules can't be loaded as a configuration.

I see, then why not distinguishing loading of .js files from loading .json files. To support comments in .json files (something I really miss) you will have to treat .json files specially and do some pre-processing.

**Comment by JKillian** [comment]
That's the direction I was thinking as well. In pseudo-pseudocode:

```
filePath = require.resolve(somePath)

if filePath.endsWith("json"):
  config = JSON.parse(stripComments(loadFile(filePath)))
else:
  config = require(filePath)
  delete require.cache[filePath]

return config
```

**Comment by egamma** [comment]
Closing workaround is in place that will not hurt when the next version of tslint has addressed this issue.
