### ISSUE TITLE
Error: Path must be a string. Received null

### ISSUE THREAD

**Issue by Ristaaf** [Microsoft/vscode-tslint#5]
I get this error every time when opening a comparison of a ts file in the GIT panel of VS Code. Happen in all projects I have tried, including a test one with just one simple ts file.

**Comment by serkanyersen** [comment]
Same here.

**Comment by egamma** [comment]
This is unrelated to vscode-tslint. Moving to vscode.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode#711

**Comment by serkanyersen** [comment]
this error is specifically caused by this extension. it goes away when you uninstall ts-lint on vscode. Why do you think it's unrelated to ts-lint?

**Comment by egamma** [comment]
Reopening, thanks for the additional info that the error goes away when ts-lint is uninstalled.
