### ISSUE TITLE
tslint sometimes unusably laggy

### ISSUE THREAD

**Issue by abierbaum** [Microsoft/vscode-tslint#50]
I can't see any pattern yet, but with the latest VSCode and latest vscode-tslint, I run into times where the linting is *way* behind.  I will see it underlining issues that are no longer and issue and then appear to suddenly "wake up" and start moving around the decorations until it determines there are no issues.  Sometimes these lags can be 20 seconds or more.

It makes it pretty much unusable because I can't trust the decorations.

Has anyone else seen anything like this?  Is there anyway to turn on some debug output of some type that would help me see when the linting is starting and stopping to better judge what is happening?

I really came to be addicted to the live linting in previous versions and am very much missing it now. :(

**Comment by jvbianchi** [comment]
+1

**Comment by egamma** [comment]
@abierbaum which vesion of vscode-tslint are you using, which version of vscode?

@dbaeumer I've upgraded vscode-tslint to the new language-client/server 2.0 node_modules. Do you have any additional insights? Is there a way to enable diagnostics to see more what is going on when this happens?

**Comment by abierbaum** [comment]
@egamma I am using vscode 1.0.0 and vscode-tslint 0.5.23

I also recently added quite a few more rules from tslint-microsoft-contrib, tslint-eslint-rules, and vrsource-tslint-rules.  I suspect that made the entire lint process slower, but would not have expected it to cause this type of delay at times in the vscode UI.

If there was a way to see some console output when a lint check starts and when it stops along with the time it took to run, that may help to track down any pattern or possibly even set of rules that makes it worse.

**Comment by egamma** [comment]
I'll add some instrumentation and console output.

**Comment by abierbaum** [comment]
@egamma After a bit more testing today using vscode with tslint enabled on some of our production code, I am seeing more than just the lag.

I am seeing code flagged in vscode stay flagged as a issue even after the code has been changed to fix it.  In some cases (but not all) the vscode interface never updates no matter how long I wait.  By way of comparison, I have a separate Linux console window running a watched task that executes tslint directly using the exact same tslint configuration file. This is running completely outside of vscode and it shows there are no issues on the code in question and it updates within a few seconds.  

If I force vscode to reload (> Reload Window), then it seems to refresh tslint and see that there are no issues.  But after a while editing code it will go back to showing lag and not updating fully.

Sorry I don't have more specific details pointing to a cause. :(

**Comment by egamma** [comment]
We will add tracing support to all the linters, since someone mentioned a similar issue with ESLint and we cannot explain it. I'll keep you posted.

**Comment by egamma** [comment]
The add tracing support issue Microsoft/vscode-languageserver-node#39

**Comment by abierbaum** [comment]
@egamma I may be missing something simple, but how specifically do I go about getting a plugin running in vscode with this enabled so I can get you the details you need?  (do I need to build something from source, reinstall a plugin or two, how/where do I modify this setting, etc).  Sorry if I am being dense, I just don't quite see how to do this.

**Comment by egamma** [comment]
@abierbaum sorry, I should have outlined the full plan. I will publish a new version vscode-tslint with the new language server modules that have tracing support. In this version of the extension you can enable a setting to trace the requests through a setting. This will allow us to narrow down whether the vscode-tslint server is getting slower or whether the problem is somewhere else. This will likely happen tomorrow.

In the meantime I'd be interested in the memory size of the vscode-tslint server when you suffer from the slow down. What platform are you running on? Once we know this we can tell you how to observe the size of the server.

**Comment by abierbaum** [comment]
I am running on Linux.

**Comment by egamma** [comment]
Then I think the easiest to get info about the vscode tslint server is to run:

>ps -aux | grep tslint

The process of interest is:
 `.vscode/extensions/eg2.tslint-0.5.23/node_modules/vscode-languageclient/lib/utils/electronForkStart`.

If you can include the info for this process then this could be helpful to us

**Comment by abierbaum** [comment]
```
$ ps -aux | grep tslint
allenb    4178 41.1  0.5 928208 94528 ?        S    06:51  37:07 /usr/share/code/code /home/allenb/.vscode/extensions/eg2.tslint-0.5.23/node_modules/vscode-languageclient/lib/utils/electronForkStart /home/allenb/.vscode/extensions/eg2.tslint-0.5.23/server/server.js
```

from htop:

virtual: 906M
res: 94528
shr: 16388

**Comment by egamma** [comment]
This is a lot of memory... and could explain the lagginess. 

Since you can see the lagging did you also update to a newer tslint version.

**Comment by abierbaum** [comment]
@egamma Still running tslint 3.8.1.  I didn't want to change too many things at once, but I can update to whatever version you recommend for testing.

**Comment by egamma** [comment]
@abierbaum no need to change to another tslint version, thanks.

**Comment by abierbaum** [comment]
Just checked after actively using vscode with typescript for the last few hours.  Now memory is at 921M virtual and 106M resident.

**Comment by egamma** [comment]
> Now memory is at 921M virtual and 106M resident.

just to confirm, are you saying that you see 906M after startup?

**Comment by abierbaum** [comment]
Just restarted to check.  I am seeing 915M virtual and 83M resident after a clean restart of vscode.

**Comment by egamma** [comment]
@abierbaum to narrow the issue down, can you please side-install the attached 0.5.22 version of vscode-tslint. This is the version before vscode-tslint upgrade to the 2.0 language server libs.

To side install the extension:
- Download the attached file
- Remove the .zip suffix
- install the extension by running `code tslint-0.5.22.vsix`

[tslint-0.5.22.vsix.zip](https://github.com/Microsoft/vscode-tslint/files/263339/tslint-0.5.22.vsix.zip)

**Comment by abierbaum** [comment]
@egamma Just tried out 0.5.22.  I was able to replicate the issue of lag where I could type well ahead of the linter and see it gradually catching up (ie. it would highlight old things, move the underlines around, etc).  After waiting maybe 15-20 seconds it would catch up.  

It did catch up though so that is good.  I will continue to use it through the weekend and see if I can get to a state where it just doesn't catch up at all.

Also, I checked the memory usage and I am seeing 904M virtual and 88M resident.

Do you have an instrumented version I could try so I could see if removing some of the rules changes the amount of time it takes to run the lint check and maybe the overall lag?  (it would be nice to have some quantitative numbers to see instead of just guessing based upon feel)

**Comment by egamma** [comment]
Thanks for trying, this excludes the upgrade to the language libraries to 2.0 as the culprit.

When the lag happens are there many errors/warnings?

When the lag happens, can you check whether you see exceptions from tslint in the development console `Help>Toggle Developer Tools`.

Can you also include your tslint.json. 

I'll make a version with tracing support available.

**Comment by abierbaum** [comment]
@egamma My tslint.json file is in this gist: https://gist.github.com/abierbaum/664db71cdc32985a2e56275fc7e280c9

I can get the lag to happen when there are only a few open warnings.  I just replicated it in a file that has 4 open warnings.

As far as exceptions, yes, I see 2 exceptions.  The are from two of the vrsource-tslint-rules.  (thanks for the pointer to this window, I didn't know there was a way to see this type of output).

After I disabled those two rules, I don't see the exception anymore but I do see the lag.  (the way I am reproducing it only shows a lag of say ~5-10 seconds but it is pretty consistent).  I have a test suite where I am just quickly typing in a new jasmine test like:

for example if I type the following at a reasonable speed it will start flagging a few issues and then I am done typing I have to wait 5-10 seconds before it will "catch up" while it is flaging and clearing things on code I typed in the past and should now pass.  It almost looks like the system has queued up quite a few checks against the old state of the code and is running those instead of dropping those out of date checks and only testing against the most recent version of the code.

```typescript
 it('test things with tslint', () => {
      let me = 10;
      expect(me).toEqual(5);
});
```

**Comment by egamma** [comment]
>for example if I type the following at a reasonable speed it will start flagging a few issues and then I am done typing I have to wait 5-10 seconds before it will "catch up" while it is flaging and clearing things on code I typed in the past and should now pass.

This hints that the delay/debounce interval for document content changes is too short for tslint. It currently is 100ms. I've attached an instrumented version of the extension, which has the delay increased to 1000ms. Please install it by side loading as you did before.

This version also has support for client tracing that you can enable using the following setting:
```json
	"tslint.trace.server": "messages"
```

You can also set the option to `"verbose"`. The output appears in the output panel and you have to switch to the `tslint` channel using the drop down on the right.

[tslint-0.5.23.vsix.zip](https://github.com/Microsoft/vscode-tslint/files/266579/tslint-0.5.23.vsix.zip)

**Comment by abierbaum** [comment]
@egamma The tslint plugin is now working **much** better. :)

Thanks a million for tracking this down. :tada: 

Maybe it would make sense to have the delay/throttle time configurable as it may only be an issue for people like me with a large number of active rules that just can't be checked fast enough to support multiple checks per second.

**Comment by egamma** [comment]
Good news thanks for your support to track this down ❤️ 

Making it configurable is one option, but we also need to improve the debounce behaviour on the server.

**Comment by egamma** [comment]
@dbaeumer fyi

**Comment by abierbaum** [comment]
@egamma After using vscode with tslint more today I have found that I can still overwhelm it, but it is much harder to do.  If I am typing for a good number of seconds (~5-10) several seconds continuously over multiple lines of code, I can get ahead of it far enough that it takes several seconds to catch up.  Still **much** better than before though.

Does the plugin cancel checks that are registered against old versions of the code or if I am typing pretty consistently for 10 seconds does it run 10 full checks on the file.  (ie. does it do event compression when a check is already out of date before it starts?)  Maybe that is what you mean about better debounce behavior on the server.

Thanks again.

**Comment by egamma** [comment]
>Does the plugin cancel checks that are registered against old versions of the code or if I am typing pretty consistently for 10 seconds does it run 10 full checks on the file. 

The delaying in the version I've sent you is done on the client side. The document changes are delayed for 1s. So if you type one character a second then you get 10 full checks. The right fix is to debounce the checks on the server side, by keeping track of when a validation for a document is in progress.

**Comment by egamma** [comment]
I've implemented debouncing on the tslint-server side and published the change a 0.5.24. 
@abierbaum please verify.

**Comment by abierbaum** [comment]
@egamma Seems to be working great.  I will continue testing more over the weekend.  Thanks so much.

**Comment by egamma** [comment]
@abierbaum great, thanks for verifying and continue to do so.
