### ISSUE TITLE
How to use TSLint vscode extension to lint *.js file?

### ISSUE THREAD

**Issue by frogcjn** [Microsoft/vscode-tslint#51]
How to use TSLint vscode extension to lint *.js file?

Thanks!

**Comment by egamma** [comment]
This is currently not supported. What is the benefit from using tslint over eslint?

**Comment by frogcjn** [comment]
ESLint's global config file is ~/.eslintrc.json
TSLint's global config gile is ~/<any path>/tslint.json

ESLint and TSLint have their own configuration styles.
So if I use TSLint to lint all *.ts and *.js file, may have a good uniform style.

By the way, if there is a A.ts and tsc compile to A.js, I think the A.js should be excluded for TSLint.
if there is a B.js, but no B.ts, then the B.js should be linted.

**Comment by egamma** [comment]
I see, there is a desire to have a single linter configuration for hybrid JS/TS projects. Actually, ESLint is in the process to support the same. ESLint has a pluggable parser and there is work in progress to plugin the TypeScript parser, see https://github.com/Microsoft/vscode-eslint/pull/74.

>By the way, if there is a A.ts and tsc compile it to A.js, I think the A.js should be excluded for TSLint, because it is generated and it's style cannot be configured by TSLint or TSC, so I think it is better to give up lint the generated *.js file.

agreed and this is supported by the filter in the Code explorer. It isn't supported by vscode-tslint. However, even better is to separate the generated .js files into an `out` or `bin` folder that you can then exclude using the vscode-tslint exclude support.

**Comment by egamma** [comment]
This needs support from tslint to be used for .js files. There is an open feature request for this: https://github.com/palantir/tslint/issues/515.

Once tslint supports this we can consider how to support this in vscode-tslint.

**Comment by YuichiNukiyama** [comment]
Now, tslint support linting .js files. see [New feature: lint js files](https://github.com/palantir/tslint/pull/1515)

**Comment by zhaytee** [comment]
I've got the latest version of vscode-tslint (0.5.40) and the latest tslint which supports linting .js files (4.0.0-dev.1). Running tslint from the cli works as expected in my project, but vscode-tslint doesn't seem to be performing the linting on my .js files in the actual editor. In fact, "tslint" isn't showing up as an output option in the bottom console, which suggests that the extension might not be loading correctly or something?

Wondering if vscode-tslint is just supposed to start working with this upstream change, or if some changes to vscode-tslint are needed. Happy to provide any information about my environment/setup if it'll help.

Thanks!

**Comment by egamma** [comment]
@zhaytee pls see https://github.com/Microsoft/vscode-tslint/pull/120
