### ISSUE TITLE
TSLint autoFix should support a Fix all command like ESLint does

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-tslint#52]
In ESLint you can F1 > ESLint: ... to fix all autofixable problems. The advantage is that the command can be bound to a keyboard shortcut if necessary

**Comment by egamma** [comment]
@rlasjunies I see that you have addressed this in https://github.com/rlasjunies/vscode-tslint. Any plans to make a PR with the change?

**Comment by rlasjunies** [comment]
@egamma I'll clean the commits and push it very soon.

**Comment by egamma** [comment]
@rlasjunies great, thanks.
