### ISSUE TITLE
Renamed file still showing in newly-opened 'Problems' report

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-tslint#58]
_From @leegee on June 26, 2016 11:47_

Latest Insiders build, latest OSX El Capitan.

1. Cause a linting error in a JS file.
1. Rename that file within Code
1. Open the 'Problems' report (CMD+SHIFT M)
1. See a the name of the file as it was before renaming
1. Click it, be asked to create the file

_Copied from original issue: Microsoft/vscode#8152_

**Comment by sandy081** [comment]
_From @dbaeumer on June 27, 2016 9:27_

@sandy081 starting with you to see if the view is stale. Reporting wise we should delete old errors and create new ones on a file rename.

**Comment by sandy081** [comment]
@dbaeumer I checked that Problems view is working as expected and not stale. Looks like problem with the ts linter. Because, similar scenario with ts server works properly.

**Comment by egamma** [comment]
Cannot reproduce after fixing #60.
