### ISSUE TITLE
Fix all auto fixable problems in the project

### ISSUE THREAD

**Issue by ValeriiVasin** [Microsoft/vscode-tslint#59]
If you do have a lot of problems in the code (tslint config change or so) - it is annoying to fix each file manually. Moreover, you need to focus on error in order to use "Quick Fix" for the file.

Would be nice to have a command to fix all existing problems in all project file at the same time.

**Comment by vizeke** [comment]
I think it'll already be useful just the tslint.applyAllFixes working with a specific shortcut on a single file without the need to focus on an error.

**Comment by egamma** [comment]
There is now a command exposed to fix all auto fixable problems `tslint.fixAllProblems`.

Fixing all problems in a project can now be achieved by using the tslint command line and the `--fix` argument, e.g.,
```
"scripts": {
    "lint": "tslint tests/*.ts -t verbose",
    "lint-fix": "tslint --fix tests/*.ts -t verbose"
  }
```

Closing this issue.
