### ISSUE TITLE
Inform user when linting failes due to custom rules

### ISSUE THREAD

**Issue by aqm5181** [Microsoft/vscode-tslint#61]
Hi -

Unfortunately for me, TSLint is not running at all. I am getting no errors. Ive tried changing the workspace settings for TSLint (specify config file, use default config) but still no luck.

It does look like the extension is loading as if I fumble the config file, I get an error when loading up a ts file.

I have installed the following locally:
    "tslint": "^3.12.1",
    "typescript": "^1.8.10"

I have the following tslint.json:

{
  "rules": {
    "ban": [true, ["function"]],
    "class-name": true,
    "comment-format": [true,
      "check-lowercase",
      "check-space"],
    "curly": true,
    "eofline": true,
    "forin": false,
    "indent": [true, "spaces"],
    "interface-name": [true, "always-prefix"],
    "label-position": true,
    "label-undefined": true,
    "max-line-length": [true, 180],
    "member-access": true,
    "member-ordering": [true,
      "public-before-private",
      "static-before-instance",
      "variables-before-functions"
    ],
    "no-any": false,
    "no-arg": true,
    "no-bitwise": true,
    "no-conditional-assignment": true,
    "no-console": [true,
      "debug",
      "info",
      "time",
      "timeEnd",
      "trace"
    ],
    "no-consecutive-blank-lines": true,
    "no-construct": true,
    "no-constructor-vars": true,
    "no-debugger": true,
    "no-duplicate-key": true,
    "no-duplicate-variable": true,
    "no-empty": false,
    "no-eval": true,
    "no-internal-module": true,
    "no-require-imports": true,
    "no-shadowed-variable": true,
    "no-string-literal": true,
    "no-switch-case-fall-through": true,
    "no-trailing-whitespace": true,
    "no-unused-expression": true,
    "no-unused-variable": true,
    "no-unreachable": true,
    "no-use-before-declare": true,
    "no-var-keyword": true,
    "one-line": [true,
      "check-open-brace",
      "check-catch",
      "check-else",
      "check-whitespace"
    ],
    "quotemark": [true, "double"],
    "radix": true,
    "semicolon": [true, "always"],
    "object-literal-sort-keys": false,
    "triple-equals": [true, "allow-null-check"],
    "typedef": [true,
      "call-signature",
      "property-declaration",
      "member-variable-declaration"],
    "typedef-whitespace": [true,
        {
            "call-signature": "nospace",
            "index-signature": "nospace",
            "parameter": "nospace",
            "property-declaration": "nospace",
            "variable-declaration": "nospace"
        },
        {
            "call-signature": "onespace",
            "index-signature": "onespace",
            "parameter": "onespace",
            "property-declaration": "onespace",
            "variable-declaration": "onespace"
        }],
    "variable-name": [
      true,
      "check-format",
      "allow-leading-underscore",
      "ban-keywords"
    ],
    "whitespace": [true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-separator",
      "check-type"
    ],
    "no-delete-expression": true,
    "no-missing-visibility-modifiers": true,
    "no-function-expression": true,
    "private-property-underscore": true,
    "ban-functions": [true, "alert", "confirm", "prompt"]
  }
}

any ideas?

**Comment by aqm5181** [comment]
I figured it out! The last few rules are custom rules. If it cant find them, the linter doesnt do anything. Might be worth amending so that it ignores unfound rules or notifies the user that the rules are missing.

**Comment by egamma** [comment]
In 0.5.39 there is a status bar item 'TSLint' that shows the error status and the full error message is shown in a 'TSLint' output channel.
