### ISSUE TITLE
no-consecutive-blank-lines not showing error (only in "Problems" panel)

### ISSUE THREAD

**Issue by MLefebvreICO** [Microsoft/vscode-tslint#63]
Hi there,

I just saw that when the flag `no-consecutive-blank-lines` is set to `true`, it doesn't do a warning in the UI anymore (it used to do a red line and putting the cursor over it would show the warning). But the warning still show in the new `Problems` panel.

That would be great to fix the UI to come back as before through.

EDIT: When we hover the beggining of a line that has this error, the warning will show. But it is missing the red line to show the user this line is problematic. 

See : http://i.imgur.com/AjDZUnq.png

**Comment by egamma** [comment]
@MLefebvreICO 

I'm pretty sure we always had this limitation, since we show squiggles on text ranges. If the text range is empty then you cannot see a squiggle. Do you remember in which version you saw a squiggle?

**Comment by MLefebvreICO** [comment]
@egamma No, I don't remember. However a remember having a red little bar (about 2-3 px wide) on the line that had this warning and hovering would show the same as the screenshot, but at least we knew before that, that we had an error there.

**Comment by egamma** [comment]
VS Code currently cannot show a marker on an empty line.

The best I can recommend for now is to use 'Go to next Error or Warning' F8, when you see a warning in the overview ruler.

![image](https://cloud.githubusercontent.com/assets/172399/18624775/71918bc0-7e4a-11e6-8153-4947b4347a32.png)

**Comment by MLefebvreICO** [comment]
That's weird since I'm pretty sure we had it before, can't remember the version through, but if you cannot do anything for now then alright !

**Comment by egamma** [comment]
This has been fixed upstream by https://github.com/Microsoft/vscode/issues/26446.
