### ISSUE TITLE
lazy load service, only really start it for first TypeScript file

### ISSUE THREAD

**Issue by jokeyrhyme** [Microsoft/vscode-tslint#64]
What I'm experiencing is mostly just a nuisance, but there's a question of efficiency / performance here as well. It appears that the tslint-server is started with each VSCode window, even before I've even opened a TypeScript file, even when the project does not even include any TypeScript files.

Because the tslint-server is always started, I get the toast / snackbar error "Failed to load tslint library" even in projects where it would never make sense for me to have the tslint NPM package installed. Note that I very much appreciate this message for TypeScript projects, it's very helpful in that case.

The majority of my projects use plain JavaScript, although I do hop through several TypeScript projects, too.

I'm not sure whether this issue should be addressed within each language-specific extension (such as this one), or whether this is a more general concern for language-specific extensions within VSCode itself. /shrug

**Comment by jokeyrhyme** [comment]
https://github.com/Microsoft/vscode/issues/9248

**Comment by jokeyrhyme** [comment]
As the primary desire here is to not see irrelevant error messages, perhaps hiding such error messages from non-matching extensions (until a matching document is encountered) would be an alternative approach?

**Comment by egamma** [comment]
@jokeyrhyme thanks for pointing this out and after further investigation we found the root cause to be in vscode. The Issue is now tracked in Microsoft/vscode#9342.

**Comment by jokeyrhyme** [comment]
:)

**Comment by egamma** [comment]
@jokeyrhyme as a stop gap measure I've published a new vscode-tslint version that only shows the 'failed to load tslint library' when there is a 'tslint.json' file in the root of the workspace (commit dc9446384eb06b42eb32212d20f284762e0c04fb)

**Comment by jokeyrhyme** [comment]
Sounds good. Thanks!
