### ISSUE TITLE
TSLint will not report unused variable on constructor parameter with modifier

### ISSUE THREAD

**Issue by litera** [Microsoft/vscode-tslint#65]
If we define type variable through constructor parameter, TSLint will not report _unused variable_.
```typescript
class SomeClass {
    // TSLint will report this variable isn't used
    private unusedVar1: any;
    constructor(
        // TSLint doesn't suggest to remove "private" keyword because of unused variable
        private unusedVar2: any 
    ) {
        // doesn't use this.unusedVar2
    }
}
```

**Comment by egamma** [comment]
This is a tslint issue and not an issue in the tslint integration for vscode.  

@litera Please report tslint issues against the tslint repository.

**Comment by litera** [comment]
Isn't this ts lint repo? it says **vscode-tslint**... Thanks. Resending over to palantir.
