### ISSUE TITLE
TSLint does nothing

### ISSUE THREAD

**Issue by johanalkstal** [Microsoft/vscode-tslint#66]
I've been unable to get tslint to notify me of any errors at all.

I'm using `0.5.33` and VS Code `1.3.1`.

I have a `tslint.json` file.

I have this specified in my `settings.json` file,

```
{
  "tslint.enable": true,
  "tslint.configFile": "./tslint.json",
  "typescript.tsdk": "./node_modules/typescript/lib"
}
```

My rules are as follows,

```
{
  "rules": {
    "member-access": true,
    "member-ordering": [
      false
    ],
    "no-any": true,
    "no-inferrable-types": true,
    "no-internal-module": true,
    "no-var-requires": false,
    "typedef": [
      true,
      "call-signature",
      "parameter",
      "property-declaration"
    ],
    "typedef-whitespace": [
      true,
      {
        "call-signature": "onespace",
        "index-signature": "onespace",
        "parameter": "onespace",
        "property-declaration": "onespace",
        "variable-declaration": "onespace"
      },
      {
        "call-signature": "onespace",
        "index-signature": "onespace",
        "parameter": "onespace",
        "property-declaration": "onespace",
        "variable-declaration": "onespace"
      }
    ],
    "ban": false,
    "curly": true,
    "forin": true,
    "label-position": true,
    "no-arg": true,
    "no-bitwise": false,
    "no-conditional-assignment": true,
    "no-console": [
      false
    ],
    "no-construct": true,
    "no-debugger": false,
    "no-duplicate-key": true,
    "no-duplicate-variable": true,
    "no-empty": false,
    "no-eval": true,
    "no-shadowed-variable": true,
    "no-string-literal": false,
    "no-switch-case-fall-through": true,
    "no-unreachable": true,
    "no-unused-expression": true,
    "no-unused-variable": true,
    "no-use-before-declare": true,
    "no-var-keyword": true,
    "radix": true,
    "switch-default": true,
    "triple-equals": true,
    "eofline": true,
    "indent": [
      true,
      "spaces"
    ],
    "no-require-imports": false,
    "sort-object-literal-keys": true,
    "no-trailing-comma": true,
    "align": [
      true
    ],
    "class-name": true,
    "interface-name": [
      true,
      "always-prefix"
    ],
    "no-consecutive-blank-lines": true,
    "one-line": [
      true
    ],
    "quotemark": [
      true,
      "single",
      "avoid-escape"
    ],
    "semicolon": [
      true,
      "never"
    ],
    "variable-name": [
      true
    ],
    "whitespace": [
      true
    ]
  }
}
```

I know it finds my `tslint.json` file because if I change the path it will warn me about it.

But when I deliberately break rules I'm not getting any signs of it.

Any help would be much appreciated.

**Comment by TylorS** [comment]
Also having the same issue.

**Comment by TylorS** [comment]
This does not occur when downgrading to 1.2.x of VS Code

**Comment by VitalyBrusentsev** [comment]
Had the same problem on one Windows machine, as well as on OS X.
Turned out new tslint (not the extension) was crashing due to an invalid (renamed) rule in tslint.config: "no-trailing-comma".
Please see the related issue:
https://github.com/palantir/tslint/issues/982

**Comment by egamma** [comment]
@johanalkstal in your tslint.json you are using the `no-trailing-comma` rule which has been removed in favor of `trailing-comma` as pointed out by @VitalyBrusentsev above.

Closing this issue as upstream and I'll create a new issue that vscode-tslint should expose tslint crashes to the user.

**Comment by kamranayub** [comment]
I'm having a similar issue but if I run tslint manually it works fine, so I'm not using any broken rules.

VS Code 1.4.0 and TSLint 3.13.0

I'm trying to add it for this repo structure: https://github.com/excaliburjs/Excalibur

We have a `tslint/tslint.json` file, I updated my `settings.json` to point to that (that seems to work? It doesn't throw an error). But when I browse to a ts file in `src/engine` like for example `Engine.ts` nothing displays in VS Code even though there are lint errors.

Am I using the wrong folder structure or something?

**Comment by egamma** [comment]
@kamranayub do you see an error message in the Console of the developer tools?

To open the developer tools use Help>Toggle Developer Tools

**Comment by kamranayub** [comment]
Sorry for the delay, just noticed I was getting errors in the UI now that opened the console.

```
 Could not find implementations for the following rules specified in the configuration:
            no-trailing-comma
            Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
            If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
```

On VS Code 1.5.3 and TSLint 0.5.39 extension version.

**Comment by egamma** [comment]
@kamranayub thanks for the update and I'll keep this issue closed.
