### ISSUE TITLE
Expose tslint crashes to the user

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-tslint#67]
Currently the extension protects itself against tslint crashes, but it doesn't expose them to the user. This makes users think the extension is broken (see #66) as an example. We should show tslint crashes to the user. 

This needs to distinguish between a tslint crash and an incorrect tslint.json configuration file.

**Comment by aluanhaddad** [comment]
@egamma First off, thank you for this plugin! It is absolutely wonderful and has made my time in VSCode much more productive and enjoyable.

I was about to open this issue. An npm package containing a large number of custom rules got updated and I spent a very long time playing with various versions of VSCode, TypeScript, tslint, and editing tslint.json, until I finally saw the errors in Help -> Developer Tools.

This would be a great enhancement.

**Comment by egamma** [comment]
In 0.5.39 there is a TSlint status bar item, shows an error status and the tslint error is shown in the output channel.
