### ISSUE TITLE
"Format Code" causes tslint failure with type assertions

### ISSUE THREAD

**Issue by LOZORD** [Microsoft/vscode-tslint#69]
If I have code like this:

```ts
const bar = <Bar> Thing.getFoo();
```

and then "Format Code" (alt-shift-F on Mac), I get this:

```ts
const bar = <Bar>Thing.getFoo();
```

The missing space after the closing angled bracket causes a spacing failure with tslint. I removed the settings in my `.vscode/settings.json` that have to do with JS/TS spacing, and the error still occurred. Is there something else I can configure to solve this?

**Comment by egamma** [comment]
Format Code is provided by `vscode`. Moving the issue to vscode.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode#10296
