### ISSUE TITLE
Allow node_modules/tslint to exist in subdirectory

### ISSUE THREAD

**Issue by neelance** [Microsoft/vscode-tslint#72]
With typescript itself I can use a `.vscode/settings.json` file like this to make vscode use the typescript installation provided in a subdirectory:
```
{
	"typescript.tsdk": "./ui/node_modules/typescript/lib"
}
```
I'd like to be able to do the same for vscode-tslint to make it use the tslint installation at `./ui/node_modules/tslint` without having to use `./ui` as the workspace root.

**Comment by neelance** [comment]
Btw: My `tslint.json` is also located in that subdirectory: `./ui/tslint.json`

**Comment by egamma** [comment]
version 0.5.39 now supports a `tslint.nodePath` option that can be configured to add an additional node_modules folder to the lookup path.

**Comment by neelance** [comment]
Thanks!
