### ISSUE TITLE
Error when using scoped package in "extends"

### ISSUE THREAD

**Issue by frederickfogerty** [Microsoft/vscode-tslint#75]
Hi there! Thanks for creating this awesome extension for VSCode. ❤️  

I found a small problem where the extension would complain that it couldn't find my configuration file when I used a scoped package (i.e. `@organisation/package-name`). I'll outline my config below.

```json
// tslint.json
{
  "extends": "@company/typescript/tslint"
}

// @company/typescript/tslint.json (real location: ./node_modules/@company/typescript/tslint.json)
{
  "extends": [
    "tslint:latest",
    "tslint-react"
  ],
  "rules": {
    // ...
  }
}
```

This is the error I get when I have it configured as above.

>vscode-tslint: Cannot read tslint configuration - 'Invalid "extends" configuration value - could not require "@company/typescript/tslint". Review the Node lookup algorithm

When I change my root tslint.json to the following it finds the file okay. 😕 
```json
{
  "extends": "./node_modules/@seeeverything/typescript/tslint.json"
}
```

Just to be clear, this problem only occurs in VSCode - running `tslint` on the command line works fine with either configuration.

vscode-tslint version: `0.5.34`
tslint version: `3.15.1`

**Comment by egamma** [comment]
I cannot reproduce this with the latest:

vscode-tslint: `0.5.39`
tslint: `3.15.1`

This is the setup I've used for testing:

![image](https://cloud.githubusercontent.com/assets/172399/18625072/5dcf369e-7e4c-11e6-97f6-0a3554d432c8.png)

**Comment by frederickfogerty** [comment]
Hi @egamma.

I was trying to make a minimal repro for this issue and I ran into a bigger issue. Can you take a look at this? https://youtu.be/1oWDQDGWXps

Thanks
Fred

**Comment by egamma** [comment]
@frederickfogerty thanks for the recording let's extract this into a new issue.
