### ISSUE TITLE
Fix all auto-fixable problems bug when last line needs a semicolon

### ISSUE THREAD

**Issue by Ventajou** [Microsoft/vscode-tslint#80]
If the last line is not empty and needs a fixable column, the `fix all...` option will put a semicolon on the new empty last line instead of the previous last line. 

Example:

```
foo()
```

will become:

```
foo()
;
```

**Comment by egamma** [comment]
@Ventajou 

I cannot reproduce this issue the way I understood the steps above. What do I have to change in the setup described below.

This is the setup that I've tried:

![tslint-bug](https://cloud.githubusercontent.com/assets/172399/18625439/f29974b8-7e4e-11e6-943d-67e2fe46bf59.gif)

`tslint.json`
```json
{
    "rules": {
        "quotemark": [
            true,
            "double"
        ],
        "semicolon": [
            "always"
        ]
    }
}
```

`greeter.ts`
```ts
function foo() {}

foo();
foo();
```

**Comment by Fice** [comment]
Hi, I ran into the same issue. 

Happens when you also set: `"eofline": true`

`export const initialState: ProjectState = null`
becomes
```
export const initialState: ProjectState = null
;
```
(needs to be on the last line obviously)

**Comment by egamma** [comment]
Since tslint 4.0 the quick fix for `semicolon` is now provided by tslint. The corresponding fix in vscode-tslint has been removed.
