### ISSUE TITLE
'Enter' on a quick fix is not working

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-tslint#82]
Steps to reproduce:

- Click on a quick fix (yellow bulb)
- You see a message for eg: `Fix this "Missing Semicolon" tslint failure?`
- Press 'Enter'

Quick fix is not applied.

**Comment by egamma** [comment]
Actually you can also not navigate in the menu of quick fixes using the cursor keys. 
![image](https://cloud.githubusercontent.com/assets/172399/18625177/02d4602e-7e4d-11e6-953f-104d145140a1.png)

Moving to VS Code for investigation.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode#12246
