### ISSUE TITLE
fixes are outdated and can't be applied to the document

### ISSUE THREAD

**Issue by garthk** [Microsoft/vscode-tslint#83]
Problems in **bold**:

* Run `vscode-insiders` version 1.5.0-insider with tslint 3.15.1 globally but 3.10.2 locally:

  * `npm install --global typescript tslint`
  * `npm install typescript tslint@3.10.2`

  (Don't worry: we'll upgrade the local install to 3.15.1 below. Bear with me.)

* Set `"no-trailing-whitespace": true` in `tslint.json`

* Add trailing whitespace to a line

* Hit F8

* Observe error:

      > `[tslint] trailing whitespace`

* Observe offered fix: 

      >💡Fix this "trailing whitespace" tslint failure? 

* Click fix

* Observe **unapplied fix and error message above**:

      > ESLint fixes are outdated and can't be applied to the document

* `%s/ESLint/tslint/g` across the [`vscode-tslint`](https://github.com/Microsoft/vscode-tslint) repo *cough*

* Upgrade from tslint 3.10.2 to 3.15.1

* Repeat above steps up to "Click fix" inclusive

* Observe applied fix and no error message: hooray!

* Click the fix again

* Observe **error message above**:

      > ESLint fixes are outdated and can't be applied to the document

**Comment by egamma** [comment]
@garthk 

>s/ESLint/tslint/g across the vscode-tslint repo cough

Fixed, thanks 😄 

However, I cannot reproduce the error message in the latest with tslint 3.15.1 and vscode-tslint 0.5.39.

Below is the setup and the steps I've tried:

![tslint-bug3](https://cloud.githubusercontent.com/assets/172399/18626339/c24b276a-7e54-11e6-83ed-1c88d33cd887.gif)

Please reopen if you can still reproduce it.
