### ISSUE TITLE
Use fixes from tslint

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/vscode-tslint#84]
In https://github.com/Microsoft/vscode-tslint/pull/47 the plugin started using fixes that only come from the formatter in https://github.com/Microsoft/tslint-microsoft-contrib/blob/d63a56a0f05f7a00d66c677db83aa40a4dae655c/src/utils/BaseFormatter.ts#L13

In https://github.com/palantir/tslint/pull/1423 @ScottSWu added the ability for tslint rules to specify their fixes, as part of the rule Failure.

Note that the data structure used to represent the fix matches what TypeScript is planning in their own "Code Actions" support, see https://github.com/Microsoft/TypeScript/pull/10185

I think we should move towards centralizing all the fixes in the upstream tslint rule, and have the vscode plugin apply the fixes produced in that API.

**Comment by alexeagle** [comment]
(probably the first step is to re-implement the fixes that are currently offered in tslint, so there is feature parity when we change the plugin to use tslint to generate the fixes)

**Comment by rlasjunies** [comment]
Hi @alexeagle,

 I am very happy about this news. I worked a little bit on this feature in vsc-tslint but everybody agree that the fixes should come from tslint engine.

 I would be happy to have a look moving on the current vscode-tslint autoFixes to tslint engine. 

 We stay in touch.

**Comment by alexeagle** [comment]
I'll try adding fixes in tslint for some of the checks in https://github.com/Microsoft/vscode-tslint/blob/master/tslint-server/src/tslintAutoFix.ts

**Comment by alexeagle** [comment]
oh, I should also add: I don't want to spend my time working on formatting lints, because a computer can do this given a formatter (we use clang-format for TypeScript). I actually think a linter is the wrong tool for this, because it forces the user to do meaningless work (even if it's click through many lightbulbs in the editor).

(much longer version: https://medium.com/@Jakeherringbone/why-linting-makes-me-yawn-cadbd9a51ca9#.10a0qdxcc )

Of course, tslint does have these checks today, and some users choose not to use an auto-formatter, so providing fixes for them might be useful. I'm just choosing how to spend my own time :)

**Comment by egamma** [comment]
@alexeagle thanks for bringing this to our attention. This is great news and we can remove the code that relied on string comparing messages.

@rlasjunies I'll merge in our latest PR today and thanks for your continuing support for the auto fix feature.

**Comment by egamma** [comment]
With the adoption of tslint 4.0 we no fully support tslint autofixes including fixes with multiple replacements.
