### ISSUE TITLE
Server initialization failed without TS files in the project

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode-tslint#88]
### Versions:
  
  * **VS Code**: 1.5.2 (stable)
  * **vscode-tslint:** 0.5.37

### Description

I working on project that contains Bash and JS files (project does not have TypeScript files). After some time (5-10 minutes) VS Code showed the Output Panel that contains following message:

![image](https://cloud.githubusercontent.com/assets/7034281/18545926/fbd649b0-7b43-11e6-8e89-45e603dac470.png)

**Console:**

![code_2016-09-15_12-58-04](https://cloud.githubusercontent.com/assets/7034281/18546178/2d26c534-7b45-11e6-943f-d6944bd4f294.png)

**Comment by egamma** [comment]
This is a consequence of upgrading to the 2.5 version of the language libraries. I'll have to implement a custom initialization handler to supress it.

**Comment by egamma** [comment]
fixed via 007e74018208c8a2f1233f838c01bc51831be433 and published vscode-tslint 0.5.39.
