### ISSUE TITLE
Could not load tslint - Server initialization failed

### ISSUE THREAD

**Issue by davidalee** [Microsoft/vscode-tslint#90]
I can't get the tslint extension working in VSC. I've done `npm i -g tslint typescript` and have verified that both are installed both globally and locally (I looked at https://github.com/Microsoft/vscode-tslint/issues/28 before opening this issue). But whenever I open VSC it shows an error:

`vscode-tslint: could not load tslint
[Error - 11:16:39 AM] Server initialization failed.
  Message: null
  Code: 99 
[object Object]`

I'm using tslint 3.15.1, typescript 1.8.10, VSC 1.5.2.

**Comment by davidalee** [comment]
It seems to be working now, I'm unclear why. I did some combination of uninstalling/installing the extension, restarting VSC, restarting my computer, and npm installing globally and locally the tslint and typescript modules.

**Comment by egamma** [comment]
@davidalee the error message that shows up is a bug. I suspect you opened a workspace without a tslint.json?

**Comment by davidalee** [comment]
@egamma Ah, yes I think that was it. I added that file on a whim but did a number of other changes along with it so I didn't realize a missing tslint.json file was the issue.
