### ISSUE TITLE
Bad experience in single file window

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-tslint#91]
1. Open new window, no workspace
2. Change mode to TypeScript
3. Start typing

- Output opens
- Focus is lost from the editor
- Some error messages are strange (`Server initialization failed`, `Message: null`, `[object Object]`)

![bug](https://cloud.githubusercontent.com/assets/22350/18577689/94430b1e-7beb-11e6-9d78-3a2e675f5ad1.gif)

**Comment by egamma** [comment]
fixed via 007e74018208c8a2f1233f838c01bc51831be433 and published vscode-tslint 0.5.39.
