### ISSUE TITLE
Cannot load tslint modules

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-tslint#99]
From @frederickfogerty 

>I was trying to make a minimal repro for this issue and I ran into a bigger issue. Can you take a look at this? https://youtu.be/1oWDQDGWXps

**Comment by egamma** [comment]
Looks related to #77, which was closed by @airstep

@frederickfogerty do you have both tslint and typescript installed globally?
Can you try to repro when you install tslint and typescript locally into a workspace?

**Comment by frederickfogerty** [comment]
Hey @egamma,

I am not able to reproduce this anymore, I am not sure what has changed since my first video.

Thanks for your help 🙌

**Comment by egamma** [comment]
@frederickfogerty thanks following up, closing.
